'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class frmFileDefinitionDetails

    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''UcQMSHeader1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UcQMSHeader1 As Global.QMSWeb.ucQMSHeader

    '''<summary>
    '''vsFileDefs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vsFileDefs As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''tbFileDefName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbFileDefName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvFileDefName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvFileDefName As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ltFileDefID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltFileDefID As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''tbFileDefDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbFileDefDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvFileDefDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvFileDefDescription As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ltTypeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltTypeName As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ddlFileDefTypeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFileDefTypeID As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rfvFileDefTypeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvFileDefTypeID As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ltFileFormatName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltFileFormatName As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ddlFileTypeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFileTypeID As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rfvFileTypeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvFileTypeID As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ltSurveyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltSurveyName As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ddlSurveyID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSurveyID As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rfvSurveyId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvSurveyId As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ddlClientID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlClientID As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tbFileDefDelimiter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbFileDefDelimiter As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvFileDefDelimiter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvFileDefDelimiter As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ibSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibSave As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''hlCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlCancel As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hlExecute control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlExecute As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''pnlFileDefColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFileDefColumns As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''dgFileDefColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgFileDefColumns As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''tblColumnControls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblColumnControls As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''ddlColumnName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlColumnName As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tbPropertyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbPropertyName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''revPropertyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revPropertyName As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''ibAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibAdd As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ibUpdateOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibUpdateOrder As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ibDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibDelete As Global.System.Web.UI.WebControls.ImageButton
End Class
