CREATE NONCLUSTERED INDEX [IDX_BubbleTemp_ExtractFileID] ON [dbo].[BubbleTemp]
(
	[ExtractFileID] ASC
)
INCLUDE ( 	[SAMPLEUNIT_ID],
	[nrcQuestionCore],
	[responseVal],
	[QUESTIONFORM_ID]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]


