CREATE NONCLUSTERED INDEX [IX_ExtractQueueArchive_EntityTypeID] ON [dbo].[ExtractQueueArchive]
(
	[EntityTypeID] ASC
)
INCLUDE ( 	[ExtractFileID],
	[PKey1]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]


