CREATE NONCLUSTERED INDEX [IX_ExtractHistory_PKey1] ON [dbo].[ExtractHistory]
(
	[PKey1] ASC,
	[PKey2] ASC,
	[ExtractFileID] ASC,
	[EntityTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]


