CREATE NONCLUSTERED INDEX [IX_QuestionCoreQUESTIONFORM] ON [dbo].[BubbleTemp]
(
	[nrcQuestionCore] ASC,
	[QUESTIONFORM_ID] ASC,
	[ExtractFileID] ASC,
	[responseVal] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


