'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class frmScriptTriggerDetails

    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''UcQMSHeader1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UcQMSHeader1 As Global.QMSWeb.ucQMSHeader

    '''<summary>
    '''vsScriptScreen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vsScriptScreen As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''ltScriptTriggerID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltScriptTriggerID As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ddlScriptTriggerType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlScriptTriggerType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlSurvey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSurvey As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tbTriggerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbTriggerName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvTriggerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvTriggerName As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''hlTriggerCodeHelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlTriggerCodeHelp As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''tbTriggerCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbTriggerCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvTriggerCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvTriggerCode As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''cuvTriggerCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cuvTriggerCode As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''ibSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibSave As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''hlDone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlDone As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''ltSearchResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltSearchResults As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''dgCriteria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgCriteria As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''pnlCriteria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCriteria As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ibAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibAdd As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ddlCriteriaTypeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCriteriaTypeID As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ibDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibDelete As Global.System.Web.UI.WebControls.ImageButton
End Class
