Public NotInheritable Class SP

    Public Const SelectAllConcurrencyLocks As String = "QCL_SelectAllConcurrencyLocks"
    Public Const SelectAllFacilities As String = "QCL_SelectAllFacilities"
    Public Const SelectAllFacilityRegions As String = "QCL_SelectAllFacilityRegions"
    Public Const SelectAllMethodologyStepTypes As String = "QCL_SelectAllMethodologyStepTypes"
    Public Const SelectAllStudyTables As String = "QCL_SelectAllStudyTables"
    Public Const SelectBusinessRule As String = "QCL_SelectBusinessRule"
    Public Const SelectBusinessRulesBySurveyId As String = "QCL_SelectBusinessRulesBySurveyId"
    Public Const SelectConcurrencyLock As String = "QCL_SelectConcurrencyLock"
    Public Const SelectConcurrencyLocksByCategory As String = "QCL_SelectConcurrencyLocksByCategory"
    Public Const SelectCoverLettersBySurveyId As String = "QCL_SelectCoverLettersBySurveyId"
    Public Const SelectCriteria As String = "QCL_SelectCriteria"
    Public Const SelectCriteriaClauseByStatementAndPhraseId As String = "QCL_SelectCriteriaClauseByStatementAndPhraseId"
    Public Const SelectCriteriaInListByCriteriaClause As String = "QCL_SelectCriteriaInListByCriteriaClauseId"
    Public Const SelectCriteriaPhraseByCriteriaStatementId As String = "QCL_SelectCriteriaPhraseByCriteriaStatementId"
    Public Const SelectEmployee As String = "QCL_SelectEmployee"
    Public Const SelectAllEmployees As String = "QCL_SelectAllEmployees"
    Public Const SelectAllUnAuthEmployees As String = "QCL_SelectAllStudyUnAuthEmployees"
    Public Const SelectEmployeeByLoginName As String = "QCL_SelectEmployeeByLoginName"
    Public Const SelectFacility As String = "QCL_SelectFacility"
    Public Const SelectFacilityByAhaId As String = "QCL_SelectFacilityByAhaId"
    Public Const SelectFacilityByClientId As String = "QCL_SelectFacilityByClientId"
    Public Const SelectFormGenJobsByGenerationDate As String = "QCL_SelectFormGenJobsByDate"
    Public Const SelectHouseHoldingFieldsBySurveyId As String = "QCL_SelectHouseHoldingFieldsBySurveyId"
    Public Const SelectLanguage As String = "QCL_SelectLanguage"
    Public Const SelectLanguagesAvailableForSurvey As String = "QCL_SelectLanguagesAvailableForSurvey"
    Public Const SelectMailingByLitho As String = "QCL_SelectMailingByLitho"
    Public Const SelectMailingByBarcode As String = "QCL_SelectMailingByBarcode"
    Public Const SelectMailingByWAC As String = "QCL_SelectMailingByWAC"
    Public Const SelectMailingsByPopId As String = "QCL_SelectMailingsByPopId"
    Public Const SelectMethodology As String = "QCL_SelectMethodology"
    Public Const SelectMethodologiesBySurveyId As String = "QCL_SelectMethodologiesBySurveyId"
    Public Const SelectMethodologyStepsByMethodologyId As String = "QCL_SelectMethodologyStepsByMethodologyId"
    Public Const SelectMethodologyStep As String = "QCL_SelectMethodologyStep"
    Public Const SelectQualiSysParam As String = "QCL_SelectQualiSysParam"
    Public Const SelectSamplePeriod As String = "QCL_SelectSamplePeriod"
    Public Const SelectSamplePeriodsBySurvey As String = "QCL_SelectSamplePeriodsBySurvey"
    Public Const SelectSampleUnitLinkingsByClientId As String = "QCL_SelectSampleUnitLinkingsByClientId"
    Public Const SelectQuestionSectionsBySurveyId As String = "QCL_SelectQuestionSectionsBySurvey_Id"
    Public Const SelectServiceTypes As String = "QCL_SelectServiceTypes"
    Public Const SelectServiceTypesBySampleUnitId As String = "QCL_SelectServiceTypesBySampleUnitID"
    Public Const SelectStandardMethodologiesBySurveyTypeId As String = "QCL_SelectStandardMethodologiesBySurveyTypeId"
    Public Const SelectStandardMethodology As String = "QCL_SelectStandardMethodology"
    Public Const SelectStandardMethodologySteps As String = "QCL_SelectStandardMethodologySteps"
    Public Const SelectStudyDatasetsByStudy As String = "QCL_SelectStudyDatasetsByStudy"
    Public Const SelectStudyTable As String = "QCL_SelectStudyTable"
    Public Const SelectStudyTableColumn As String = "QCL_SelectStudyTableColumn"
    Public Const SelectStudyTableColumns As String = "QCL_SelectStudyTableColumns"
    Public Const SelectUnscheduledSampleSets As String = "QCL_SelectUnscheduledSampleSets"
    Public Const SelectSampleUnitSectionMappingsBySampleUnitId As String = "dbo.QCL_SelectSampleUnitSectionMappingsBySampleUnit_Id"
    Public Const SelectSamplePeriodScheduledSamples As String = "dbo.QCL_SelectSamplePeriodScheduledSamples"
    Public Const SelectSamplePeriodScheduledSample As String = "dbo.QCL_SelectSamplePeriodScheduledSample"
    Public Const SelectActivePeriodbySurveyId As String = "dbo.QCL_SelectActivePeriodbySurveyId"

    Public Const DeleteApplication As String = "QCL_DeleteApplication"
    Public Const DeleteConcurrencyLock As String = "QCL_DeleteConcurrencyLock"
    Public Const DeleteDataset As String = "QCL_DeleteDataset"
    Public Const DeleteFacility As String = "QCL_DeleteFacility"
    Public Const DeleteFutureMailings As String = "QCL_DeleteFutureMailings"
    Public Const DeleteMethodology As String = "QCL_DeleteMethodology"
    Public Const DeleteMethodologyStepsByMethodologyId As String = "QCL_DeleteMethodologyStepsByMethodologyId"
    Public Const DeleteSampleUnitLinkingsByClientId As String = "QCL_DeleteSampleUnitLinkingsByClientId"
    Public Const DeleteCriteria As String = "QCL_DeleteCriteria"
    Public Const DeleteCriteriaPhrases As String = "QCL_DeleteCriteriaPhrases"
    Public Const DeleteBusinessRule As String = "QCL_DeleteBusinessRule"
    Public Const DeleteSampleUnitServiceBySampleUnitID As String = "QCL_DeleteSampleUnitService"
    Public Const DeleteSampleUnitSectionMapping As String = "dbo.QCL_DeleteSampleUnitSectionMapping"
    Public Const DeleteSamplePeriod As String = "dbo.QCL_DeleteSamplePeriod"
    Public Const deleteSamplePeriodScheduledSample As String = "dbo.QCL_DeleteSamplePeriodScheduledSample"

    Public Const InsertSampleUnitSectionMapping As String = "dbo.QCL_InsertSampleUnitSectionMapping"
    Public Const InsertApplication As String = "QCL_InsertApplication"
    Public Const InsertConcurrencyLock As String = "QCL_InsertConcurrencyLock"
    Public Const InsertFacility As String = "QCL_InsertFacility"
    Public Const InsertMethodology As String = "QCL_InsertMethodology"
    Public Const InsertMethodologyStep As String = "QCL_InsertMethodologyStep"
    Public Const InsertSampleUnitLinking As String = "QCL_InsertSampleUnitLinking"
    Public Const InsertCriteria As String = "QCL_InsertCriteria"
    Public Const InsertCriteriaClause As String = "QCL_InsertCriteriaClause"
    Public Const InsertCriteriaInValue As String = "QCL_InsertCriteriaInValue"
    Public Const InsertBusinessRule As String = "QCL_InsertBusinessRule"
    Public Const InsertAuditLogChange As String = "QCL_InsertChangeLog"
    Public Const InsertSampleUnitService As String = "QCL_InsertSampleUnitService"
    Public Const InsertSamplePeriodScheduledSample As String = "dbo.QCL_InsertSamplePeriodScheduledSample"
    Public Const InsertSamplePeriod As String = "dbo.QCL_InsertSamplePeriod"

    Public Const UpdateApplication As String = "QCL_UpdateApplication"
    Public Const UpdateBusinessRule As String = "QCL_UpdateBusinessRule"
    Public Const UpdateConcurrencyLock As String = "QCL_UpdateConcurrencyLock"
    Public Const UpdateCriteria As String = "QCL_UpdateCriteria"
    Public Const UpdateFacility As String = "QCL_UpdateFacility"
    Public Const UpdateFormGenJobGenerationDate As String = "QCL_UpdateFormGenJobGenerationDate"
    Public Const UpdateFormGenJobPriority As String = "QCL_UpdateFormGenJobPriority"
    Public Const UpdateMethodology As String = "QCL_UpdateMethodology"
    Public Const UpdateMethodologyActiveFlag As String = "QCL_UpdateMethodologyActiveState"
    '    Public Const UpdateMethodologyStep As String = "QCL_UpdateMethodologyStep"
    Public Const UpdateMethodologyStepVendor As String = "QCL_UpdateMethodologyStepVendor"
    Public Const UpdateSamplePeriodScheduledSample As String = "dbo.QCL_UpdateSamplePeriodScheduledSample"
    Public Const UpdateSamplePeriod As String = "dbo.QCL_UpdateSamplePeriod"

    Public Const AllowDeleteFacility As String = "QCL_AllowDeleteFacility"
    Public Const AllowUnassignmentFacility As String = "QCL_AllowUnassignmentFacility"
    Public Const AssignFacilityToClient As String = "QCL_AssignFacilityToClient"
    Public Const ChangeRespondentAddress As String = "QCL_ChangeRespondentAddress"
    Public Const LogContactRequest As String = "QCL_LogContactRequest"
    Public Const RegenerateMailing As String = "QCL_ReGenerateMailing"
    Public Const ScheduleNextMailSteps As String = "QCL_SetNextGeneration"
    Public Const TakeOffCallList As String = "QCL_TakeOffCallList"
    Public Const LogDispositionByLitho As String = "QCL_LogDispositionByLitho"
    Public Const UnassignFacilityFromClient As String = "QCL_UnassignFacilityFromClient"

    'Added 2014.07.18 All Cahps Teams - Sprint 4, User story 6 
    Public Const SelectModeSectionMappingsBySurveyId As String = "QCL_SelectModeSectionMappingsBySurveyId"
    Public Const InsertModeSectionMapping As String = "QCL_InsertModeSectionMapping"
    Public Const DeleteModeSectionMapping As String = "QCL_DeleteModeSectionMapping"
    Public Const UpdateModeSectionMapping As String = "QCL_UpdateModeSectionMapping"

    'Added 2015.07.15  Sprint 29 User Story 26 
    'Amended 2015.07.31 Sprint 30 Reach Story 8
    Public Const SelectAllSiteGroups As String = "QCL_SiteGroupSelect"
    Public Const SelectPracticeSitesBySiteGroupId As String = "QCL_PracticeSiteSelect"
    Public Const SelectAllSiteGroupsAndPracticeSites As String = "QCL_SiteGroupsAndPracticeSitesSelect"
    Public Const UpdateSiteGroup As String = "QCL_SiteGroupUpdate"
    Public Const UpdatePracticeSite As String = "QCL_PracticeSiteUpdate"
    Public Const InsertSiteGroup As String = "QCL_SiteGroupInsert"
    Public Const InsertPracticeSite As String = "QCL_PracticeSiteInsert"
    Public Const DeleteSiteGroup As String = "QCL_SiteGroupDelete"
    Public Const DeletePracticeSite As String = "QCL_PracticeSiteDelete"
    Public Const PracticeSiteAllowDelete As String = "QCL_SiteAllowDelete"

    'Added 2015.09.15 Sprint 58 ATL-772
    Public Const SelectDRGUpdates As String = "LD_SelectDRGUpdates"
    Public Const RollbackDRGUpdates As String = "LD_UpdateDRG_Rollback"
    Public Const UpdateFileStateDRG As String = "LD_UpdateFileStateDRG"


#Region "Legacy Sampling Procedures"

    Public Const GetParameters As String = "QCL_SelectStoredProcedureParameters"
    Public Const ExecuteAddSampleSet As String = "sp_Samp_AddSampleSetV2"
    Public Const ExecutePopulateSampleUnitUniverse As String = "sp_Samp_Populate_Sampleunit_Universe"
    Public Const ExecutePreSample As String = "SP_Samp_PersistantAssignment"
    Public Const ExecuteInitializeBusinessRules As String = "sp_Samp_Initialze_BusRules"
    Public Const ExecuteEncounterTableExists As String = "sp_Samp_FindEncTable"
    Public Const ExecuteFetchSurveyValues As String = "sp_Samp_FetchSurveyValues"
    Public Const ExecuteFetchHouseholdingValues As String = "sp_Samp_FetchHouseholdingVals"
    Public Const ExecuteCreateTempTables As String = "sp_Samp_CreateTempTables"
    Public Const ExecuteDropTempTables As String = "sp_Samp_DropTempTables"
    Public Const ExecuteApplyIndex As String = "QCL_SampleSetIndexUniverse"
    Public Const ExecuteResurveyExclusion As String = "QCL_SampleSetResurveyExclusion"
    Public Const ExecuteNewbornRule As String = "QCL_SampleSetNewbornRule"
    Public Const ExecuteTOCLRule As String = "QCL_SampleSetTOCLRule"
    Public Const ExecuteDedupUniverseStatic As String = "sp_Samp_DeDupUnitUnivStaticV2"
    Public Const ExecuteDedupUniverseDynamic As String = "sp_Samp_DeDupUnitUnivDynV2"
    Public Const ExecuteCalcResponseRates As String = "sp_Samp_CalcResponseRates"
    Public Const ExecuteCalcTargets As String = "sp_Samp_CalcTargetsV2"
    Public Const ExecuteFetchSampleUnitTiers As String = "sp_Samp_FetchSampleUnitTiersV2"
    Public Const ExecuteCalcOutgo As String = "sp_Samp_CalcOutgoV2"
    Public Const ExecuteUpdatePeriod As String = "sp_Samp_UpdatePeriod"
    Public Const ExecuteUpdateSampleDataSet As String = "sp_Samp_UpdateSampleDataSet"
    Public Const ExecuteUpdateSamplePop As String = "sp_Samp_UpdateSamplePop"
    Public Const ExecuteUpdateSelectedSample As String = "sp_Samp_UpdateSelectedSample"
    Public Const ExecuteHouseholdingAdult As String = "sp_Samp_HouseholdingAdult"
    Public Const ExecuteHouseholdingMinor As String = "sp_Samp_HouseholdingMinor"
    Public Const ExecuteRollbackSample As String = "sp_Samp_RollbackSample"
    Public Const ExecuteValidateConfiguration As String = "sp_Samp_ValidateConfiguration"

#End Region


End Class
