---------------------------------------------------------------------------------------
--DL_SelectQUALPRO_PARAMS
---------------------------------------------------------------------------------------
IF OBJECT_ID(N'[dbo].[DL_SelectQUALPRO_PARAMS]') IS NOT NULL 
	DROP PROCEDURE [dbo].[DL_SelectQUALPRO_PARAMS]
GO
CREATE PROCEDURE [dbo].[DL_SelectQUALPRO_PARAMS]
@PARAM_ID INT
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT PARAM_ID, STRPARAM_NM, STRPARAM_TYPE, STRPARAM_GRP, STRPARAM_VALUE, NUMPARAM_VALUE, DATPARAM_VALUE, COMMENTS
FROM [dbo].QUALPRO_PARAMS
WHERE PARAM_ID = @PARAM_ID

SET NOCOUNT OFF
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
GO
---------------------------------------------------------------------------------------
--DL_SelectAllQUALPRO_PARAMSs
---------------------------------------------------------------------------------------
IF OBJECT_ID(N'[dbo].[DL_SelectAllQUALPRO_PARAMSs]') IS NOT NULL 
	DROP PROCEDURE [dbo].[DL_SelectAllQUALPRO_PARAMSs]
GO
CREATE PROCEDURE [dbo].[DL_SelectAllQUALPRO_PARAMSs]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT PARAM_ID, STRPARAM_NM, STRPARAM_TYPE, STRPARAM_GRP, STRPARAM_VALUE, NUMPARAM_VALUE, DATPARAM_VALUE, COMMENTS
FROM [dbo].QUALPRO_PARAMS

SET NOCOUNT OFF
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
GO
---------------------------------------------------------------------------------------
--DL_InsertQUALPRO_PARAMS
---------------------------------------------------------------------------------------
IF OBJECT_ID(N'[dbo].[DL_InsertQUALPRO_PARAMS]') IS NOT NULL 
	DROP PROCEDURE [dbo].[DL_InsertQUALPRO_PARAMS]
GO
CREATE PROCEDURE [dbo].[DL_InsertQUALPRO_PARAMS]
@STRPARAM_NM VARCHAR(20),
@STRPARAM_TYPE CHAR(1),
@STRPARAM_GRP VARCHAR(20),
@STRPARAM_VALUE VARCHAR(255),
@NUMPARAM_VALUE INT,
@DATPARAM_VALUE DATETIME,
@COMMENTS VARCHAR(255)
AS

SET NOCOUNT ON

INSERT INTO [dbo].QUALPRO_PARAMS (STRPARAM_NM, STRPARAM_TYPE, STRPARAM_GRP, STRPARAM_VALUE, NUMPARAM_VALUE, DATPARAM_VALUE, COMMENTS)
VALUES (@STRPARAM_NM, @STRPARAM_TYPE, @STRPARAM_GRP, @STRPARAM_VALUE, @NUMPARAM_VALUE, @DATPARAM_VALUE, @COMMENTS)

SELECT SCOPE_IDENTITY()

SET NOCOUNT OFF
GO
---------------------------------------------------------------------------------------
--DL_UpdateQUALPRO_PARAMS
---------------------------------------------------------------------------------------
IF OBJECT_ID(N'[dbo].[DL_UpdateQUALPRO_PARAMS]') IS NOT NULL 
	DROP PROCEDURE [dbo].[DL_UpdateQUALPRO_PARAMS]
GO
CREATE PROCEDURE [dbo].[DL_UpdateQUALPRO_PARAMS]
@PARAM_ID INT,
@STRPARAM_NM VARCHAR(20),
@STRPARAM_TYPE CHAR(1),
@STRPARAM_GRP VARCHAR(20),
@STRPARAM_VALUE VARCHAR(255),
@NUMPARAM_VALUE INT,
@DATPARAM_VALUE DATETIME,
@COMMENTS VARCHAR(255)
AS

SET NOCOUNT ON

UPDATE [dbo].QUALPRO_PARAMS SET
	STRPARAM_NM = @STRPARAM_NM,
	STRPARAM_TYPE = @STRPARAM_TYPE,
	STRPARAM_GRP = @STRPARAM_GRP,
	STRPARAM_VALUE = @STRPARAM_VALUE,
	NUMPARAM_VALUE = @NUMPARAM_VALUE,
	DATPARAM_VALUE = @DATPARAM_VALUE,
	COMMENTS = @COMMENTS
WHERE PARAM_ID = @PARAM_ID

SET NOCOUNT OFF
GO
---------------------------------------------------------------------------------------
--DL_DeleteQUALPRO_PARAMS
---------------------------------------------------------------------------------------
IF OBJECT_ID(N'[dbo].[DL_DeleteQUALPRO_PARAMS]') IS NOT NULL 
	DROP PROCEDURE [dbo].[DL_DeleteQUALPRO_PARAMS]
GO
CREATE PROCEDURE [dbo].[DL_DeleteQUALPRO_PARAMS]
@PARAM_ID INT
AS

SET NOCOUNT ON

DELETE [dbo].QUALPRO_PARAMS
WHERE PARAM_ID = @PARAM_ID

SET NOCOUNT OFF
GO

