CREATE NONCLUSTERED INDEX [IDX_CMMNTLINEPOS_GETBOXES] ON [dbo].[COMMENTLINEPOS]
(
	[QUESTIONFORM_ID] ASC,
	[INTPAGE_NUM] ASC,
	[SAMPLEUNIT_ID] ASC,
	[CMNTBOX_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]


