CREATE NONCLUSTERED INDEX [IDX_BUBBLE_CORE] ON [dbo].[BUBBLEPOS]
(
	[QUESTIONFORM_ID] ASC,
	[QSTNCORE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]


