Imports Microsoft.VisualStudio.TestTools.UnitTesting

'------------------------------------------------------------------------------
'<autogenerated>
'        This code was generated by Microsoft Visual Studio Team System 2005.
'
'        Changes to this file may cause incorrect behavior and will be lost if
'        the code is regenerated.
'</autogenerated>
'------------------------------------------------------------------------------
<System.Diagnostics.DebuggerStepThrough(), _
 System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")> _
Friend Class NRC_DataLoader_Library_UploadFileAccessor
    Inherits BaseAccessor

    Protected Shared m_privateType As Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType = New Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType(GetType(Global.NRC.DataLoader.Library.UploadFile))

    Friend Sub New(ByVal target As Global.NRC.DataLoader.Library.UploadFile)
        MyBase.New(target, m_privateType)
    End Sub

    Friend Property mInstanceGuid() As Global.System.Guid
        Get
            Dim ret As Global.System.Guid = CType(m_privateObject.GetFieldOrProperty("mInstanceGuid"), Global.System.Guid)
            Return ret
        End Get
        Set(ByVal value As Global.System.Guid)
            m_privateObject.SetFieldOrProperty("mInstanceGuid", value)
        End Set
    End Property

    Friend Property mId() As Integer
        Get
            Dim ret As Integer = CType(m_privateObject.GetFieldOrProperty("mId"), Integer)
            Return ret
        End Get
        Set(ByVal value As Integer)
            m_privateObject.SetFieldOrProperty("mId", value)
        End Set
    End Property

    Friend Property mOrigFileName() As String
        Get
            Dim ret As String = CType(m_privateObject.GetFieldOrProperty("mOrigFileName"), String)
            Return ret
        End Get
        Set(ByVal value As String)
            m_privateObject.SetFieldOrProperty("mOrigFileName", value)
        End Set
    End Property

    Friend Property mFileName() As String
        Get
            Dim ret As String = CType(m_privateObject.GetFieldOrProperty("mFileName"), String)
            Return ret
        End Get
        Set(ByVal value As String)
            m_privateObject.SetFieldOrProperty("mFileName", value)
        End Set
    End Property

    Friend Property mFileSize() As Integer
        Get
            Dim ret As Integer = CType(m_privateObject.GetFieldOrProperty("mFileSize"), Integer)
            Return ret
        End Get
        Set(ByVal value As Integer)
            m_privateObject.SetFieldOrProperty("mFileSize", value)
        End Set
    End Property

    Friend Property mUploadActionId() As System.Nullable(Of Integer)
        Get
            Dim ret As System.Nullable(Of Integer) = CType(m_privateObject.GetFieldOrProperty("mUploadActionId"), System.Nullable(Of Integer))
            Return ret
        End Get
        Set(ByVal value As System.Nullable(Of Integer))
            m_privateObject.SetFieldOrProperty("mUploadActionId", value)
        End Set
    End Property

    Friend Property mUploadAction() As Global.NRC.DataLoader.Library.UploadAction
        Get
            Dim ret As Global.NRC.DataLoader.Library.UploadAction = CType(m_privateObject.GetFieldOrProperty("mUploadAction"), Global.NRC.DataLoader.Library.UploadAction)
            Return ret
        End Get
        Set(ByVal value As Global.NRC.DataLoader.Library.UploadAction)
            m_privateObject.SetFieldOrProperty("mUploadAction", value)
        End Set
    End Property

    Friend Property mUserNotes() As String
        Get
            Dim ret As String = CType(m_privateObject.GetFieldOrProperty("mUserNotes"), String)
            Return ret
        End Get
        Set(ByVal value As String)
            m_privateObject.SetFieldOrProperty("mUserNotes", value)
        End Set
    End Property

    Friend Property mMemberId() As Integer
        Get
            Dim ret As Integer = CType(m_privateObject.GetFieldOrProperty("mMemberId"), Integer)
            Return ret
        End Get
        Set(ByVal value As Integer)
            m_privateObject.SetFieldOrProperty("mMemberId", value)
        End Set
    End Property

    Friend Property mGroupID() As Integer
        Get
            Dim ret As Integer = CType(m_privateObject.GetFieldOrProperty("mGroupID"), Integer)
            Return ret
        End Get
        Set(ByVal value As Integer)
            m_privateObject.SetFieldOrProperty("mGroupID", value)
        End Set
    End Property

    Friend Property mUploadFilePackages() As Global.NRC.DataLoader.Library.UploadFilePackageCollection
        Get
            Dim ret As Global.NRC.DataLoader.Library.UploadFilePackageCollection = CType(m_privateObject.GetFieldOrProperty("mUploadFilePackages"), Global.NRC.DataLoader.Library.UploadFilePackageCollection)
            Return ret
        End Get
        Set(ByVal value As Global.NRC.DataLoader.Library.UploadFilePackageCollection)
            m_privateObject.SetFieldOrProperty("mUploadFilePackages", value)
        End Set
    End Property

    Friend Property mUploadFileState() As Global.NRC.DataLoader.Library.UploadFileState
        Get
            Dim ret As Global.NRC.DataLoader.Library.UploadFileState = CType(m_privateObject.GetFieldOrProperty("mUploadFileState"), Global.NRC.DataLoader.Library.UploadFileState)
            Return ret
        End Get
        Set(ByVal value As Global.NRC.DataLoader.Library.UploadFileState)
            m_privateObject.SetFieldOrProperty("mUploadFileState", value)
        End Set
    End Property

    Friend Property mClientFileId() As Integer
        Get
            Dim ret As Integer = CType(m_privateObject.GetFieldOrProperty("mClientFileId"), Integer)
            Return ret
        End Get
        Set(ByVal value As Integer)
            m_privateObject.SetFieldOrProperty("mClientFileId", value)
        End Set
    End Property

    Friend Property mProjectManager() As Global.NRC.DataLoader.Library.ProjectManager
        Get
            Dim ret As Global.NRC.DataLoader.Library.ProjectManager = CType(m_privateObject.GetFieldOrProperty("mProjectManager"), Global.NRC.DataLoader.Library.ProjectManager)
            Return ret
        End Get
        Set(ByVal value As Global.NRC.DataLoader.Library.ProjectManager)
            m_privateObject.SetFieldOrProperty("mProjectManager", value)
        End Set
    End Property

    Friend Property mFileStatusSaved() As Boolean
        Get
            Dim ret As Boolean = CType(m_privateObject.GetFieldOrProperty("mFileStatusSaved"), Boolean)
            Return ret
        End Get
        Set(ByVal value As Boolean)
            m_privateObject.SetFieldOrProperty("mFileStatusSaved", value)
        End Set
    End Property

    Friend Property mFileNotificationHandled() As Boolean
        Get
            Dim ret As Boolean = CType(m_privateObject.GetFieldOrProperty("mFileNotificationHandled"), Boolean)
            Return ret
        End Get
        Set(ByVal value As Boolean)
            m_privateObject.SetFieldOrProperty("mFileNotificationHandled", value)
        End Set
    End Property

    Friend Shared Function CreatePrivate() As Global.NRC.DataLoader.Library.UploadFile
        Dim args(-1) As Object
        Dim priv_obj As Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject = New Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject(GetType(Global.NRC.DataLoader.Library.UploadFile), New System.Type(-1) {}, args)
        Return CType(priv_obj.Target, Global.NRC.DataLoader.Library.UploadFile)
    End Function

    Friend Function GetIdValue() As Object
        Dim args(-1) As Object
        Dim ret As Object = CType(m_privateObject.Invoke("GetIdValue", New System.Type(-1) {}, args), Object)
        Return ret
    End Function

    Friend Sub AddBusinessRules()
        Dim args(-1) As Object
        m_privateObject.Invoke("AddBusinessRules", New System.Type(-1) {}, args)
    End Sub

    Friend Sub CreateNew()
        Dim args(-1) As Object
        m_privateObject.Invoke("CreateNew", New System.Type(-1) {}, args)
    End Sub

    Friend Sub Insert()
        Dim args(-1) As Object
        m_privateObject.Invoke("Insert", New System.Type(-1) {}, args)
    End Sub

    Friend Sub Update()
        Dim args(-1) As Object
        m_privateObject.Invoke("Update", New System.Type(-1) {}, args)
    End Sub

    Friend Sub DeleteImmediate()
        Dim args(-1) As Object
        m_privateObject.Invoke("DeleteImmediate", New System.Type(-1) {}, args)
    End Sub
End Class
<System.Diagnostics.DebuggerStepThrough(), _
 System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")> _
Friend Class BaseAccessor

    Protected m_privateObject As Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject

    Protected Sub New(ByVal target As Object, ByVal type As Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType)
        MyBase.New()
        m_privateObject = New Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject(target, type)
    End Sub

    Protected Sub New(ByVal type As Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType)
        Me.New(Nothing, type)
    End Sub

    Friend Overridable ReadOnly Property Target() As Object
        Get
            Return m_privateObject.Target
        End Get
    End Property

    Public Overrides Function ToString() As String
        Return Me.Target.ToString
    End Function

    Public Overloads Overrides Function Equals(ByVal obj As Object) As Boolean
        If GetType(BaseAccessor).IsInstanceOfType(obj) Then
            obj = CType(obj, BaseAccessor).Target
        End If
        Return Me.Target.Equals(obj)
    End Function

    Public Overrides Function GetHashCode() As Integer
        Return Me.Target.GetHashCode
    End Function
End Class
