
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("e25255d2-6e58-4aef-a8a0-19a212ec25dc")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("OUH", "FK_ClientOrganization_Client", "Client", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(OUH.Client), "ClientOrganization", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(OUH.ClientOrganization), True)>
<Assembly: EdmRelationshipAttribute("OUH", "FK_ClientOrganization_Organization", "DimOrganization", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(OUH.Organization), "ClientOrganization", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(OUH.ClientOrganization), True)>
<Assembly: EdmRelationshipAttribute("OUH", "FK_MemberOrganizationUnit_DimOrganizationUnit", "DimOrganizationUnit", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(OUH.OrganizationUnit), "MemberOrganizationUnit", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(OUH.MemberOrganizationUnit), True)>
<Assembly: EdmRelationshipAttribute("OUH", "FK_DimOrganizationUnit_OrganizationID", "DimOrganization", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(OUH.Organization), "DimOrganizationUnit", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(OUH.OrganizationUnit))>
<Assembly: EdmRelationshipAttribute("OUH", "FK_DimOrganizationUnit_OrganizationCategoryID", "DimOrganizationCategory", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(OUH.OrganizationCategory), "DimOrganizationUnit", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(OUH.OrganizationUnit))>
<Assembly: EdmRelationshipAttribute("OUH", "FK_FFT_OrgUnitSampleUnit_OrganizationUnitID", "DimOrganizationUnit", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(OUH.OrganizationUnit), "FFT_OrgUnitSampleUnit", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(OUH.FFT_OrgUnitSampleUnit))>
<Assembly: EdmRelationshipAttribute("OUH", "FK_GroupOrganizationUnit_DimOrganizationUnit", "OrganizationUnit", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(OUH.OrganizationUnit), "GroupOrganizationUnit", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(OUH.GroupOrganizationUnit), True)>
<Assembly: EdmRelationshipAttribute("OUH", "FK_ClientOrganization_Organization1", "Organization", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(OUH.Organization), "ClientOrganization", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(OUH.ClientOrganization), True)>

#End Region

Namespace OUH

    #Region "Contexts"
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public Partial Class OUHModel
        Inherits ObjectContext
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Initializes a new OUHModel object using the connection string found in the 'OUHModel' section of the application configuration file.
        ''' </summary>
        Public Sub New()
            MyBase.New("name=OUHModel", "OUHModel")
            OnContextCreated()
        End Sub
    
        ''' <summary>
        ''' Initialize a new OUHModel object.
        ''' </summary>
        Public Sub New(ByVal connectionString As String)
            MyBase.New(connectionString, "OUHModel")
            OnContextCreated()
        End Sub
    
        ''' <summary>
        ''' Initialize a new OUHModel object.
        ''' </summary>
        Public Sub New(ByVal connection As EntityConnection)
            MyBase.New(connection, "OUHModel")
            OnContextCreated()
        End Sub
    
        #End Region
    
        #Region "Partial Methods"
    
        Partial Private Sub OnContextCreated()
        End Sub
    
        #End Region
    
        #Region "ObjectSet Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property Client() As ObjectSet(Of Client)
            Get
                If (_Client Is Nothing) Then
                    _Client = MyBase.CreateObjectSet(Of Client)("Client")
                End If
                Return _Client
            End Get
        End Property
    
        Private _Client As ObjectSet(Of Client)
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property ClientOrganization() As ObjectSet(Of ClientOrganization)
            Get
                If (_ClientOrganization Is Nothing) Then
                    _ClientOrganization = MyBase.CreateObjectSet(Of ClientOrganization)("ClientOrganization")
                End If
                Return _ClientOrganization
            End Get
        End Property
    
        Private _ClientOrganization As ObjectSet(Of ClientOrganization)
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property MemberOrganizationUnit() As ObjectSet(Of MemberOrganizationUnit)
            Get
                If (_MemberOrganizationUnit Is Nothing) Then
                    _MemberOrganizationUnit = MyBase.CreateObjectSet(Of MemberOrganizationUnit)("MemberOrganizationUnit")
                End If
                Return _MemberOrganizationUnit
            End Get
        End Property
    
        Private _MemberOrganizationUnit As ObjectSet(Of MemberOrganizationUnit)
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property OrganizationSet() As ObjectSet(Of Organization)
            Get
                If (_OrganizationSet Is Nothing) Then
                    _OrganizationSet = MyBase.CreateObjectSet(Of Organization)("OrganizationSet")
                End If
                Return _OrganizationSet
            End Get
        End Property
    
        Private _OrganizationSet As ObjectSet(Of Organization)
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property OrganizationCategorySet() As ObjectSet(Of OrganizationCategory)
            Get
                If (_OrganizationCategorySet Is Nothing) Then
                    _OrganizationCategorySet = MyBase.CreateObjectSet(Of OrganizationCategory)("OrganizationCategorySet")
                End If
                Return _OrganizationCategorySet
            End Get
        End Property
    
        Private _OrganizationCategorySet As ObjectSet(Of OrganizationCategory)
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property OrganizationUnitSet() As ObjectSet(Of OrganizationUnit)
            Get
                If (_OrganizationUnitSet Is Nothing) Then
                    _OrganizationUnitSet = MyBase.CreateObjectSet(Of OrganizationUnit)("OrganizationUnitSet")
                End If
                Return _OrganizationUnitSet
            End Get
        End Property
    
        Private _OrganizationUnitSet As ObjectSet(Of OrganizationUnit)
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property FFT_OrgUnitSampleUnit() As ObjectSet(Of FFT_OrgUnitSampleUnit)
            Get
                If (_FFT_OrgUnitSampleUnit Is Nothing) Then
                    _FFT_OrgUnitSampleUnit = MyBase.CreateObjectSet(Of FFT_OrgUnitSampleUnit)("FFT_OrgUnitSampleUnit")
                End If
                Return _FFT_OrgUnitSampleUnit
            End Get
        End Property
    
        Private _FFT_OrgUnitSampleUnit As ObjectSet(Of FFT_OrgUnitSampleUnit)
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property vw_OrganizationUnit() As ObjectSet(Of vw_OrganizationUnit)
            Get
                If (_vw_OrganizationUnit Is Nothing) Then
                    _vw_OrganizationUnit = MyBase.CreateObjectSet(Of vw_OrganizationUnit)("vw_OrganizationUnit")
                End If
                Return _vw_OrganizationUnit
            End Get
        End Property
    
        Private _vw_OrganizationUnit As ObjectSet(Of vw_OrganizationUnit)
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property GroupOrganizationUnit() As ObjectSet(Of GroupOrganizationUnit)
            Get
                If (_GroupOrganizationUnit Is Nothing) Then
                    _GroupOrganizationUnit = MyBase.CreateObjectSet(Of GroupOrganizationUnit)("GroupOrganizationUnit")
                End If
                Return _GroupOrganizationUnit
            End Get
        End Property
    
        Private _GroupOrganizationUnit As ObjectSet(Of GroupOrganizationUnit)

        #End Region

        #Region "AddTo Methods"
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the Client EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToClient(ByVal client As Client)
            MyBase.AddObject("Client", client)
        End Sub
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the ClientOrganization EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToClientOrganization(ByVal clientOrganization As ClientOrganization)
            MyBase.AddObject("ClientOrganization", clientOrganization)
        End Sub
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the MemberOrganizationUnit EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToMemberOrganizationUnit(ByVal memberOrganizationUnit As MemberOrganizationUnit)
            MyBase.AddObject("MemberOrganizationUnit", memberOrganizationUnit)
        End Sub
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the OrganizationSet EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToOrganizationSet(ByVal organization As Organization)
            MyBase.AddObject("OrganizationSet", organization)
        End Sub
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the OrganizationCategorySet EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToOrganizationCategorySet(ByVal organizationCategory As OrganizationCategory)
            MyBase.AddObject("OrganizationCategorySet", organizationCategory)
        End Sub
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the OrganizationUnitSet EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToOrganizationUnitSet(ByVal organizationUnit As OrganizationUnit)
            MyBase.AddObject("OrganizationUnitSet", organizationUnit)
        End Sub
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the FFT_OrgUnitSampleUnit EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToFFT_OrgUnitSampleUnit(ByVal fFT_OrgUnitSampleUnit As FFT_OrgUnitSampleUnit)
            MyBase.AddObject("FFT_OrgUnitSampleUnit", fFT_OrgUnitSampleUnit)
        End Sub
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the vw_OrganizationUnit EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddTovw_OrganizationUnit(ByVal vw_OrganizationUnit As vw_OrganizationUnit)
            MyBase.AddObject("vw_OrganizationUnit", vw_OrganizationUnit)
        End Sub
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the GroupOrganizationUnit EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToGroupOrganizationUnit(ByVal groupOrganizationUnit As GroupOrganizationUnit)
            MyBase.AddObject("GroupOrganizationUnit", groupOrganizationUnit)
        End Sub

        #End Region

    End Class

    #End Region

    #Region "Entities"
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="OUH", Name:="Client")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class Client
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new Client object.
        ''' </summary>
        ''' <param name="clientID">Initial value of the ClientID property.</param>
        ''' <param name="clientName">Initial value of the ClientName property.</param>
        ''' <param name="sourceClientID">Initial value of the SourceClientID property.</param>
        Public Shared Function CreateClient(clientID As Global.System.Int32, clientName As Global.System.String, sourceClientID As Global.System.String) As Client
            Dim client as Client = New Client
            client.ClientID = clientID
            client.ClientName = clientName
            client.SourceClientID = sourceClientID
            Return client
        End Function

        #End Region

        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property ClientID() As Global.System.Int32
            Get
                Return _ClientID
            End Get
            Set
                If (_ClientID <> Value) Then
                    OnClientIDChanging(value)
                    ReportPropertyChanging("ClientID")
                    _ClientID = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("ClientID")
                    OnClientIDChanged()
                End If
            End Set
        End Property
    
        Private _ClientID As Global.System.Int32
        Private Partial Sub OnClientIDChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnClientIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property ClientName() As Global.System.String
            Get
                Return _ClientName
            End Get
            Set
                OnClientNameChanging(value)
                ReportPropertyChanging("ClientName")
                _ClientName = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("ClientName")
                OnClientNameChanged()
            End Set
        End Property
    
        Private _ClientName As Global.System.String
        Private Partial Sub OnClientNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnClientNameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property SourceClientID() As Global.System.String
            Get
                Return _SourceClientID
            End Get
            Set
                OnSourceClientIDChanging(value)
                ReportPropertyChanging("SourceClientID")
                _SourceClientID = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("SourceClientID")
                OnSourceClientIDChanged()
            End Set
        End Property
    
        Private _SourceClientID As Global.System.String
        Private Partial Sub OnSourceClientIDChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnSourceClientIDChanged()
        End Sub

        #End Region

        #Region "Navigation Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("OUH", "FK_ClientOrganization_Client", "ClientOrganization")>
         Public Property ClientOrganization() As EntityCollection(Of ClientOrganization)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of ClientOrganization)("OUH.FK_ClientOrganization_Client", "ClientOrganization")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of ClientOrganization)("OUH.FK_ClientOrganization_Client", "ClientOrganization", value)
                End If
            End Set
        End Property

        #End Region

    End Class
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="OUH", Name:="ClientOrganization")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class ClientOrganization
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new ClientOrganization object.
        ''' </summary>
        ''' <param name="clientID">Initial value of the ClientID property.</param>
        ''' <param name="organizationID">Initial value of the OrganizationID property.</param>
        Public Shared Function CreateClientOrganization(clientID As Global.System.Int32, organizationID As Global.System.Int32) As ClientOrganization
            Dim clientOrganization as ClientOrganization = New ClientOrganization
            clientOrganization.ClientID = clientID
            clientOrganization.OrganizationID = organizationID
            Return clientOrganization
        End Function

        #End Region

        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property ClientID() As Global.System.Int32
            Get
                Return _ClientID
            End Get
            Set
                If (_ClientID <> Value) Then
                    OnClientIDChanging(value)
                    ReportPropertyChanging("ClientID")
                    _ClientID = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("ClientID")
                    OnClientIDChanged()
                End If
            End Set
        End Property
    
        Private _ClientID As Global.System.Int32
        Private Partial Sub OnClientIDChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnClientIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property OrganizationID() As Global.System.Int32
            Get
                Return _OrganizationID
            End Get
            Set
                If (_OrganizationID <> Value) Then
                    OnOrganizationIDChanging(value)
                    ReportPropertyChanging("OrganizationID")
                    _OrganizationID = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("OrganizationID")
                    OnOrganizationIDChanged()
                End If
            End Set
        End Property
    
        Private _OrganizationID As Global.System.Int32
        Private Partial Sub OnOrganizationIDChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnOrganizationIDChanged()
        End Sub

        #End Region

        #Region "Navigation Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("OUH", "FK_ClientOrganization_Client", "Client")>
        Public Property Client() As Client
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Client)("OUH.FK_ClientOrganization_Client", "Client").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Client)("OUH.FK_ClientOrganization_Client", "Client").Value = value
            End Set
        End Property
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property ClientReference() As EntityReference(Of Client)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Client)("OUH.FK_ClientOrganization_Client", "Client")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Client)("OUH.FK_ClientOrganization_Client", "Client", value)
                End If
            End Set
        End Property
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("OUH", "FK_ClientOrganization_Organization", "DimOrganization")>
        Public Property Organization() As Organization
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Organization)("OUH.FK_ClientOrganization_Organization", "DimOrganization").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Organization)("OUH.FK_ClientOrganization_Organization", "DimOrganization").Value = value
            End Set
        End Property
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property OrganizationReference() As EntityReference(Of Organization)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Organization)("OUH.FK_ClientOrganization_Organization", "DimOrganization")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Organization)("OUH.FK_ClientOrganization_Organization", "DimOrganization", value)
                End If
            End Set
        End Property
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("OUH", "FK_ClientOrganization_Organization1", "Organization")>
        Public Property DimOrganization() As Organization
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Organization)("OUH.FK_ClientOrganization_Organization1", "Organization").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Organization)("OUH.FK_ClientOrganization_Organization1", "Organization").Value = value
            End Set
        End Property
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property DimOrganizationReference() As EntityReference(Of Organization)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Organization)("OUH.FK_ClientOrganization_Organization1", "Organization")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Organization)("OUH.FK_ClientOrganization_Organization1", "Organization", value)
                End If
            End Set
        End Property

        #End Region

    End Class
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="OUH", Name:="FFT_OrgUnitSampleUnit")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class FFT_OrgUnitSampleUnit
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new FFT_OrgUnitSampleUnit object.
        ''' </summary>
        ''' <param name="orgUnitSampleUnitID">Initial value of the OrgUnitSampleUnitID property.</param>
        ''' <param name="sampleUnitID">Initial value of the SampleUnitID property.</param>
        ''' <param name="samplePopulationID">Initial value of the SamplePopulationID property.</param>
        Public Shared Function CreateFFT_OrgUnitSampleUnit(orgUnitSampleUnitID As Global.System.Int64, sampleUnitID As Global.System.Int32, samplePopulationID As Global.System.Int32) As FFT_OrgUnitSampleUnit
            Dim fFT_OrgUnitSampleUnit as FFT_OrgUnitSampleUnit = New FFT_OrgUnitSampleUnit
            fFT_OrgUnitSampleUnit.OrgUnitSampleUnitID = orgUnitSampleUnitID
            fFT_OrgUnitSampleUnit.SampleUnitID = sampleUnitID
            fFT_OrgUnitSampleUnit.SamplePopulationID = samplePopulationID
            Return fFT_OrgUnitSampleUnit
        End Function

        #End Region

        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property OrgUnitSampleUnitID() As Global.System.Int64
            Get
                Return _OrgUnitSampleUnitID
            End Get
            Set
                If (_OrgUnitSampleUnitID <> Value) Then
                    OnOrgUnitSampleUnitIDChanging(value)
                    ReportPropertyChanging("OrgUnitSampleUnitID")
                    _OrgUnitSampleUnitID = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("OrgUnitSampleUnitID")
                    OnOrgUnitSampleUnitIDChanged()
                End If
            End Set
        End Property
    
        Private _OrgUnitSampleUnitID As Global.System.Int64
        Private Partial Sub OnOrgUnitSampleUnitIDChanging(value As Global.System.Int64)
        End Sub
    
        Private Partial Sub OnOrgUnitSampleUnitIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property SampleUnitID() As Global.System.Int32
            Get
                Return _SampleUnitID
            End Get
            Set
                OnSampleUnitIDChanging(value)
                ReportPropertyChanging("SampleUnitID")
                _SampleUnitID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("SampleUnitID")
                OnSampleUnitIDChanged()
            End Set
        End Property
    
        Private _SampleUnitID As Global.System.Int32
        Private Partial Sub OnSampleUnitIDChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnSampleUnitIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property SamplePopulationID() As Global.System.Int32
            Get
                Return _SamplePopulationID
            End Get
            Set
                OnSamplePopulationIDChanging(value)
                ReportPropertyChanging("SamplePopulationID")
                _SamplePopulationID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("SamplePopulationID")
                OnSamplePopulationIDChanged()
            End Set
        End Property
    
        Private _SamplePopulationID As Global.System.Int32
        Private Partial Sub OnSamplePopulationIDChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnSamplePopulationIDChanged()
        End Sub

        #End Region

        #Region "Navigation Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("OUH", "FK_FFT_OrgUnitSampleUnit_OrganizationUnitID", "DimOrganizationUnit")>
        Public Property OrganizationUnit() As OrganizationUnit
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of OrganizationUnit)("OUH.FK_FFT_OrgUnitSampleUnit_OrganizationUnitID", "DimOrganizationUnit").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of OrganizationUnit)("OUH.FK_FFT_OrgUnitSampleUnit_OrganizationUnitID", "DimOrganizationUnit").Value = value
            End Set
        End Property
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property OrganizationUnitReference() As EntityReference(Of OrganizationUnit)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of OrganizationUnit)("OUH.FK_FFT_OrgUnitSampleUnit_OrganizationUnitID", "DimOrganizationUnit")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of OrganizationUnit)("OUH.FK_FFT_OrgUnitSampleUnit_OrganizationUnitID", "DimOrganizationUnit", value)
                End If
            End Set
        End Property

        #End Region

    End Class
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="OUH", Name:="GroupOrganizationUnit")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class GroupOrganizationUnit
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new GroupOrganizationUnit object.
        ''' </summary>
        ''' <param name="groupID">Initial value of the GroupID property.</param>
        ''' <param name="organizationUnitID">Initial value of the OrganizationUnitID property.</param>
        Public Shared Function CreateGroupOrganizationUnit(groupID As Global.System.Int32, organizationUnitID As Global.System.Int32) As GroupOrganizationUnit
            Dim groupOrganizationUnit as GroupOrganizationUnit = New GroupOrganizationUnit
            groupOrganizationUnit.GroupID = groupID
            groupOrganizationUnit.OrganizationUnitID = organizationUnitID
            Return groupOrganizationUnit
        End Function

        #End Region

        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property GroupID() As Global.System.Int32
            Get
                Return _GroupID
            End Get
            Set
                If (_GroupID <> Value) Then
                    OnGroupIDChanging(value)
                    ReportPropertyChanging("GroupID")
                    _GroupID = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("GroupID")
                    OnGroupIDChanged()
                End If
            End Set
        End Property
    
        Private _GroupID As Global.System.Int32
        Private Partial Sub OnGroupIDChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnGroupIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property OrganizationUnitID() As Global.System.Int32
            Get
                Return _OrganizationUnitID
            End Get
            Set
                If (_OrganizationUnitID <> Value) Then
                    OnOrganizationUnitIDChanging(value)
                    ReportPropertyChanging("OrganizationUnitID")
                    _OrganizationUnitID = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("OrganizationUnitID")
                    OnOrganizationUnitIDChanged()
                End If
            End Set
        End Property
    
        Private _OrganizationUnitID As Global.System.Int32
        Private Partial Sub OnOrganizationUnitIDChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnOrganizationUnitIDChanged()
        End Sub

        #End Region

        #Region "Navigation Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("OUH", "FK_GroupOrganizationUnit_DimOrganizationUnit", "OrganizationUnit")>
        Public Property OrganizationUnit() As OrganizationUnit
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of OrganizationUnit)("OUH.FK_GroupOrganizationUnit_DimOrganizationUnit", "OrganizationUnit").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of OrganizationUnit)("OUH.FK_GroupOrganizationUnit_DimOrganizationUnit", "OrganizationUnit").Value = value
            End Set
        End Property
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property OrganizationUnitReference() As EntityReference(Of OrganizationUnit)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of OrganizationUnit)("OUH.FK_GroupOrganizationUnit_DimOrganizationUnit", "OrganizationUnit")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of OrganizationUnit)("OUH.FK_GroupOrganizationUnit_DimOrganizationUnit", "OrganizationUnit", value)
                End If
            End Set
        End Property

        #End Region

    End Class
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="OUH", Name:="MemberOrganizationUnit")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class MemberOrganizationUnit
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new MemberOrganizationUnit object.
        ''' </summary>
        ''' <param name="member">Initial value of the Member property.</param>
        ''' <param name="organizationUnitID">Initial value of the OrganizationUnitID property.</param>
        ''' <param name="memberID">Initial value of the MemberID property.</param>
        Public Shared Function CreateMemberOrganizationUnit(member As Global.System.String, organizationUnitID As Global.System.Int32, memberID As Global.System.Int32) As MemberOrganizationUnit
            Dim memberOrganizationUnit as MemberOrganizationUnit = New MemberOrganizationUnit
            memberOrganizationUnit.Member = member
            memberOrganizationUnit.OrganizationUnitID = organizationUnitID
            memberOrganizationUnit.MemberID = memberID
            Return memberOrganizationUnit
        End Function

        #End Region

        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Member() As Global.System.String
            Get
                Return _Member
            End Get
            Set
                If (_Member <> Value) Then
                    OnMemberChanging(value)
                    ReportPropertyChanging("Member")
                    _Member = StructuralObject.SetValidValue(value, false)
                    ReportPropertyChanged("Member")
                    OnMemberChanged()
                End If
            End Set
        End Property
    
        Private _Member As Global.System.String
        Private Partial Sub OnMemberChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnMemberChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property OrganizationUnitID() As Global.System.Int32
            Get
                Return _OrganizationUnitID
            End Get
            Set
                If (_OrganizationUnitID <> Value) Then
                    OnOrganizationUnitIDChanging(value)
                    ReportPropertyChanging("OrganizationUnitID")
                    _OrganizationUnitID = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("OrganizationUnitID")
                    OnOrganizationUnitIDChanged()
                End If
            End Set
        End Property
    
        Private _OrganizationUnitID As Global.System.Int32
        Private Partial Sub OnOrganizationUnitIDChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnOrganizationUnitIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property MemberID() As Global.System.Int32
            Get
                Return _MemberID
            End Get
            Set
                OnMemberIDChanging(value)
                ReportPropertyChanging("MemberID")
                _MemberID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("MemberID")
                OnMemberIDChanged()
            End Set
        End Property
    
        Private _MemberID As Global.System.Int32
        Private Partial Sub OnMemberIDChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnMemberIDChanged()
        End Sub

        #End Region

        #Region "Navigation Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("OUH", "FK_MemberOrganizationUnit_DimOrganizationUnit", "DimOrganizationUnit")>
        Public Property OrganizationUnit() As OrganizationUnit
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of OrganizationUnit)("OUH.FK_MemberOrganizationUnit_DimOrganizationUnit", "DimOrganizationUnit").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of OrganizationUnit)("OUH.FK_MemberOrganizationUnit_DimOrganizationUnit", "DimOrganizationUnit").Value = value
            End Set
        End Property
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property OrganizationUnitReference() As EntityReference(Of OrganizationUnit)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of OrganizationUnit)("OUH.FK_MemberOrganizationUnit_DimOrganizationUnit", "DimOrganizationUnit")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of OrganizationUnit)("OUH.FK_MemberOrganizationUnit_DimOrganizationUnit", "DimOrganizationUnit", value)
                End If
            End Set
        End Property

        #End Region

    End Class
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="OUH", Name:="Organization")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class Organization
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new Organization object.
        ''' </summary>
        ''' <param name="organizationID">Initial value of the OrganizationID property.</param>
        ''' <param name="organizationName">Initial value of the OrganizationName property.</param>
        Public Shared Function CreateOrganization(organizationID As Global.System.Int32, organizationName As Global.System.String) As Organization
            Dim organization as Organization = New Organization
            organization.OrganizationID = organizationID
            organization.OrganizationName = organizationName
            Return organization
        End Function

        #End Region

        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property OrganizationID() As Global.System.Int32
            Get
                Return _OrganizationID
            End Get
            Set
                If (_OrganizationID <> Value) Then
                    OnOrganizationIDChanging(value)
                    ReportPropertyChanging("OrganizationID")
                    _OrganizationID = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("OrganizationID")
                    OnOrganizationIDChanged()
                End If
            End Set
        End Property
    
        Private _OrganizationID As Global.System.Int32
        Private Partial Sub OnOrganizationIDChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnOrganizationIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property OrganizationName() As Global.System.String
            Get
                Return _OrganizationName
            End Get
            Set
                OnOrganizationNameChanging(value)
                ReportPropertyChanging("OrganizationName")
                _OrganizationName = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("OrganizationName")
                OnOrganizationNameChanged()
            End Set
        End Property
    
        Private _OrganizationName As Global.System.String
        Private Partial Sub OnOrganizationNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnOrganizationNameChanged()
        End Sub

        #End Region

        #Region "Navigation Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("OUH", "FK_ClientOrganization_Organization", "ClientOrganization")>
         Public Property ClientOrganization() As EntityCollection(Of ClientOrganization)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of ClientOrganization)("OUH.FK_ClientOrganization_Organization", "ClientOrganization")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of ClientOrganization)("OUH.FK_ClientOrganization_Organization", "ClientOrganization", value)
                End If
            End Set
        End Property
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("OUH", "FK_DimOrganizationUnit_OrganizationID", "DimOrganizationUnit")>
         Public Property OrganizationUnit() As EntityCollection(Of OrganizationUnit)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of OrganizationUnit)("OUH.FK_DimOrganizationUnit_OrganizationID", "DimOrganizationUnit")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of OrganizationUnit)("OUH.FK_DimOrganizationUnit_OrganizationID", "DimOrganizationUnit", value)
                End If
            End Set
        End Property
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("OUH", "FK_ClientOrganization_Organization1", "ClientOrganization")>
         Public Property ClientOrganization_1() As EntityCollection(Of ClientOrganization)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of ClientOrganization)("OUH.FK_ClientOrganization_Organization1", "ClientOrganization")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of ClientOrganization)("OUH.FK_ClientOrganization_Organization1", "ClientOrganization", value)
                End If
            End Set
        End Property

        #End Region

    End Class
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="OUH", Name:="OrganizationCategory")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class OrganizationCategory
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new OrganizationCategory object.
        ''' </summary>
        ''' <param name="organizationCategoryID">Initial value of the OrganizationCategoryID property.</param>
        ''' <param name="categoryName">Initial value of the CategoryName property.</param>
        ''' <param name="internalOnly">Initial value of the InternalOnly property.</param>
        Public Shared Function CreateOrganizationCategory(organizationCategoryID As Global.System.Int32, categoryName As Global.System.String, internalOnly As Global.System.Boolean) As OrganizationCategory
            Dim organizationCategory as OrganizationCategory = New OrganizationCategory
            organizationCategory.OrganizationCategoryID = organizationCategoryID
            organizationCategory.CategoryName = categoryName
            organizationCategory.InternalOnly = internalOnly
            Return organizationCategory
        End Function

        #End Region

        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property OrganizationCategoryID() As Global.System.Int32
            Get
                Return _OrganizationCategoryID
            End Get
            Set
                If (_OrganizationCategoryID <> Value) Then
                    OnOrganizationCategoryIDChanging(value)
                    ReportPropertyChanging("OrganizationCategoryID")
                    _OrganizationCategoryID = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("OrganizationCategoryID")
                    OnOrganizationCategoryIDChanged()
                End If
            End Set
        End Property
    
        Private _OrganizationCategoryID As Global.System.Int32
        Private Partial Sub OnOrganizationCategoryIDChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnOrganizationCategoryIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property CategoryName() As Global.System.String
            Get
                Return _CategoryName
            End Get
            Set
                OnCategoryNameChanging(value)
                ReportPropertyChanging("CategoryName")
                _CategoryName = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("CategoryName")
                OnCategoryNameChanged()
            End Set
        End Property
    
        Private _CategoryName As Global.System.String
        Private Partial Sub OnCategoryNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnCategoryNameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property InternalOnly() As Global.System.Boolean
            Get
                Return _InternalOnly
            End Get
            Set
                OnInternalOnlyChanging(value)
                ReportPropertyChanging("InternalOnly")
                _InternalOnly = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("InternalOnly")
                OnInternalOnlyChanged()
            End Set
        End Property
    
        Private _InternalOnly As Global.System.Boolean
        Private Partial Sub OnInternalOnlyChanging(value As Global.System.Boolean)
        End Sub
    
        Private Partial Sub OnInternalOnlyChanged()
        End Sub

        #End Region

        #Region "Navigation Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("OUH", "FK_DimOrganizationUnit_OrganizationCategoryID", "DimOrganizationUnit")>
         Public Property OrganizationUnit() As EntityCollection(Of OrganizationUnit)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of OrganizationUnit)("OUH.FK_DimOrganizationUnit_OrganizationCategoryID", "DimOrganizationUnit")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of OrganizationUnit)("OUH.FK_DimOrganizationUnit_OrganizationCategoryID", "DimOrganizationUnit", value)
                End If
            End Set
        End Property

        #End Region

    End Class
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="OUH", Name:="OrganizationUnit")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class OrganizationUnit
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new OrganizationUnit object.
        ''' </summary>
        ''' <param name="organizationUnitID">Initial value of the OrganizationUnitID property.</param>
        ''' <param name="organizationCategoryName">Initial value of the OrganizationCategoryName property.</param>
        ''' <param name="organizationName">Initial value of the OrganizationName property.</param>
        ''' <param name="levelName">Initial value of the LevelName property.</param>
        ''' <param name="orgUnitName">Initial value of the OrgUnitName property.</param>
        ''' <param name="level01OrgUnitID">Initial value of the Level01OrgUnitID property.</param>
        ''' <param name="level01OrgUnitName">Initial value of the Level01OrgUnitName property.</param>
        ''' <param name="levelNum">Initial value of the LevelNum property.</param>
        ''' <param name="isLeaf">Initial value of the IsLeaf property.</param>
        Public Shared Function CreateOrganizationUnit(organizationUnitID As Global.System.Int32, organizationCategoryName As Global.System.String, organizationName As Global.System.String, levelName As Global.System.String, orgUnitName As Global.System.String, level01OrgUnitID As Global.System.Int32, level01OrgUnitName As Global.System.String, levelNum As Global.System.Int32, isLeaf As Global.System.Boolean) As OrganizationUnit
            Dim organizationUnit as OrganizationUnit = New OrganizationUnit
            organizationUnit.OrganizationUnitID = organizationUnitID
            organizationUnit.OrganizationCategoryName = organizationCategoryName
            organizationUnit.OrganizationName = organizationName
            organizationUnit.LevelName = levelName
            organizationUnit.OrgUnitName = orgUnitName
            organizationUnit.Level01OrgUnitID = level01OrgUnitID
            organizationUnit.Level01OrgUnitName = level01OrgUnitName
            organizationUnit.LevelNum = levelNum
            organizationUnit.IsLeaf = isLeaf
            Return organizationUnit
        End Function

        #End Region

        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property OrganizationUnitID() As Global.System.Int32
            Get
                Return _OrganizationUnitID
            End Get
            Set
                If (_OrganizationUnitID <> Value) Then
                    OnOrganizationUnitIDChanging(value)
                    ReportPropertyChanging("OrganizationUnitID")
                    _OrganizationUnitID = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("OrganizationUnitID")
                    OnOrganizationUnitIDChanged()
                End If
            End Set
        End Property
    
        Private _OrganizationUnitID As Global.System.Int32
        Private Partial Sub OnOrganizationUnitIDChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnOrganizationUnitIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property OrganizationCategoryName() As Global.System.String
            Get
                Return _OrganizationCategoryName
            End Get
            Set
                OnOrganizationCategoryNameChanging(value)
                ReportPropertyChanging("OrganizationCategoryName")
                _OrganizationCategoryName = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("OrganizationCategoryName")
                OnOrganizationCategoryNameChanged()
            End Set
        End Property
    
        Private _OrganizationCategoryName As Global.System.String
        Private Partial Sub OnOrganizationCategoryNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnOrganizationCategoryNameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property OrganizationName() As Global.System.String
            Get
                Return _OrganizationName
            End Get
            Set
                OnOrganizationNameChanging(value)
                ReportPropertyChanging("OrganizationName")
                _OrganizationName = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("OrganizationName")
                OnOrganizationNameChanged()
            End Set
        End Property
    
        Private _OrganizationName As Global.System.String
        Private Partial Sub OnOrganizationNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnOrganizationNameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property LevelName() As Global.System.String
            Get
                Return _LevelName
            End Get
            Set
                OnLevelNameChanging(value)
                ReportPropertyChanging("LevelName")
                _LevelName = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("LevelName")
                OnLevelNameChanged()
            End Set
        End Property
    
        Private _LevelName As Global.System.String
        Private Partial Sub OnLevelNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnLevelNameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property OrgUnitName() As Global.System.String
            Get
                Return _OrgUnitName
            End Get
            Set
                OnOrgUnitNameChanging(value)
                ReportPropertyChanging("OrgUnitName")
                _OrgUnitName = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("OrgUnitName")
                OnOrgUnitNameChanged()
            End Set
        End Property
    
        Private _OrgUnitName As Global.System.String
        Private Partial Sub OnOrgUnitNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnOrgUnitNameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Level01OrgUnitID() As Global.System.Int32
            Get
                Return _Level01OrgUnitID
            End Get
            Set
                OnLevel01OrgUnitIDChanging(value)
                ReportPropertyChanging("Level01OrgUnitID")
                _Level01OrgUnitID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Level01OrgUnitID")
                OnLevel01OrgUnitIDChanged()
            End Set
        End Property
    
        Private _Level01OrgUnitID As Global.System.Int32
        Private Partial Sub OnLevel01OrgUnitIDChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnLevel01OrgUnitIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Level01OrgUnitName() As Global.System.String
            Get
                Return _Level01OrgUnitName
            End Get
            Set
                OnLevel01OrgUnitNameChanging(value)
                ReportPropertyChanging("Level01OrgUnitName")
                _Level01OrgUnitName = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("Level01OrgUnitName")
                OnLevel01OrgUnitNameChanged()
            End Set
        End Property
    
        Private _Level01OrgUnitName As Global.System.String
        Private Partial Sub OnLevel01OrgUnitNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnLevel01OrgUnitNameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Level02OrgUnitID() As Nullable(Of Global.System.Int32)
            Get
                Return _Level02OrgUnitID
            End Get
            Set
                OnLevel02OrgUnitIDChanging(value)
                ReportPropertyChanging("Level02OrgUnitID")
                _Level02OrgUnitID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Level02OrgUnitID")
                OnLevel02OrgUnitIDChanged()
            End Set
        End Property
    
        Private _Level02OrgUnitID As Nullable(Of Global.System.Int32)
        Private Partial Sub OnLevel02OrgUnitIDChanging(value As Nullable(Of Global.System.Int32))
        End Sub
    
        Private Partial Sub OnLevel02OrgUnitIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Level02OrgUnitName() As Global.System.String
            Get
                Return _Level02OrgUnitName
            End Get
            Set
                OnLevel02OrgUnitNameChanging(value)
                ReportPropertyChanging("Level02OrgUnitName")
                _Level02OrgUnitName = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("Level02OrgUnitName")
                OnLevel02OrgUnitNameChanged()
            End Set
        End Property
    
        Private _Level02OrgUnitName As Global.System.String
        Private Partial Sub OnLevel02OrgUnitNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnLevel02OrgUnitNameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Level03OrgUnitID() As Nullable(Of Global.System.Int32)
            Get
                Return _Level03OrgUnitID
            End Get
            Set
                OnLevel03OrgUnitIDChanging(value)
                ReportPropertyChanging("Level03OrgUnitID")
                _Level03OrgUnitID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Level03OrgUnitID")
                OnLevel03OrgUnitIDChanged()
            End Set
        End Property
    
        Private _Level03OrgUnitID As Nullable(Of Global.System.Int32)
        Private Partial Sub OnLevel03OrgUnitIDChanging(value As Nullable(Of Global.System.Int32))
        End Sub
    
        Private Partial Sub OnLevel03OrgUnitIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Level03OrgUnitName() As Global.System.String
            Get
                Return _Level03OrgUnitName
            End Get
            Set
                OnLevel03OrgUnitNameChanging(value)
                ReportPropertyChanging("Level03OrgUnitName")
                _Level03OrgUnitName = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("Level03OrgUnitName")
                OnLevel03OrgUnitNameChanged()
            End Set
        End Property
    
        Private _Level03OrgUnitName As Global.System.String
        Private Partial Sub OnLevel03OrgUnitNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnLevel03OrgUnitNameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Level04OrgUnitID() As Nullable(Of Global.System.Int32)
            Get
                Return _Level04OrgUnitID
            End Get
            Set
                OnLevel04OrgUnitIDChanging(value)
                ReportPropertyChanging("Level04OrgUnitID")
                _Level04OrgUnitID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Level04OrgUnitID")
                OnLevel04OrgUnitIDChanged()
            End Set
        End Property
    
        Private _Level04OrgUnitID As Nullable(Of Global.System.Int32)
        Private Partial Sub OnLevel04OrgUnitIDChanging(value As Nullable(Of Global.System.Int32))
        End Sub
    
        Private Partial Sub OnLevel04OrgUnitIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Level04OrgUnitName() As Global.System.String
            Get
                Return _Level04OrgUnitName
            End Get
            Set
                OnLevel04OrgUnitNameChanging(value)
                ReportPropertyChanging("Level04OrgUnitName")
                _Level04OrgUnitName = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("Level04OrgUnitName")
                OnLevel04OrgUnitNameChanged()
            End Set
        End Property
    
        Private _Level04OrgUnitName As Global.System.String
        Private Partial Sub OnLevel04OrgUnitNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnLevel04OrgUnitNameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Level05OrgUnitID() As Nullable(Of Global.System.Int32)
            Get
                Return _Level05OrgUnitID
            End Get
            Set
                OnLevel05OrgUnitIDChanging(value)
                ReportPropertyChanging("Level05OrgUnitID")
                _Level05OrgUnitID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Level05OrgUnitID")
                OnLevel05OrgUnitIDChanged()
            End Set
        End Property
    
        Private _Level05OrgUnitID As Nullable(Of Global.System.Int32)
        Private Partial Sub OnLevel05OrgUnitIDChanging(value As Nullable(Of Global.System.Int32))
        End Sub
    
        Private Partial Sub OnLevel05OrgUnitIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Level05OrgUnitName() As Global.System.String
            Get
                Return _Level05OrgUnitName
            End Get
            Set
                OnLevel05OrgUnitNameChanging(value)
                ReportPropertyChanging("Level05OrgUnitName")
                _Level05OrgUnitName = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("Level05OrgUnitName")
                OnLevel05OrgUnitNameChanged()
            End Set
        End Property
    
        Private _Level05OrgUnitName As Global.System.String
        Private Partial Sub OnLevel05OrgUnitNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnLevel05OrgUnitNameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Level06OrgUnitID() As Nullable(Of Global.System.Int32)
            Get
                Return _Level06OrgUnitID
            End Get
            Set
                OnLevel06OrgUnitIDChanging(value)
                ReportPropertyChanging("Level06OrgUnitID")
                _Level06OrgUnitID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Level06OrgUnitID")
                OnLevel06OrgUnitIDChanged()
            End Set
        End Property
    
        Private _Level06OrgUnitID As Nullable(Of Global.System.Int32)
        Private Partial Sub OnLevel06OrgUnitIDChanging(value As Nullable(Of Global.System.Int32))
        End Sub
    
        Private Partial Sub OnLevel06OrgUnitIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Level06OrgUnitName() As Global.System.String
            Get
                Return _Level06OrgUnitName
            End Get
            Set
                OnLevel06OrgUnitNameChanging(value)
                ReportPropertyChanging("Level06OrgUnitName")
                _Level06OrgUnitName = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("Level06OrgUnitName")
                OnLevel06OrgUnitNameChanged()
            End Set
        End Property
    
        Private _Level06OrgUnitName As Global.System.String
        Private Partial Sub OnLevel06OrgUnitNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnLevel06OrgUnitNameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Level07OrgUnitID() As Nullable(Of Global.System.Int32)
            Get
                Return _Level07OrgUnitID
            End Get
            Set
                OnLevel07OrgUnitIDChanging(value)
                ReportPropertyChanging("Level07OrgUnitID")
                _Level07OrgUnitID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Level07OrgUnitID")
                OnLevel07OrgUnitIDChanged()
            End Set
        End Property
    
        Private _Level07OrgUnitID As Nullable(Of Global.System.Int32)
        Private Partial Sub OnLevel07OrgUnitIDChanging(value As Nullable(Of Global.System.Int32))
        End Sub
    
        Private Partial Sub OnLevel07OrgUnitIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Level07OrgUnitName() As Global.System.String
            Get
                Return _Level07OrgUnitName
            End Get
            Set
                OnLevel07OrgUnitNameChanging(value)
                ReportPropertyChanging("Level07OrgUnitName")
                _Level07OrgUnitName = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("Level07OrgUnitName")
                OnLevel07OrgUnitNameChanged()
            End Set
        End Property
    
        Private _Level07OrgUnitName As Global.System.String
        Private Partial Sub OnLevel07OrgUnitNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnLevel07OrgUnitNameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Level08OrgUnitID() As Nullable(Of Global.System.Int32)
            Get
                Return _Level08OrgUnitID
            End Get
            Set
                OnLevel08OrgUnitIDChanging(value)
                ReportPropertyChanging("Level08OrgUnitID")
                _Level08OrgUnitID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Level08OrgUnitID")
                OnLevel08OrgUnitIDChanged()
            End Set
        End Property
    
        Private _Level08OrgUnitID As Nullable(Of Global.System.Int32)
        Private Partial Sub OnLevel08OrgUnitIDChanging(value As Nullable(Of Global.System.Int32))
        End Sub
    
        Private Partial Sub OnLevel08OrgUnitIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Level08OrgUnitName() As Global.System.String
            Get
                Return _Level08OrgUnitName
            End Get
            Set
                OnLevel08OrgUnitNameChanging(value)
                ReportPropertyChanging("Level08OrgUnitName")
                _Level08OrgUnitName = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("Level08OrgUnitName")
                OnLevel08OrgUnitNameChanged()
            End Set
        End Property
    
        Private _Level08OrgUnitName As Global.System.String
        Private Partial Sub OnLevel08OrgUnitNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnLevel08OrgUnitNameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Level09OrgUnitID() As Nullable(Of Global.System.Int32)
            Get
                Return _Level09OrgUnitID
            End Get
            Set
                OnLevel09OrgUnitIDChanging(value)
                ReportPropertyChanging("Level09OrgUnitID")
                _Level09OrgUnitID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Level09OrgUnitID")
                OnLevel09OrgUnitIDChanged()
            End Set
        End Property
    
        Private _Level09OrgUnitID As Nullable(Of Global.System.Int32)
        Private Partial Sub OnLevel09OrgUnitIDChanging(value As Nullable(Of Global.System.Int32))
        End Sub
    
        Private Partial Sub OnLevel09OrgUnitIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Level09OrgUnitName() As Global.System.String
            Get
                Return _Level09OrgUnitName
            End Get
            Set
                OnLevel09OrgUnitNameChanging(value)
                ReportPropertyChanging("Level09OrgUnitName")
                _Level09OrgUnitName = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("Level09OrgUnitName")
                OnLevel09OrgUnitNameChanged()
            End Set
        End Property
    
        Private _Level09OrgUnitName As Global.System.String
        Private Partial Sub OnLevel09OrgUnitNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnLevel09OrgUnitNameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Level10OrgUnitID() As Nullable(Of Global.System.Int32)
            Get
                Return _Level10OrgUnitID
            End Get
            Set
                OnLevel10OrgUnitIDChanging(value)
                ReportPropertyChanging("Level10OrgUnitID")
                _Level10OrgUnitID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Level10OrgUnitID")
                OnLevel10OrgUnitIDChanged()
            End Set
        End Property
    
        Private _Level10OrgUnitID As Nullable(Of Global.System.Int32)
        Private Partial Sub OnLevel10OrgUnitIDChanging(value As Nullable(Of Global.System.Int32))
        End Sub
    
        Private Partial Sub OnLevel10OrgUnitIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Level10OrgUnitName() As Global.System.String
            Get
                Return _Level10OrgUnitName
            End Get
            Set
                OnLevel10OrgUnitNameChanging(value)
                ReportPropertyChanging("Level10OrgUnitName")
                _Level10OrgUnitName = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("Level10OrgUnitName")
                OnLevel10OrgUnitNameChanged()
            End Set
        End Property
    
        Private _Level10OrgUnitName As Global.System.String
        Private Partial Sub OnLevel10OrgUnitNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnLevel10OrgUnitNameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property LevelNum() As Global.System.Int32
            Get
                Return _LevelNum
            End Get
            Set
                OnLevelNumChanging(value)
                ReportPropertyChanging("LevelNum")
                _LevelNum = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("LevelNum")
                OnLevelNumChanged()
            End Set
        End Property
    
        Private _LevelNum As Global.System.Int32
        Private Partial Sub OnLevelNumChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnLevelNumChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property IsLeaf() As Global.System.Boolean
            Get
                Return _IsLeaf
            End Get
            Set
                OnIsLeafChanging(value)
                ReportPropertyChanging("IsLeaf")
                _IsLeaf = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("IsLeaf")
                OnIsLeafChanged()
            End Set
        End Property
    
        Private _IsLeaf As Global.System.Boolean
        Private Partial Sub OnIsLeafChanging(value As Global.System.Boolean)
        End Sub
    
        Private Partial Sub OnIsLeafChanged()
        End Sub

        #End Region

        #Region "Navigation Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("OUH", "FK_MemberOrganizationUnit_DimOrganizationUnit", "MemberOrganizationUnit")>
         Public Property MemberOrganizationUnit() As EntityCollection(Of MemberOrganizationUnit)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of MemberOrganizationUnit)("OUH.FK_MemberOrganizationUnit_DimOrganizationUnit", "MemberOrganizationUnit")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of MemberOrganizationUnit)("OUH.FK_MemberOrganizationUnit_DimOrganizationUnit", "MemberOrganizationUnit", value)
                End If
            End Set
        End Property
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("OUH", "FK_DimOrganizationUnit_OrganizationID", "DimOrganization")>
        Public Property Organization() As Organization
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Organization)("OUH.FK_DimOrganizationUnit_OrganizationID", "DimOrganization").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Organization)("OUH.FK_DimOrganizationUnit_OrganizationID", "DimOrganization").Value = value
            End Set
        End Property
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property OrganizationReference() As EntityReference(Of Organization)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Organization)("OUH.FK_DimOrganizationUnit_OrganizationID", "DimOrganization")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Organization)("OUH.FK_DimOrganizationUnit_OrganizationID", "DimOrganization", value)
                End If
            End Set
        End Property
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("OUH", "FK_DimOrganizationUnit_OrganizationCategoryID", "DimOrganizationCategory")>
        Public Property OrganizationCategory() As OrganizationCategory
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of OrganizationCategory)("OUH.FK_DimOrganizationUnit_OrganizationCategoryID", "DimOrganizationCategory").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of OrganizationCategory)("OUH.FK_DimOrganizationUnit_OrganizationCategoryID", "DimOrganizationCategory").Value = value
            End Set
        End Property
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property OrganizationCategoryReference() As EntityReference(Of OrganizationCategory)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of OrganizationCategory)("OUH.FK_DimOrganizationUnit_OrganizationCategoryID", "DimOrganizationCategory")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of OrganizationCategory)("OUH.FK_DimOrganizationUnit_OrganizationCategoryID", "DimOrganizationCategory", value)
                End If
            End Set
        End Property
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("OUH", "FK_FFT_OrgUnitSampleUnit_OrganizationUnitID", "FFT_OrgUnitSampleUnit")>
         Public Property FFT_OrgUnitSampleUnit() As EntityCollection(Of FFT_OrgUnitSampleUnit)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of FFT_OrgUnitSampleUnit)("OUH.FK_FFT_OrgUnitSampleUnit_OrganizationUnitID", "FFT_OrgUnitSampleUnit")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of FFT_OrgUnitSampleUnit)("OUH.FK_FFT_OrgUnitSampleUnit_OrganizationUnitID", "FFT_OrgUnitSampleUnit", value)
                End If
            End Set
        End Property
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("OUH", "FK_GroupOrganizationUnit_DimOrganizationUnit", "GroupOrganizationUnit")>
         Public Property GroupOrganizationUnit() As EntityCollection(Of GroupOrganizationUnit)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of GroupOrganizationUnit)("OUH.FK_GroupOrganizationUnit_DimOrganizationUnit", "GroupOrganizationUnit")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of GroupOrganizationUnit)("OUH.FK_GroupOrganizationUnit_DimOrganizationUnit", "GroupOrganizationUnit", value)
                End If
            End Set
        End Property

        #End Region

    End Class
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="OUH", Name:="vw_OrganizationUnit")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class vw_OrganizationUnit
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new vw_OrganizationUnit object.
        ''' </summary>
        ''' <param name="organizationUnitID">Initial value of the OrganizationUnitID property.</param>
        ''' <param name="orgUnitName">Initial value of the OrgUnitName property.</param>
        ''' <param name="organizationID">Initial value of the OrganizationID property.</param>
        ''' <param name="levelNum">Initial value of the LevelNum property.</param>
        ''' <param name="levelName">Initial value of the LevelName property.</param>
        Public Shared Function Createvw_OrganizationUnit(organizationUnitID As Global.System.Int32, orgUnitName As Global.System.String, organizationID As Global.System.Int32, levelNum As Global.System.Int32, levelName As Global.System.String) As vw_OrganizationUnit
            Dim vw_OrganizationUnit as vw_OrganizationUnit = New vw_OrganizationUnit
            vw_OrganizationUnit.OrganizationUnitID = organizationUnitID
            vw_OrganizationUnit.OrgUnitName = orgUnitName
            vw_OrganizationUnit.OrganizationID = organizationID
            vw_OrganizationUnit.LevelNum = levelNum
            vw_OrganizationUnit.LevelName = levelName
            Return vw_OrganizationUnit
        End Function

        #End Region

        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property OrganizationUnitID() As Global.System.Int32
            Get
                Return _OrganizationUnitID
            End Get
            Set
                If (_OrganizationUnitID <> Value) Then
                    OnOrganizationUnitIDChanging(value)
                    ReportPropertyChanging("OrganizationUnitID")
                    _OrganizationUnitID = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("OrganizationUnitID")
                    OnOrganizationUnitIDChanged()
                End If
            End Set
        End Property
    
        Private _OrganizationUnitID As Global.System.Int32
        Private Partial Sub OnOrganizationUnitIDChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnOrganizationUnitIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property OrgUnitName() As Global.System.String
            Get
                Return _OrgUnitName
            End Get
            Set
                If (_OrgUnitName <> Value) Then
                    OnOrgUnitNameChanging(value)
                    ReportPropertyChanging("OrgUnitName")
                    _OrgUnitName = StructuralObject.SetValidValue(value, false)
                    ReportPropertyChanged("OrgUnitName")
                    OnOrgUnitNameChanged()
                End If
            End Set
        End Property
    
        Private _OrgUnitName As Global.System.String
        Private Partial Sub OnOrgUnitNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnOrgUnitNameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property OrganizationID() As Global.System.Int32
            Get
                Return _OrganizationID
            End Get
            Set
                If (_OrganizationID <> Value) Then
                    OnOrganizationIDChanging(value)
                    ReportPropertyChanging("OrganizationID")
                    _OrganizationID = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("OrganizationID")
                    OnOrganizationIDChanged()
                End If
            End Set
        End Property
    
        Private _OrganizationID As Global.System.Int32
        Private Partial Sub OnOrganizationIDChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnOrganizationIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property ParentOrgUnitID() As Nullable(Of Global.System.Int32)
            Get
                Return _ParentOrgUnitID
            End Get
            Set
                OnParentOrgUnitIDChanging(value)
                ReportPropertyChanging("ParentOrgUnitID")
                _ParentOrgUnitID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("ParentOrgUnitID")
                OnParentOrgUnitIDChanged()
            End Set
        End Property
    
        Private _ParentOrgUnitID As Nullable(Of Global.System.Int32)
        Private Partial Sub OnParentOrgUnitIDChanging(value As Nullable(Of Global.System.Int32))
        End Sub
    
        Private Partial Sub OnParentOrgUnitIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property LevelNum() As Global.System.Int32
            Get
                Return _LevelNum
            End Get
            Set
                If (_LevelNum <> Value) Then
                    OnLevelNumChanging(value)
                    ReportPropertyChanging("LevelNum")
                    _LevelNum = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("LevelNum")
                    OnLevelNumChanged()
                End If
            End Set
        End Property
    
        Private _LevelNum As Global.System.Int32
        Private Partial Sub OnLevelNumChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnLevelNumChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property LevelName() As Global.System.String
            Get
                Return _LevelName
            End Get
            Set
                If (_LevelName <> Value) Then
                    OnLevelNameChanging(value)
                    ReportPropertyChanging("LevelName")
                    _LevelName = StructuralObject.SetValidValue(value, false)
                    ReportPropertyChanged("LevelName")
                    OnLevelNameChanged()
                End If
            End Set
        End Property
    
        Private _LevelName As Global.System.String
        Private Partial Sub OnLevelNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnLevelNameChanged()
        End Sub

        #End Region

    End Class

    #End Region

    
End Namespace
