CREATE TABLE [dbo].[BackgroundFieldMapping](
	[FieldName] [varchar](256) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[MapToField] [varchar](256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MapToExpression] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_BackgroundFieldMapping] PRIMARY KEY CLUSTERED 
(
	[FieldName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]


