'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class UserControls_FooterControlCss
    Protected WithEvents PrivacyLink As System.Web.UI.WebControls.HyperLink
    Protected WithEvents CopyrightLabel As System.Web.UI.WebControls.Label
    Protected WithEvents DateTimeLabel As System.Web.UI.WebControls.Label
    Protected WithEvents VersionLabel As System.Web.UI.WebControls.Label
End Class
