ALTER TABLE dbo.TransformTarget ADD CONSTRAINT [PK_TransformTarget] PRIMARY KEY CLUSTERED
(
		TransformTargetId ASC
) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO