ALTER TABLE dbo.Transform ADD CONSTRAINT [PK_Transform] PRIMARY KEY CLUSTERED
(
		TransformId ASC
) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
go