ALTER TABLE dbo.TransformImports ADD CONSTRAINT [PK_TransformImports] PRIMARY KEY CLUSTERED
(
	TransformId ASC,
	TransformLibraryId ASC
) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO