if not "%1"=="" xcopy \\%1\Logs\*.* Logs\%1\*.* /s /y >%1.log
if not "%1"=="" del /s /q /f \\%1\logs\*.* >>%1.log
if not "%2"=="" xcopy \\%2\Logs\*.* Logs\%2\*.* /s /y >%2.log
if not "%2"=="" del /s /q /f \\%2\logs\*.* >>%2.log
if not "%3"=="" xcopy \\%3\Logs\*.* Logs\%3\*.* /s /y >%3.log
if not "%3"=="" del /s /q /f \\%3\logs\*.* >>%3.log
if not "%4"=="" xcopy \\%4\Logs\*.* Logs\%4\*.* /s /y >%4.log
if not "%4"=="" del /s /q /f \\%4\logs\*.* >>%4.log
if not "%5"=="" xcopy \\%5\Logs\*.* Logs\%5\*.* /s /y >%5.log
if not "%5"=="" del /s /q /f \\%5\logs\*.* >>%5.log
if not "%6"=="" xcopy \\%6\Logs\*.* Logs\%6\*.* /s /y >%6.log
if not "%6"=="" del /s /q /f \\%6\logs\*.* >>%6.log
if not "%7"=="" xcopy \\%7\Logs\*.* Logs\%7\*.* /s /y >%7.log
if not "%7"=="" del /s /q /f \\%7\logs\*.* >>%7.log
if not "%8"=="" xcopy \\%8\Logs\*.* Logs\%8\*.* /s /y >%8.log
if not "%8"=="" del /s /q /f \\%8\logs\*.* >>%8.log
if not "%9"=="" xcopy \\%9\Logs\*.* Logs\%9\*.* /s /y >%9.log
if not "%9"=="" del /s /q /f \\%9\logs\*.* >>%9.log
