'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''eToolKit_UserControls_SideNav class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class eToolKit_UserControls_SideNav

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''SelectionTreeMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectionTreeMenu As Global.Nrc.MySolutions.MenuBox

    '''<summary>
    '''SelectionTreeTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectionTreeTitle As Global.Nrc.MySolutions.MenuBoxTitle

    '''<summary>
    '''SelectionTreeImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectionTreeImage As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''SelectionTreeMenuExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectionTreeMenuExtender As Global.AjaxControlToolkit.CollapsiblePanelExtender

    '''<summary>
    '''SelectionTreeMenuBody control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectionTreeMenuBody As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ltlSelectionTreeMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltlSelectionTreeMenu As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ToolBoxMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToolBoxMenu As Global.Nrc.MySolutions.MenuBox

    '''<summary>
    '''ToolBoxTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToolBoxTitle As Global.Nrc.MySolutions.MenuBoxTitle

    '''<summary>
    '''ToolBoxImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToolBoxImage As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''ToolBoxMenuExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToolBoxMenuExtender As Global.AjaxControlToolkit.CollapsiblePanelExtender

    '''<summary>
    '''ToolBoxMenuBody control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToolBoxMenuBody As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''QuestionImportanceLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QuestionImportanceLink As Global.Nrc.MySolutions.MenuBoxLink

    '''<summary>
    '''QuickCheckLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QuickCheckLink As Global.Nrc.MySolutions.MenuBoxLink

    '''<summary>
    '''RecommendationsLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RecommendationsLink As Global.Nrc.MySolutions.MenuBoxLink

    '''<summary>
    '''ResourcesLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ResourcesLink As Global.Nrc.MySolutions.MenuBoxLink

    '''<summary>
    '''QuestionResultsLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QuestionResultsLink As Global.Nrc.MySolutions.MenuBoxLink

    '''<summary>
    '''CommentsLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CommentsLink As Global.Nrc.MySolutions.MenuBoxLink

    '''<summary>
    '''ResearchInquiry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ResearchInquiry As Global.Nrc.MySolutions.MenuBoxLink

    '''<summary>
    '''LnForumsLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LnForumsLink As Global.Nrc.MySolutions.MenuBoxLink

    '''<summary>
    '''LnArchiveLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LnArchiveLink As Global.Nrc.MySolutions.MenuBoxLink

    '''<summary>
    '''PatientEyesLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PatientEyesLink As Global.Nrc.MySolutions.MenuBoxLink

    '''<summary>
    '''MemberResourcesMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MemberResourcesMenu As Global.Nrc.MySolutions.MenuBox

    '''<summary>
    '''MemberResourcesTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MemberResourcesTitle As Global.Nrc.MySolutions.MenuBoxTitle

    '''<summary>
    '''MemberResourcesImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MemberResourcesImage As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''MemberResourcesExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MemberResourcesExtender As Global.AjaxControlToolkit.CollapsiblePanelExtender

    '''<summary>
    '''MemberResourcesBody control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MemberResourcesBody As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''MemberResourcesList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MemberResourcesList As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''MemberResourcesMoreLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MemberResourcesMoreLink As Global.Nrc.MySolutions.MenuBoxLink

    '''<summary>
    '''ActionPlansMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ActionPlansMenu As Global.Nrc.MySolutions.MenuBox

    '''<summary>
    '''ActionPlansTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ActionPlansTitle As Global.Nrc.MySolutions.MenuBoxTitle

    '''<summary>
    '''ActionPlansImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ActionPlansImage As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''ActionPlansMenuExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ActionPlansMenuExtender As Global.AjaxControlToolkit.CollapsiblePanelExtender

    '''<summary>
    '''ActionPlansBody control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ActionPlansBody As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ActionPlansNotAvailable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ActionPlansNotAvailable As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ActionPlansTree control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ActionPlansTree As Global.System.Web.UI.WebControls.TreeView

    '''<summary>
    '''SupportMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SupportMenu As Global.Nrc.MySolutions.MenuBox

    '''<summary>
    '''SupportTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SupportTitle As Global.Nrc.MySolutions.MenuBoxTitle

    '''<summary>
    '''SupportImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SupportImage As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''SupportMenuExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SupportMenuExtender As Global.AjaxControlToolkit.CollapsiblePanelExtender

    '''<summary>
    '''SupportMenuBody control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SupportMenuBody As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''PreferencesLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PreferencesLink As Global.Nrc.MySolutions.MenuBoxLink

    '''<summary>
    '''HelpLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HelpLink As Global.Nrc.MySolutions.MenuBoxLink

    '''<summary>
    '''ContactLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactLink As Global.Nrc.MySolutions.MenuBoxLink

    '''<summary>
    '''SiteRequirementsLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SiteRequirementsLink As Global.Nrc.MySolutions.MenuBoxLink

    '''<summary>
    '''ControlChartLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ControlChartLink As Global.Nrc.MySolutions.MenuBoxLink
End Class
