CREATE NONCLUSTERED INDEX [davetemp] ON [dbo].[dg_plaintext]
(
	[survey_id] ASC,
	[selqstns_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


