CREATE NONCLUSTERED INDEX [ewq_SamplePop] ON [dbo].[Extract_Web_QuestionForm]
(
	[SamplePop_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


