CREATE NONCLUSTERED INDEX [IDX_SLCTDSMPL_STUDY_POP_ID_EncDt] ON [dbo].[SELECTEDSAMPLE]
(
	[STUDY_ID] ASC,
	[POP_ID] ASC,
	[SampleEncounterDate] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]


