CREATE NONCLUSTERED INDEX [IDX_SELECTEDSAMPLE_intExtracted_flg] ON [dbo].[SELECTEDSAMPLE]
(
	[intExtracted_flg] ASC,
	[SAMPLESET_ID] ASC
)
INCLUDE ( 	[SELECTEDSAMPLE_ID]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]


