CREATE NONCLUSTERED INDEX [idx_selqstns_SkipPatternCover] ON [dbo].[SEL_QSTNS]
(
	[SURVEY_ID] ASC,
	[QSTNCORE] ASC,
	[NUMMARKCOUNT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]


