CREATE UNIQUE NONCLUSTERED INDEX [idx_names] ON [dbo].[EMPLOYEE]
(
	[STREMPLOYEE_FIRST_NM] ASC,
	[STREMPLOYEE_LAST_NM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]


