CREATE NONCLUSTERED INDEX [IDX_SLCTDSMPL_SAMPLEUNIT_SLCTYPE_XFlg] ON [dbo].[SELECTEDSAMPLE]
(
	[SAMPLEUNIT_ID] ASC,
	[STRUNITSELECTTYPE] ASC,
	[intExtracted_flg] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


