CREATE NONCLUSTERED INDEX [idx_covering] ON [dbo].[DL_SampleUnitSection_BySampleset]
(
	[SAMPLEUNIT_ID] ASC,
	[SELQSTNSSECTION] ASC,
	[SELQSTNSSURVEY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]


