CREATE NONCLUSTERED INDEX [idx_DL_SampleunitSection_bySampleset_Section] ON [dbo].[DL_SampleUnitSection_BySampleset]
(
	[SELQSTNSSECTION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]


