CREATE NONCLUSTERED INDEX [IDX_QFORM_UNUSED] ON [dbo].[QUESTIONFORM]
(
	[UnusedReturn_id] ASC,
	[QUESTIONFORM_ID] ASC
)
WHERE ([UNUSEDRETURN_ID]>(0))
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]


