CREATE UNIQUE NONCLUSTERED INDEX [IDX_UNIQ_STRPARAM_NM] ON [dbo].[QUALPRO_PARAMS]
(
	[STRPARAM_NM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]


