CREATE NONCLUSTERED INDEX [IDX_SCHEDULEDMAILING_SENTMAIL_ID] ON [dbo].[SCHEDULEDMAILING]
(
	[SENTMAIL_ID] ASC,
	[DATGENERATE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]


