CREATE NONCLUSTERED INDEX [idx_covering] ON [dbo].[SkipIdentifier]
(
	[datGenerated] ASC,
	[QstnCore] ASC,
	[intResponseval] ASC
)
INCLUDE ( 	[Skip_id],
	[Survey_id]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]


