CREATE NONCLUSTERED INDEX [IDX_DATASETMEMBER_POPDS] ON [dbo].[DATASETMEMBER]
(
	[POP_ID] ASC,
	[DATASET_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]


