CREATE NONCLUSTERED INDEX [idx_sentm_smmethdat] ON [dbo].[SENTMAILING]
(
	[SENTMAIL_ID] ASC,
	[METHODOLOGY_ID] ASC,
	[DATPRINTED] ASC,
	[DATMAILED] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


