CREATE NONCLUSTERED INDEX [idx_covering] ON [dbo].[DL_SEL_QSTNS_BySampleSet]
(
	[SECTION_ID] ASC,
	[SURVEY_ID] ASC,
	[SampleSet_ID] ASC,
	[SUBTYPE] ASC,
	[QSTNCORE] ASC,
	[SCALEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]


