CREATE UNIQUE NONCLUSTERED INDEX [IDX_SMPLPOP_EXPORT] ON [dbo].[SAMPLEPOP]
(
	[STUDY_ID] ASC,
	[POP_ID] ASC,
	[SAMPLESET_ID] ASC,
	[SAMPLEPOP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]


