CREATE NONCLUSTERED INDEX [idx_stdydsdtload] ON [dbo].[DATA_SET]
(
	[STUDY_ID] ASC,
	[DATASET_ID] ASC,
	[DATLOAD_DT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]


