CREATE NONCLUSTERED INDEX [INV_NOTIF_HIST_INV_NUMBER_IND] ON [dbo].[INV_NOTIFICATIONS_HIST]
(
	[INVOICE_NUMBER] ASC,
	[NOTIFICATION_DATE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]


