CREATE NONCLUSTERED INDEX [IX_GroupedPrint_SurveyPaperConfigBundled] ON [dbo].[GroupedPrint]
(
	[Survey_id] ASC,
	[PaperConfig_id] ASC,
	[datBundled] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


