CREATE NONCLUSTERED INDEX [IX_MAILINGSUMMARY_SAMPLESET_ID] ON [dbo].[MAILINGSUMMARY]
(
	[SAMPLESET_ID] ASC
)
INCLUDE ( 	[MAILINGSTEP_ID],
	[DATMAILED]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]


