CREATE NONCLUSTERED INDEX [IX_MAILINGSUMMARY_DATMAILED] ON [dbo].[MAILINGSUMMARY]
(
	[DATMAILED] ASC
)
INCLUDE ( 	[INTPAGES],
	[MAILINGSTEP_ID],
	[SAMPLESET_ID],
	[MAILCOUNT],
	[SURVEY_ID]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]


