CREATE NONCLUSTERED INDEX [IX_NPSENTMAILING_DATPRINTED_METHODOLOGY_ID_PAPERCONFIG_ID_STRPOSTALBUNDLE_datBundled_SENTMAIL_ID_STRLITHOCODE_STRGROUPDEST] ON [dbo].[NPSENTMAILING]
(
	[DATPRINTED] ASC,
	[METHODOLOGY_ID] ASC,
	[PAPERCONFIG_ID] ASC,
	[STRPOSTALBUNDLE] ASC,
	[datBundled] ASC
)
INCLUDE ( 	[SENTMAIL_ID],
	[STRLITHOCODE],
	[STRGROUPDEST]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]


