CREATE NONCLUSTERED INDEX [IX_PeriodDates_datScheduledSample_dt] ON [dbo].[PeriodDates]
(
	[datScheduledSample_dt] ASC
)
INCLUDE ( 	[PeriodDef_id]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]


