CREATE NONCLUSTERED INDEX [IX_PeriodDates_datSampleCreate_dt] ON [dbo].[PeriodDates]
(
	[datSampleCreate_dt] ASC,
	[PeriodDef_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]


