CREATE NONCLUSTERED INDEX [IX_Period_Survey_id_datPeriodDate] ON [dbo].[Period]
(
	[Survey_id] ASC,
	[datPeriodDate] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


