CREATE NONCLUSTERED INDEX [IX_SAMPLESET_web_extract_flg] ON [dbo].[SAMPLESET]
(
	[web_extract_flg] ASC,
	[datScheduled] ASC
)
INCLUDE ( 	[SAMPLESET_ID]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]


