CREATE NONCLUSTERED INDEX [IX_SAMPLESET_DATSAMPLECREATE_DT] ON [dbo].[SAMPLESET]
(
	[DATSAMPLECREATE_DT] ASC,
	[tiOversample_flag] ASC
)
INCLUDE ( 	[SURVEY_ID],
	[datScheduled],
	[SAMPLESET_ID]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]


