CREATE NONCLUSTERED INDEX [ix_SELECTEDSAMPLE_STUDY_ID_includes] ON [dbo].[SELECTEDSAMPLE]
(
	[STUDY_ID] ASC
)
INCLUDE ( 	[enc_id]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]


