CREATE NONCLUSTERED INDEX [IX_targetinfosurveydateunit] ON [dbo].[targetinfo]
(
	[survey_id] ASC,
	[perioddate] ASC,
	[sampleunit_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]


