CREATE NONCLUSTERED INDEX [IX_TAGFIELD_STUDY_ID_TAG_ID_STRREPLACELITERAL] ON [dbo].[TAGFIELD]
(
	[STUDY_ID] ASC
)
INCLUDE ( 	[TAG_ID],
	[STRREPLACELITERAL]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]


