CREATE NONCLUSTERED INDEX [ReEval_SvyGen] ON [dbo].[ReEvalSkip]
(
	[survey_id] ASC,
	[datGenerated] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]


