CREATE NONCLUSTERED INDEX [ReEval_StSpSuQcVal] ON [dbo].[ReEvalSkip]
(
	[study_id] ASC,
	[samplepop_id] ASC,
	[sampleunit_id] ASC,
	[qstncore] ASC,
	[ReEval] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]


