CREATE NONCLUSTERED INDEX [tmp] ON [dbo].[drm_SAMPLEPOP_INC0028463]
(
	[SAMPLESET_ID] ASC,
	[POP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]


