CREATE NONCLUSTERED INDEX [tmp_dataload_litho] ON [dbo].[DL_LithoCodes]
(
	[SurveyDataLoad_ID] ASC
)
INCLUDE ( 	[strLithoCode]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]


