CREATE NONCLUSTERED INDEX [tmp_vendorid_dataload] ON [dbo].[DL_DataLoad]
(
	[Vendor_ID] ASC
)
INCLUDE ( 	[DataLoad_ID]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]


