CREATE NONCLUSTERED INDEX [tmpindex] ON [dbo].[SEL_QSTNS]
(
	[LANGUAGE] ASC,
	[SUBTYPE] ASC,
	[QSTNCORE] ASC,
	[SURVEY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]


