// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1053:StaticHolderTypesShouldNotHaveConstructors", Scope = "TypeOfFile", Target = "ExportClient.App_Start.ElmahMvc")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Nrc.CatalystExporter.ExportClient.MvcApplication.#Application_Start()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "Nrc.CatalystExporter.ExportClient.Helpers.CatalystHelper.#GetClientStudySurveys(Nrc.CatalystExporter.Logging.UserContext,System.Int64[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "Nrc.CatalystExporter.ExportClient.Helpers.CatalystHelper.#GetClientStudySurveys(Nrc.CatalystExporter.Logging.UserContext,System.String[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "Nrc.CatalystExporter.ExportClient.Controllers.HomeController.#FindLogs(System.Collections.Generic.ICollection`1<System.Int32>,System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Nrc.CatalystExporter.ExportClient.Helpers.FileCreationHelper.#WriteDelimitedRow(System.Collections.Generic.List`1<System.String>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "Nrc.CatalystExporter.ExportClient.Helpers.FileCreationHelper.#WriteExportToFile(System.String,System.DateTime,System.DateTime,System.Collections.Generic.IEnumerable`1<System.Int32>,System.Collections.Generic.IEnumerable`1<Nrc.CatalystExporter.DataContracts.ColumnDefinition>,Nrc.CatalystExporter.Logging.UserContext)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "Nrc.CatalystExporter.ExportClient.Helpers.FileCreationHelper.#WriteToDelimitedFile(System.DateTime,System.DateTime,Nrc.CatalystExporter.Logging.UserContext,System.Collections.Generic.List`1<System.String>,Nrc.CatalystExporter.DataContracts.ClientStudySurvey,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Nrc.CatalystExporter.ExportClient.Helpers.EnumHelper.#GetSelectList`1(!!0[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1004:GenericMethodsShouldProvideTypeParameter", Scope = "member", Target = "Nrc.CatalystExporter.ExportClient.Helpers.EnumHelper.#IntToFormattedString`1(System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1004:GenericMethodsShouldProvideTypeParameter", Scope = "member", Target = "Nrc.CatalystExporter.ExportClient.Helpers.EnumHelper.#StringToInt`1(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "Nrc.CatalystExporter.ExportClient.Helpers.FileCreationHelper.#WriteToDelimitedFile(System.DateTime,System.DateTime,Nrc.CatalystExporter.Logging.UserContext,System.Collections.Generic.List`1<System.String>,Nrc.CatalystExporter.DataContracts.ClientStudySurvey,System.String,System.Char)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Nrc.CatalystExporter.ExportClient.Helpers.FileCreationHelper.#WriteDelimitedRow(System.Collections.Generic.List`1<System.String>,System.Char)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2233:OperationsShouldNotOverflow", MessageId = "page-1", Scope = "member", Target = "Nrc.CatalystExporter.ExportClient.Controllers.HomeController.#FindLogs(System.Collections.Generic.ICollection`1<System.Int32>,System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Nrc.CatalystExporter.ExportClient.Models.CreateNewModel.#Times")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Nrc.CatalystExporter.ExportClient.Models.NewDefinition.#Columns")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Nrc.CatalystExporter.ExportClient.Models.NewDefinition.#Columns")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "Nrc.CatalystExporter.ExportClient.Controllers.HomeController.#FindScheduled(System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2233:OperationsShouldNotOverflow", MessageId = "page-1", Scope = "member", Target = "Nrc.CatalystExporter.ExportClient.Controllers.HomeController.#FindScheduled(System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Nrc.CatalystExporter.ExportClient.Models.EditScheduleModel.#DemographicFields")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Nrc.CatalystExporter.ExportClient.Models.EditScheduleModel.#DemographicFields")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA1806:DoNotIgnoreMethodResults", MessageId = "System.Int32.TryParse(System.String,System.Int32@)", Scope = "member", Target = "Nrc.CatalystExporter.ExportClient.Controllers.HomeController.#FindNav(System.String,System.String)")]
