'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.42.
'
Namespace InOutService
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="InOutSoap", [Namespace]:="http://tempuri.org//InOut")>  _
    Partial Public Class InOut
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private GetUserListOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetStatusListOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetUserIdOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetUserStatusListOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetUserStatusOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetUserStatus1OperationCompleted As System.Threading.SendOrPostCallback
        
        Private SetUserStatusOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Nrc.InOutClient.My.MySettings.Default.InOutClient_InOutService_InOut
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event GetUserListCompleted As GetUserListCompletedEventHandler
        
        '''<remarks/>
        Public Event GetStatusListCompleted As GetStatusListCompletedEventHandler
        
        '''<remarks/>
        Public Event GetUserIdCompleted As GetUserIdCompletedEventHandler
        
        '''<remarks/>
        Public Event GetUserStatusListCompleted As GetUserStatusListCompletedEventHandler
        
        '''<remarks/>
        Public Event GetUserStatusCompleted As GetUserStatusCompletedEventHandler
        
        '''<remarks/>
        Public Event GetUserStatus1Completed As GetUserStatus1CompletedEventHandler
        
        '''<remarks/>
        Public Event SetUserStatusCompleted As SetUserStatusCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org//InOut/GetUserList", RequestNamespace:="http://tempuri.org//InOut", ResponseNamespace:="http://tempuri.org//InOut", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetUserList() As String()
            Dim results() As Object = Me.Invoke("GetUserList", New Object(-1) {})
            Return CType(results(0),String())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetUserListAsync()
            Me.GetUserListAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetUserListAsync(ByVal userState As Object)
            If (Me.GetUserListOperationCompleted Is Nothing) Then
                Me.GetUserListOperationCompleted = AddressOf Me.OnGetUserListOperationCompleted
            End If
            Me.InvokeAsync("GetUserList", New Object(-1) {}, Me.GetUserListOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetUserListOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetUserListCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetUserListCompleted(Me, New GetUserListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org//InOut/GetStatusList", RequestNamespace:="http://tempuri.org//InOut", ResponseNamespace:="http://tempuri.org//InOut", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetStatusList() As StatusInfo()
            Dim results() As Object = Me.Invoke("GetStatusList", New Object(-1) {})
            Return CType(results(0),StatusInfo())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetStatusListAsync()
            Me.GetStatusListAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetStatusListAsync(ByVal userState As Object)
            If (Me.GetStatusListOperationCompleted Is Nothing) Then
                Me.GetStatusListOperationCompleted = AddressOf Me.OnGetStatusListOperationCompleted
            End If
            Me.InvokeAsync("GetStatusList", New Object(-1) {}, Me.GetStatusListOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetStatusListOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetStatusListCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetStatusListCompleted(Me, New GetStatusListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org//InOut/GetUserId", RequestNamespace:="http://tempuri.org//InOut", ResponseNamespace:="http://tempuri.org//InOut", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetUserId(ByVal userName As String) As Integer
            Dim results() As Object = Me.Invoke("GetUserId", New Object() {userName})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetUserIdAsync(ByVal userName As String)
            Me.GetUserIdAsync(userName, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetUserIdAsync(ByVal userName As String, ByVal userState As Object)
            If (Me.GetUserIdOperationCompleted Is Nothing) Then
                Me.GetUserIdOperationCompleted = AddressOf Me.OnGetUserIdOperationCompleted
            End If
            Me.InvokeAsync("GetUserId", New Object() {userName}, Me.GetUserIdOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetUserIdOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetUserIdCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetUserIdCompleted(Me, New GetUserIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org//InOut/GetUserStatusList", RequestNamespace:="http://tempuri.org//InOut", ResponseNamespace:="http://tempuri.org//InOut", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetUserStatusList() As InOutInfo()
            Dim results() As Object = Me.Invoke("GetUserStatusList", New Object(-1) {})
            Return CType(results(0),InOutInfo())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetUserStatusListAsync()
            Me.GetUserStatusListAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetUserStatusListAsync(ByVal userState As Object)
            If (Me.GetUserStatusListOperationCompleted Is Nothing) Then
                Me.GetUserStatusListOperationCompleted = AddressOf Me.OnGetUserStatusListOperationCompleted
            End If
            Me.InvokeAsync("GetUserStatusList", New Object(-1) {}, Me.GetUserStatusListOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetUserStatusListOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetUserStatusListCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetUserStatusListCompleted(Me, New GetUserStatusListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org//InOut/GetUserStatusById", RequestElementName:="GetUserStatusById", RequestNamespace:="http://tempuri.org//InOut", ResponseElementName:="GetUserStatusByIdResponse", ResponseNamespace:="http://tempuri.org//InOut", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Overloads Function GetUserStatus(ByVal userId As Integer) As <System.Xml.Serialization.XmlElementAttribute("GetUserStatusByIdResult")> InOutInfo
            Dim results() As Object = Me.Invoke("GetUserStatus", New Object() {userId})
            Return CType(results(0),InOutInfo)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetUserStatusAsync(ByVal userId As Integer)
            Me.GetUserStatusAsync(userId, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetUserStatusAsync(ByVal userId As Integer, ByVal userState As Object)
            If (Me.GetUserStatusOperationCompleted Is Nothing) Then
                Me.GetUserStatusOperationCompleted = AddressOf Me.OnGetUserStatusOperationCompleted
            End If
            Me.InvokeAsync("GetUserStatus", New Object() {userId}, Me.GetUserStatusOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetUserStatusOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetUserStatusCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetUserStatusCompleted(Me, New GetUserStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.WebMethodAttribute(MessageName:="GetUserStatus1"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org//InOut/GetUserStatusByName", RequestElementName:="GetUserStatusByName", RequestNamespace:="http://tempuri.org//InOut", ResponseElementName:="GetUserStatusByNameResponse", ResponseNamespace:="http://tempuri.org//InOut", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Overloads Function GetUserStatus(ByVal userName As String) As <System.Xml.Serialization.XmlElementAttribute("GetUserStatusByNameResult")> InOutInfo
            Dim results() As Object = Me.Invoke("GetUserStatus1", New Object() {userName})
            Return CType(results(0),InOutInfo)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetUserStatus1Async(ByVal userName As String)
            Me.GetUserStatus1Async(userName, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetUserStatus1Async(ByVal userName As String, ByVal userState As Object)
            If (Me.GetUserStatus1OperationCompleted Is Nothing) Then
                Me.GetUserStatus1OperationCompleted = AddressOf Me.OnGetUserStatus1OperationCompleted
            End If
            Me.InvokeAsync("GetUserStatus1", New Object() {userName}, Me.GetUserStatus1OperationCompleted, userState)
        End Sub
        
        Private Sub OnGetUserStatus1OperationCompleted(ByVal arg As Object)
            If (Not (Me.GetUserStatus1CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetUserStatus1Completed(Me, New GetUserStatus1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org//InOut/SetUserStatus", RequestNamespace:="http://tempuri.org//InOut", ResponseNamespace:="http://tempuri.org//InOut", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub SetUserStatus(ByVal userId As Integer, ByVal statusId As Integer)
            Me.Invoke("SetUserStatus", New Object() {userId, statusId})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SetUserStatusAsync(ByVal userId As Integer, ByVal statusId As Integer)
            Me.SetUserStatusAsync(userId, statusId, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SetUserStatusAsync(ByVal userId As Integer, ByVal statusId As Integer, ByVal userState As Object)
            If (Me.SetUserStatusOperationCompleted Is Nothing) Then
                Me.SetUserStatusOperationCompleted = AddressOf Me.OnSetUserStatusOperationCompleted
            End If
            Me.InvokeAsync("SetUserStatus", New Object() {userId, statusId}, Me.SetUserStatusOperationCompleted, userState)
        End Sub
        
        Private Sub OnSetUserStatusOperationCompleted(ByVal arg As Object)
            If (Not (Me.SetUserStatusCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SetUserStatusCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org//InOut")>  _
    Partial Public Class StatusInfo
        
        Private inOutStatusIDField As Integer
        
        Private statusField As String
        
        Private isAvailableField As Boolean
        
        Private webLabelField As String
        
        '''<remarks/>
        Public Property InOutStatusID() As Integer
            Get
                Return Me.inOutStatusIDField
            End Get
            Set
                Me.inOutStatusIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsAvailable() As Boolean
            Get
                Return Me.isAvailableField
            End Get
            Set
                Me.isAvailableField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property WebLabel() As String
            Get
                Return Me.webLabelField
            End Get
            Set
                Me.webLabelField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org//InOut")>  _
    Partial Public Class InOutInfo
        
        Private userIDField As Integer
        
        Private firstNameField As String
        
        Private lastNameField As String
        
        Private emailField As String
        
        Private userNameField As String
        
        Private statusIDField As Integer
        
        Private statusField As String
        
        Private isAvailableField As Boolean
        
        Private webLabelField As String
        
        Private teamIDField As Integer
        
        Private teamNameField As String
        
        Private phoneExtensionField As String
        
        Private officeIDField As Integer
        
        Private officeNameField As String
        
        '''<remarks/>
        Public Property UserID() As Integer
            Get
                Return Me.userIDField
            End Get
            Set
                Me.userIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FirstName() As String
            Get
                Return Me.firstNameField
            End Get
            Set
                Me.firstNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LastName() As String
            Get
                Return Me.lastNameField
            End Get
            Set
                Me.lastNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Email() As String
            Get
                Return Me.emailField
            End Get
            Set
                Me.emailField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UserName() As String
            Get
                Return Me.userNameField
            End Get
            Set
                Me.userNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StatusID() As Integer
            Get
                Return Me.statusIDField
            End Get
            Set
                Me.statusIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsAvailable() As Boolean
            Get
                Return Me.isAvailableField
            End Get
            Set
                Me.isAvailableField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property WebLabel() As String
            Get
                Return Me.webLabelField
            End Get
            Set
                Me.webLabelField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TeamID() As Integer
            Get
                Return Me.teamIDField
            End Get
            Set
                Me.teamIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TeamName() As String
            Get
                Return Me.teamNameField
            End Get
            Set
                Me.teamNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PhoneExtension() As String
            Get
                Return Me.phoneExtensionField
            End Get
            Set
                Me.phoneExtensionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OfficeID() As Integer
            Get
                Return Me.officeIDField
            End Get
            Set
                Me.officeIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OfficeName() As String
            Get
                Return Me.officeNameField
            End Get
            Set
                Me.officeNameField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")>  _
    Public Delegate Sub GetUserListCompletedEventHandler(ByVal sender As Object, ByVal e As GetUserListCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetUserListCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")>  _
    Public Delegate Sub GetStatusListCompletedEventHandler(ByVal sender As Object, ByVal e As GetStatusListCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetStatusListCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As StatusInfo()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),StatusInfo())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")>  _
    Public Delegate Sub GetUserIdCompletedEventHandler(ByVal sender As Object, ByVal e As GetUserIdCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetUserIdCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")>  _
    Public Delegate Sub GetUserStatusListCompletedEventHandler(ByVal sender As Object, ByVal e As GetUserStatusListCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetUserStatusListCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As InOutInfo()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),InOutInfo())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")>  _
    Public Delegate Sub GetUserStatusCompletedEventHandler(ByVal sender As Object, ByVal e As GetUserStatusCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetUserStatusCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As InOutInfo
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),InOutInfo)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")>  _
    Public Delegate Sub GetUserStatus1CompletedEventHandler(ByVal sender As Object, ByVal e As GetUserStatus1CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetUserStatus1CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As InOutInfo
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),InOutInfo)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")>  _
    Public Delegate Sub SetUserStatusCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
End Namespace
