Friend Class SP
    Public Shared ReadOnly GetCustomers As String = "dbo.GetCustomers"
    Public Shared ReadOnly GetCustomer As String = "dbo.GetCustomer"
    Public Shared ReadOnly InsertCustomer As String = "dbo.InsertCustomer"
    Public Shared ReadOnly UpdateCustomer As String = "dbo.UpdateCustomer"
    Public Shared ReadOnly DeleteCustomer As String = "dbo.DeleteCustomer"
#Region "RespondentImportProcs"
    Public Shared ReadOnly GetConfigVars As String = "dbo.GetConfigVars"
    Public Shared ReadOnly GetRespondentImportSchedules As String = "dbo.IU_GetRespondentImportSchedules"
    Public Shared ReadOnly GetRespondentImportSchedule As String = "dbo.IU_GetRespondentImportSchedule"
    Public Shared ReadOnly GetRespImportFileLogByFileID As String = "dbo.IU_GetRespondentImportFileLogByFileID"
    Public Shared ReadOnly GetRespondentImportFileLogsByDate As String = "dbo.IU_GetRespondentImportFileLogsByDate"
    Public Shared ReadOnly AddRespondentImportFileLog As String = "dbo.IU_AddRespondentImportFileLog"
    Public Shared ReadOnly GetRespondentImportFileLineLogsByImportFileID As String = "dbo.IU_GetRespondentImportFileLineLogsByImportFileID"
    Public Shared ReadOnly AddRespondentImportFileLineLog As String = "dbo.IU_AddRespondentImportFileLineLog"
    Public Shared ReadOnly GetFileDefVarsByTemplateID As String = "dbo.IU_GetFileDefVarsByTemplateID"
    Public Shared ReadOnly GetSurveyInstanceID As String = "dbo.IU_GetSurveyInstanceID"
    Public Shared ReadOnly RespondentHasResponses As String = "dbo.IU_RespondentHasResponses"
    Public Shared ReadOnly ImportResponsesToStaging As String = "dbo.IU_ImportResponsesToStaging"
    Public Shared ReadOnly RemoveResponesFromStaging As String = "dbo.IU_RemoveResponsesFromStaging"
    Public Shared ReadOnly ImportResponseLine As String = "dbo.IU_ImportResponseLine"
    Public Shared ReadOnly GetFileDefTableByFileDefID As String = "dbo.IU_GetFileDefTableByFileDefID"
    Public Shared ReadOnly HasCompleteCode As String = "dbo.IU_HasCompleteCode"
#End Region
End Class
