CREATE TABLE [dbo].[COMMENTLINEPOS](
	[QUESTIONFORM_ID] [int] NOT NULL,
	[INTPAGE_NUM] [int] NOT NULL,
	[CMNTBOX_ID] [int] NOT NULL,
	[INTLINE_NUM] [int] NOT NULL,
	[SAMPLEUNIT_ID] [int] NOT NULL,
	[X_POS] [int] NOT NULL,
	[Y_POS] [int] NOT NULL,
	[INTWIDTH] [int] NOT NULL,
	[INTHEIGHT] [int] NOT NULL
) ON [PRIMARY]


