'The following code was generated by Microsoft Visual Studio 2005.
'The test owner should check each test for validity.
Imports Microsoft.VisualStudio.TestTools.UnitTesting
Imports System
Imports System.Text
Imports System.Collections.Generic




'''<summary>
'''This is a test class for Nrc.Qualisys.QLoader.FileLoader.FileLoader and is intended
'''to contain all Nrc.Qualisys.QLoader.FileLoader.FileLoader Unit Tests
'''</summary>
<TestClass()> _
Public Class FileLoaderTest


    Private testContextInstance As TestContext

    '''<summary>
    '''Gets or sets the test context which provides
    '''information about and functionality for the current test run.
    '''</summary>
    Public Property TestContext() As TestContext
        Get
            Return testContextInstance
        End Get
        Set(ByVal value As TestContext)
            testContextInstance = value
        End Set
    End Property
#Region "Additional test attributes"
    '
    'You can use the following additional attributes as you write your tests:
    '
    'Use ClassInitialize to run code before running the first test in the class
    '
    '<ClassInitialize()>  _
    'Public Shared Sub MyClassInitialize(ByVal testContext As TestContext)
    'End Sub
    '
    'Use ClassCleanup to run code after all tests in a class have run
    '
    '<ClassCleanup()>  _
    'Public Shared Sub MyClassCleanup()
    'End Sub
    '
    'Use TestInitialize to run code before running each test
    '
    '<TestInitialize()>  _
    'Public Sub MyTestInitialize()
    'End Sub
    '
    'Use TestCleanup to run code after each test has run
    '
    '<TestCleanup()>  _
    'Public Sub MyTestCleanup()
    'End Sub
    '
#End Region


    '''<summary>
    '''A test for LoadFile(ByVal Integer)
    ''' This is not an actual test but will allow to debug the loading code in FileLoader console app.
    ''' To use this test you need to stop the Qloader service in Testing then
    ''' Load a file in Qloader, write down the datafile_id of the loaded file and
    ''' assign it to the dataFileID in the test. It will allow you to debug loading process.
    '''</summary>
    <DeploymentItem("FileLoader.exe"), _
     TestMethod()> _
    Public Sub LoadFileTest()
        Dim dataFileID As Integer = 540 'TODO: Initialize to an appropriate value

        QLoaderTest.Nrc_Qualisys_QLoader_FileLoader_FileLoaderAccessor.LoadFile(dataFileID)
        Assert.IsTrue(True)
        'Assert.Inconclusive("A method that does not return a value cannot be verified.")
    End Sub

End Class
