CREATE PROCEDURE QCL_UnassignFacilityFromClient
@SUFacilityID INT,
@ClientID INT
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET NOCOUNT ON

DELETE ClientSUFacilityLookup
WHERE Client_id=@ClientID
AND SUFacility_id=@SUFacilityID

SET NOCOUNT OFF
SET TRANSACTION ISOLATION LEVEL READ COMMITTED


