CREATE PROCEDURE [dbo].[QCL_SelectAllToBeSeededs]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT Seed_id, Survey_id, IsSeeded, datSeeded, SurveyType_id, YearQtr
FROM [dbo].ToBeSeeded

SET NOCOUNT OFF
SET TRANSACTION ISOLATION LEVEL READ COMMITTED


