CREATE PROCEDURE [dbo].[QCL_UpdateSTUDY_EMPLOYEE]
@EMPLOYEE_ID INT,
@STUDY_ID INT
AS

SET NOCOUNT ON

UPDATE [dbo].STUDY_EMPLOYEE
SET EMPLOYEE_ID = @EMPLOYEE_ID,
	STUDY_ID = @STUDY_ID
WHERE EMPLOYEE_ID = @EMPLOYEE_ID
	AND STUDY_ID = @STUDY_ID

SET NOCOUNT OFF


