CREATE PROCEDURE [dbo].[QCL_SelectMM_EmailBlastsByMAILINGSTEPId]
@MAILINGSTEP_ID INT
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT MM_EmailBlast_ID, MAILINGSTEP_ID, EmailBlast_ID, DaysFromStepGen, DateSent
FROM MM_EmailBlast
WHERE MAILINGSTEP_ID = @MAILINGSTEP_ID

SET NOCOUNT OFF
SET TRANSACTION ISOLATION LEVEL READ COMMITTED


