CREATE PROCEDURE [dbo].[QCL_UpdateStudy]
@STUDY_ID int,
@STRSTUDY_NM char(10),
@STRSTUDY_DSC varchar(255),
@CLIENT_ID int,
@ADEMPLOYEE_ID int,
@DATCREATE_DT datetime,
@BITCLEANADDR bit,
@bitProperCase bit,
@Active bit,
@bitAutosample bit
AS

SET NOCOUNT ON

UPDATE [dbo].STUDY
SET STRSTUDY_NM = @STRSTUDY_NM,
	STRSTUDY_DSC = @STRSTUDY_DSC,
	CLIENT_ID = @CLIENT_ID,
	ADEMPLOYEE_ID = @ADEMPLOYEE_ID,
	DATCREATE_DT = @DATCREATE_DT,
	BITCLEANADDR = @BITCLEANADDR,
	bitProperCase = @bitProperCase,
	Active = @Active,
	bitAutosample = @bitAutosample
WHERE STUDY_ID = @STUDY_ID

SET NOCOUNT OFF


