CREATE PROCEDURE [dbo].[QCL_SelectSTUDY_EMPLOYEEsFullAccess]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT  EMPLOYEE_ID, Null STUDY_ID, STREMPLOYEE_FIRST_NM + ' ' + STREMPLOYEE_LAST_NM EMPLOYEENAME
FROM [dbo].EMPLOYEE
WHERE FullAccess = 1
ORDER BY STREMPLOYEE_FIRST_NM + ' ' + STREMPLOYEE_LAST_NM

SET NOCOUNT OFF
SET TRANSACTION ISOLATION LEVEL READ COMMITTED


