CREATE PROCEDURE [dbo].[QCL_SelectACOCAHPSDisposition]
@ACOCAHPSDispositionID INT
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT ACOCAHPSDispositionID, Disposition_ID, ACOCAHPSValue, ACOCAHPSHierarchy, ACOCAHPSDesc
FROM [dbo].ACOCAHPSDispositions
WHERE ACOCAHPSDispositionID = @ACOCAHPSDispositionID

SET NOCOUNT OFF
SET TRANSACTION ISOLATION LEVEL READ COMMITTED


