CREATE PROCEDURE QCL_AssignFacilityToClient
@SUFacilityID INT,
@ClientID INT
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET NOCOUNT ON

EXEC QCL_UnassignFacilityFromClient @SUFacilityID, @ClientID

INSERT INTO ClientSUFacilityLookup (Client_id, SUFacility_id)
SELECT @ClientID, @SUFacilityID

SET NOCOUNT OFF
SET TRANSACTION ISOLATION LEVEL READ COMMITTED


