CREATE PROCEDURE [dbo].[QCL_SelectAllMM_EmailBlasts]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT MM_EmailBlast_ID, MAILINGSTEP_ID, EmailBlast_ID, DaysFromStepGen, DateSent
FROM [dbo].MM_EmailBlast

SET NOCOUNT OFF
SET TRANSACTION ISOLATION LEVEL READ COMMITTED


