CREATE PROCEDURE [dbo].[QCL_SelectMM_EmailBlast_Option]
@EmailBlast_ID INT
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT EmailBlast_ID, Value
FROM [dbo].MM_EmailBlast_Options
WHERE EmailBlast_ID = @EmailBlast_ID

SET NOCOUNT OFF
SET TRANSACTION ISOLATION LEVEL READ COMMITTED


