CREATE PROCEDURE [dbo].[QCL_SelectMM_EmailBlastsByEmailBlastId]
@EmailBlast_ID INT
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT MM_EmailBlast_ID, MAILINGSTEP_ID, EmailBlast_ID, DaysFromStepGen, DateSent
FROM MM_EmailBlast
WHERE EmailBlast_ID = @EmailBlast_ID

SET NOCOUNT OFF
SET TRANSACTION ISOLATION LEVEL READ COMMITTED


