CREATE PROCEDURE [dbo].[QCL_InsertSTUDY_EMPLOYEE]
@EMPLOYEE_ID INT,
@STUDY_ID INT
AS

SET NOCOUNT ON

INSERT INTO [dbo].STUDY_EMPLOYEE (EMPLOYEE_ID, STUDY_ID)
VALUES (@EMPLOYEE_ID, @STUDY_ID)

--SELECT SCOPE_IDENTITY()
SELECT 1

SET NOCOUNT OFF


