CREATE PROCEDURE [dbo].[QCL_DeleteSAMPLEUNITSECTIONMapping]
@SAMPLEUNITSECTION_ID INT
AS

SET NOCOUNT ON

DELETE [dbo].SAMPLEUNITSECTION
WHERE SAMPLEUNITSECTION_ID = @SAMPLEUNITSECTION_ID

SET NOCOUNT OFF


