CREATE PROCEDURE [dbo].[QCL_SelectQuestionSectionsBySurvey_Id]
@Survey_id INT
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT DISTINCT SELQSTNS_ID, SURVEY_ID, SECTION_ID, LABEL
FROM [dbo].SEL_QSTNS
WHERE Survey_id=@Survey_id
	AND Sel_Qstns.SubType = 3 

SET NOCOUNT OFF
SET TRANSACTION ISOLATION LEVEL READ COMMITTED


