CREATE PROCEDURE [dbo].[QCL_SelectAllHCAHPSDispositions]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT HCAHPSDispositionID, Disposition_ID, HCAHPSValue, HCAHPSHierarchy, HCAHPSDesc
FROM [dbo].HCAHPSDispositions

SET NOCOUNT OFF
SET TRANSACTION ISOLATION LEVEL READ COMMITTED


