CREATE PROCEDURE [dbo].[QCL_SelectAllMM_EmailBlast_Options]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT EmailBlast_ID, Value
FROM [dbo].MM_EmailBlast_Options

SET NOCOUNT OFF
SET TRANSACTION ISOLATION LEVEL READ COMMITTED


