CREATE PROCEDURE [dbo].[QCL_InsertACOCAHPSDisposition]
@Disposition_ID INT,
@ACOCAHPSValue VARCHAR(2),
@ACOCAHPSHierarchy INT,
@ACOCAHPSDesc VARCHAR(100)
AS

SET NOCOUNT ON

INSERT INTO [dbo].ACOCAHPSDispositions (Disposition_ID, ACOCAHPSValue, ACOCAHPSHierarchy, ACOCAHPSDesc)
VALUES (@Disposition_ID, @ACOCAHPSValue, @ACOCAHPSHierarchy, @ACOCAHPSDesc)

SELECT SCOPE_IDENTITY()

SET NOCOUNT OFF


