CREATE PROCEDURE [dbo].[QCL_SelectAllHHCAHPSDispositions]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT HHCAHPSDispositionID, Disposition_ID, HHCAHPSValue, HHCAHPSHierarchy, HHCAHPSDesc
FROM [dbo].HHCAHPSDispositions

SET NOCOUNT OFF
SET TRANSACTION ISOLATION LEVEL READ COMMITTED


