CREATE PROCEDURE [dbo].[QCL_InsertSAMPLEUNITSECTIONMapping]
@SAMPLEUNIT_ID INT,
@SELQSTNSSECTION INT,
@SELQSTNSSURVEY_ID INT
AS

SET NOCOUNT ON

INSERT INTO [dbo].SAMPLEUNITSECTION (SAMPLEUNIT_ID, SELQSTNSSECTION, SELQSTNSSURVEY_ID)
VALUES (@SAMPLEUNIT_ID, @SELQSTNSSECTION, @SELQSTNSSURVEY_ID)

SELECT SCOPE_IDENTITY()

SET NOCOUNT OFF


