CREATE PROCEDURE [dbo].[QCL_SelectCoverLetterItems]
@SurveyID INT,
@CoverID INT
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT st.QPC_ID, st.COVERID, st.LABEL, 1 as ItemType
FROM SEL_TEXTBOX st 
WHERE st.Survey_id = @SurveyID
AND st.COVERID = @CoverID
AND LEN(st.LABEL) > 0
AND st.LANGUAGE = 1


SET NOCOUNT OFF
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
