CREATE PROCEDURE [dbo].[QCL_SelectHCAHPSDisposition]
@HCAHPSDispositionID INT
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT HCAHPSDispositionID, Disposition_ID, HCAHPSValue, HCAHPSHierarchy, HCAHPSDesc
FROM [dbo].HCAHPSDispositions
WHERE HCAHPSDispositionID = @HCAHPSDispositionID

SET NOCOUNT OFF
SET TRANSACTION ISOLATION LEVEL READ COMMITTED


