CREATE PROCEDURE [dbo].[QCL_SelectClient]
    @ClientID INT
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET NOCOUNT ON

SELECT Client_id, strClient_nm, Active, ClientGroup_ID 
FROM [dbo].Client 
WHERE Client_id = @ClientID

SET TRANSACTION ISOLATION LEVEL READ COMMITTED
SET NOCOUNT OFF


