CREATE PROCEDURE [dbo].[QCL_SelectHHCAHPSDisposition]
@HHCAHPSDispositionID INT
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT HHCAHPSDispositionID, Disposition_ID, HHCAHPSValue, HHCAHPSHierarchy, HHCAHPSDesc
FROM [dbo].HHCAHPSDispositions
WHERE HHCAHPSDispositionID = @HHCAHPSDispositionID

SET NOCOUNT OFF
SET TRANSACTION ISOLATION LEVEL READ COMMITTED


