CREATE PROCEDURE [dbo].[QCL_SelectHCAHPSDispositionsByDispositionId]
@Disposition_ID INT
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT HCAHPSDispositionID, Disposition_ID, HCAHPSValue, HCAHPSHierarchy, HCAHPSDesc
FROM HCAHPSDispositions
WHERE Disposition_ID = @Disposition_ID

SET NOCOUNT OFF
SET TRANSACTION ISOLATION LEVEL READ COMMITTED


