CREATE PROCEDURE [dbo].[QCL_SelectSAMPLEUNITSECTIONMappingsBySAMPLEUNIT_ID]
@SAMPLEUNIT_ID INT
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT SAMPLEUNITSECTION_ID, SAMPLEUNIT_ID, SELQSTNSSECTION, SELQSTNSSURVEY_ID
FROM SAMPLEUNITSECTION
WHERE SAMPLEUNIT_ID = @SAMPLEUNIT_ID

SET NOCOUNT OFF
SET TRANSACTION ISOLATION LEVEL READ COMMITTED


