CREATE PROCEDURE [dbo].[QCL_SelectAllACOCAHPSDispositions]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT ACOCAHPSDispositionID, Disposition_ID, ACOCAHPSValue, ACOCAHPSHierarchy, ACOCAHPSDesc
FROM [dbo].ACOCAHPSDispositions

SET NOCOUNT OFF
SET TRANSACTION ISOLATION LEVEL READ COMMITTED


