CREATE PROCEDURE [dbo].[QSL_SelectBadLitho]
@BadLitho_ID INT
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT BadLitho_ID, DataLoad_ID, BadstrLithoCode, DateCreated
FROM [dbo].DL_BadLithos
WHERE BadLitho_ID = @BadLitho_ID

SET NOCOUNT OFF
SET TRANSACTION ISOLATION LEVEL READ COMMITTED


