CREATE PROCEDURE [dbo].[QSL_SelectHandEntry]
@DL_HandEntry_ID INT
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT DL_HandEntry_ID, DL_LithoCode_ID, DL_Error_ID, QstnCore, ItemNumber, LineNumber, HandEntryText
FROM [dbo].DL_HandEntry
WHERE DL_HandEntry_ID = @DL_HandEntry_ID

SET NOCOUNT OFF
SET TRANSACTION ISOLATION LEVEL READ COMMITTED


