CREATE PROCEDURE [dbo].[QSL_SelectAllVendorFileStatus]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT VendorFileStatus_ID, VendorFileStatus_nm
FROM [dbo].VendorFileStatus

SET NOCOUNT OFF
SET TRANSACTION ISOLATION LEVEL READ COMMITTED


