CREATE PROCEDURE [dbo].[QSL_SelectCommentsByLithoCodeId]
@DL_LithoCode_ID INT
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT DataLoadCmnt_ID, DL_LithoCode_ID, DL_Error_ID, CmntNumber, cmntText, bitSubmitted
FROM DL_Comments
WHERE DL_LithoCode_ID = @DL_LithoCode_ID

SET NOCOUNT OFF
SET TRANSACTION ISOLATION LEVEL READ COMMITTED


