CREATE PROCEDURE [dbo].[QSL_SelectHandEntriesByLithoCodeId]
@DL_LithoCode_ID INT
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT DL_HandEntry_ID, DL_LithoCode_ID, DL_Error_ID, QstnCore, ItemNumber, LineNumber, HandEntryText
FROM DL_HandEntry
WHERE DL_LithoCode_ID = @DL_LithoCode_ID

SET NOCOUNT OFF
SET TRANSACTION ISOLATION LEVEL READ COMMITTED


