CREATE PROCEDURE [dbo].[QSL_SelectVoviciSurveyScaleValues]
@Survey_ID INT,
@SampleSet_ID INT
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT b.QSTNCORE, a.QPC_ID AS ScaleID, a.Item, CONVERT(VARCHAR, a.Val) AS Val
FROM DL_SEL_SCLS_BySampleSet a INNER JOIN DL_SEL_QSTNS_BySampleSet b ON a.QPC_ID = b.ScaleId
WHERE a.Survey_Id = @Survey_ID   
	AND b.Survey_Id = @Survey_ID
	AND a.SampleSet_ID = @SampleSet_ID
ORDER BY a.QPC_ID, a.Item

SET NOCOUNT OFF
SET TRANSACTION ISOLATION LEVEL READ COMMITTED


