CREATE PROCEDURE [dbo].[QSL_SelectAllVendorFileTrackings]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT VendorFileTracking_ID, Member_ID, ActionDesc, VendorFile_ID, ActionDate
FROM [dbo].VendorFileTracking

SET NOCOUNT OFF
SET TRANSACTION ISOLATION LEVEL READ COMMITTED


