CREATE PROCEDURE sp_sys_ResetAllPCLGenMachines
AS
DECLARE @SQL VARCHAR (8000)
SET @SQL = ''
SELECT @SQL = @SQL + ' EXEC dbo.sp_PCL_ApplicationErrorReset ''' + COMPUTER_NM + '''' 
FROM (SELECT DISTINCT TOP 100 COMPUTER_NM FROM PCLGENRUN WHERE COMPUTER_NM LIKE 'NRCPCLGEN%' ORDER BY 1 ) T1
EXEC (@SQL)


