CREATE TABLE [dbo].[HCAHPS_bip](
	[QUESTIONFORM_ID] [int] NOT NULL,
	[INTPAGE_NUM] [int] NOT NULL,
	[QSTNCORE] [int] NOT NULL,
	[SURVEY_ID] [int] NOT NULL,
	[ITEM] [int] NOT NULL,
	[SAMPLEUNIT_ID] [int] NOT NULL,
	[VAL] [int] NULL,
	[X_POS] [int] NOT NULL,
	[Y_POS] [int] NOT NULL
) ON [PRIMARY]


