CREATE TABLE [dbo].[s1592April](
	[study_id] [int] NULL,
	[NonDel] [datetime] NULL,
	[datReturned] [datetime] NULL,
	[RetLitho] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[datFirstGen] [datetime] NULL,
	[FirstLitho] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[datSecondGen] [datetime] NULL,
	[SecondLitho] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[datThirdGen] [datetime] NULL,
	[ThirdLitho] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Batch] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[samplepop_id] [int] NOT NULL,
	[sampleset_id] [int] NOT NULL,
	[datsamplecreate_dt] [datetime] NULL,
	[pop_id] [int] NOT NULL,
	[enc_id] [int] NOT NULL,
	[POPULATIONLName] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONFName] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONMiddle] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONAddr] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONCity] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONST] [varchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONZIP5] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONDOB] [datetime] NULL,
	[POPULATIONSex] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONAge] [int] NULL,
	[POPULATIONAddrStat] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONAddrErr] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONZip4] [varchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONNewRecordDate] [datetime] NULL,
	[POPULATIONLangID] [int] NULL,
	[POPULATIONDel_Pt] [varchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONSSN] [varchar](9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONGuarFirstName] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONGuarMiddle] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONGuarLastName] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONGuarAddr] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONGuarCity] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONGuarState] [varchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONGuarZip5] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONPhone] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONVisitNum] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONPHONSTAT] [int] NULL,
	[POPULATIONpop_id] [int] NOT NULL,
	[POPULATIONAreaCode] [varchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONMemberID] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONServiceInd_2] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONServiceInd_3] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONServiceInd_4] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONServiceInd_5] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONServiceInd_6] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONServiceInd_7] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONServiceInd_8] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONDMISID] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONCountry] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONRankName] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONRankNum] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONService] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONBeneficiaryGrp] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONFMP] [int] NULL,
	[POPULATIONAddr2] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONGuarZip4] [varchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONGuarDel_Pt] [varchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONGuarAddrStat] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONGuarAddrErr] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONNameStat] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONGuarNameStat] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONProvince] [varchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONPostal_Code] [varchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONPop_Mtch_Err] [varchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONPop_Mtch] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONService1000] [varchar](1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONService2000] [varchar](1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONHandEntry1] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONHandEntry2] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONHandentry200] [varchar](99) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONWebReturn] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPULATIONPhoneReturn] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENCOUNTERNewRecordDate] [datetime] NULL,
	[ENCOUNTERAdmitSource] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENCOUNTERVisitNum] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENCOUNTERDrSpec] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENCOUNTERClinicName] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENCOUNTERFacilityName] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENCOUNTERServiceDate] [datetime] NULL,
	[ENCOUNTERDrLastName] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENCOUNTERDrFirstName] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENCOUNTERDrMiddleInitial] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENCOUNTERpop_id] [int] NULL,
	[ENCOUNTERenc_id] [int] NOT NULL,
	[ENCOUNTERServiceInd_2] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENCOUNTERServiceInd_9] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENCOUNTERServiceInd_10] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENCOUNTERServiceInd_11] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENCOUNTERServiceInd_12] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENCOUNTERServiceInd_13] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENCOUNTERServiceInd_14] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENCOUNTERServiceInd_15] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENCOUNTERServiceInd_16] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENCOUNTERServiceInd_17] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENCOUNTERServiceInd_18] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENCOUNTERServiceInd_19] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENCOUNTERServiceInd_21] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENCOUNTERServiceInd_22] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENCOUNTERServiceInd_23] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENCOUNTERServiceInd_24] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENCOUNTERDMISID] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENCOUNTERMEPRS3] [varchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENCOUNTERRankNum] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENCOUNTERService] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENCOUNTERMEPRS4] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENCOUNTERDrRank] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENCOUNTERRegion] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENCOUNTERRegionCustom] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENCOUNTERServiceArea] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENCOUNTERDrNameStat] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENCOUNTERServiceInd_35] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENCOUNTEREnc_Mtch_Err] [varchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENCOUNTEREnc_Mtch] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MEPRS3NewRecordDate] [datetime] NULL,
	[MEPRS3ClinicName] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MEPRS3MEPRS3] [varchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MEPRS3MEPRS3_id] [int] NOT NULL,
	[RANKSex] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RANKNewRecordFlag] [int] NULL,
	[RANKNewRecordDate] [datetime] NULL,
	[RANKRankName] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RANKRankNum] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RANKRANK_id] [int] NOT NULL,
	[MTFNewRecordFlag] [int] NULL,
	[MTFNewRecordDate] [datetime] NULL,
	[MTFFacilityName] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MTFDMISID] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MTFMTF_id] [int] NOT NULL
) ON [PRIMARY]


