ALTER TABLE [dbo].[MM_EmailBlast]  WITH CHECK ADD  CONSTRAINT [FK__MM_EmailB__MAILI__5FC086D3] FOREIGN KEY([MAILINGSTEP_ID])
REFERENCES [dbo].[MAILINGSTEP] ([MAILINGSTEP_ID])


GO
ALTER TABLE [dbo].[MM_EmailBlast] CHECK CONSTRAINT [FK__MM_EmailB__MAILI__5FC086D3]

