ALTER TABLE [dbo].[BUSINESSRULE]  WITH CHECK ADD  CONSTRAINT [FK_BUSINESS_REF_18027_STUDY] FOREIGN KEY([STUDY_ID])
REFERENCES [dbo].[STUDY] ([STUDY_ID])


GO
ALTER TABLE [dbo].[BUSINESSRULE] CHECK CONSTRAINT [FK_BUSINESS_REF_18027_STUDY]

