ALTER TABLE [dbo].[CRITERIACLAUSE]  WITH NOCHECK ADD  CONSTRAINT [FK_CRITERIA_REF_1715_METASTRU] FOREIGN KEY([TABLE_ID], [FIELD_ID])
REFERENCES [dbo].[METASTRUCTURE] ([TABLE_ID], [FIELD_ID])


GO
ALTER TABLE [dbo].[CRITERIACLAUSE] CHECK CONSTRAINT [FK_CRITERIA_REF_1715_METASTRU]

