ALTER TABLE [dbo].[CODESCLS]  WITH NOCHECK ADD  CONSTRAINT [FK_CODESCLS_REF_28954_CODES] FOREIGN KEY([CODE])
REFERENCES [dbo].[Codes] ([Code])


GO
ALTER TABLE [dbo].[CODESCLS] CHECK CONSTRAINT [FK_CODESCLS_REF_28954_CODES]

