ALTER TABLE [dbo].[CODEQSTNS]  WITH NOCHECK ADD  CONSTRAINT [FK_CODEQSTN_REF_28910_CODES] FOREIGN KEY([CODE])
REFERENCES [dbo].[Codes] ([Code])


GO
ALTER TABLE [dbo].[CODEQSTNS] CHECK CONSTRAINT [FK_CODEQSTN_REF_28910_CODES]

