ALTER TABLE [dbo].[SURVEY_DEF]  WITH NOCHECK ADD  CONSTRAINT [FK_CutoffTable_id] FOREIGN KEY([cutofftable_id])
REFERENCES [dbo].[METATABLE] ([TABLE_ID])


GO
ALTER TABLE [dbo].[SURVEY_DEF] CHECK CONSTRAINT [FK_CutoffTable_id]

