ALTER TABLE [dbo].[SURVEY_DEF]  WITH NOCHECK ADD  CONSTRAINT [FK_CutoffField_id] FOREIGN KEY([cutofffield_id])
REFERENCES [dbo].[METAFIELD] ([FIELD_ID])


GO
ALTER TABLE [dbo].[SURVEY_DEF] CHECK CONSTRAINT [FK_CutoffField_id]

