ALTER TABLE [dbo].[CODETXTBOX]  WITH NOCHECK ADD  CONSTRAINT [FK_CODETXTB_REF_28941_CODES] FOREIGN KEY([CODE])
REFERENCES [dbo].[Codes] ([Code])


GO
ALTER TABLE [dbo].[CODETXTBOX] CHECK CONSTRAINT [FK_CODETXTB_REF_28941_CODES]

