ALTER TABLE [dbo].[Codes]  WITH CHECK ADD  CONSTRAINT [FK_CODES_REF_9256_LANGUAGE] FOREIGN KEY([LangID])
REFERENCES [dbo].[Languages] ([LangID])


GO
ALTER TABLE [dbo].[Codes] CHECK CONSTRAINT [FK_CODES_REF_9256_LANGUAGE]

