ALTER TABLE [dbo].[CRITERIASTMT]  WITH CHECK ADD  CONSTRAINT [FK_CRITERIA_REF_16400_STUDY] FOREIGN KEY([STUDY_ID])
REFERENCES [dbo].[STUDY] ([STUDY_ID])


GO
ALTER TABLE [dbo].[CRITERIASTMT] CHECK CONSTRAINT [FK_CRITERIA_REF_16400_STUDY]

