ALTER TABLE [dbo].[DATASETMEMBER]  WITH CHECK ADD  CONSTRAINT [FK_DATASETM_REF_10109_DATA_SET] FOREIGN KEY([DATASET_ID])
REFERENCES [dbo].[DATA_SET] ([DATASET_ID])


GO
ALTER TABLE [dbo].[DATASETMEMBER] CHECK CONSTRAINT [FK_DATASETM_REF_10109_DATA_SET]

