ALTER TABLE [dbo].[DATA_SET]  WITH CHECK ADD  CONSTRAINT [FK_DATA_SET_REF_87_STUDY] FOREIGN KEY([STUDY_ID])
REFERENCES [dbo].[STUDY] ([STUDY_ID])


GO
ALTER TABLE [dbo].[DATA_SET] CHECK CONSTRAINT [FK_DATA_SET_REF_87_STUDY]

