ALTER TABLE [dbo].[Period]  WITH NOCHECK ADD  CONSTRAINT [FK_EMPLOYEE_ID] FOREIGN KEY([Employee_id])
REFERENCES [dbo].[EMPLOYEE] ([EMPLOYEE_ID])


GO
ALTER TABLE [dbo].[Period] CHECK CONSTRAINT [FK_EMPLOYEE_ID]

