ALTER TABLE [dbo].[EXPORTDEFAULT]  WITH NOCHECK ADD  CONSTRAINT [FK_EXPORTDE_REF_29833_METAFIEL] FOREIGN KEY([FIELD_ID])
REFERENCES [dbo].[METAFIELD] ([FIELD_ID])


GO
ALTER TABLE [dbo].[EXPORTDEFAULT] CHECK CONSTRAINT [FK_EXPORTDE_REF_29833_METAFIEL]

