ALTER TABLE [dbo].[FormGenError]  WITH CHECK ADD  CONSTRAINT [FK_FORMGENE_REF_43073_FORMGENE] FOREIGN KEY([FGErrorType_id])
REFERENCES [dbo].[FormGenErrorType] ([FGErrorType_id])


GO
ALTER TABLE [dbo].[FormGenError] CHECK CONSTRAINT [FK_FORMGENE_REF_43073_FORMGENE]

