ALTER TABLE [dbo].[SAMPLESET]  WITH NOCHECK ADD  CONSTRAINT [FK_FIELD_ID] FOREIGN KEY([intDateRange_Field_id])
REFERENCES [dbo].[METAFIELD] ([FIELD_ID])


GO
ALTER TABLE [dbo].[SAMPLESET] CHECK CONSTRAINT [FK_FIELD_ID]

