ALTER TABLE [dbo].[HOUSEHOLDRULE]  WITH CHECK ADD  CONSTRAINT [FK_HOUSEHOL_REF_4438_METASTRU] FOREIGN KEY([TABLE_ID], [FIELD_ID])
REFERENCES [dbo].[METASTRUCTURE] ([TABLE_ID], [FIELD_ID])


GO
ALTER TABLE [dbo].[HOUSEHOLDRULE] CHECK CONSTRAINT [FK_HOUSEHOL_REF_4438_METASTRU]

