ALTER TABLE [dbo].[MAILINGSTEP]  WITH CHECK ADD  CONSTRAINT [FK_MAILINGSTEP_MAILINGSTEPMETHOD] FOREIGN KEY([MailingStepMethod_id])
REFERENCES [dbo].[MAILINGSTEPMETHOD] ([MailingStepMethod_id])


GO
ALTER TABLE [dbo].[MAILINGSTEP] CHECK CONSTRAINT [FK_MAILINGSTEP_MAILINGSTEPMETHOD]

