ALTER TABLE [dbo].[METATABLE]  WITH CHECK ADD  CONSTRAINT [FK_METATABL_REF_222_STUDY] FOREIGN KEY([STUDY_ID])
REFERENCES [dbo].[STUDY] ([STUDY_ID])


GO
ALTER TABLE [dbo].[METATABLE] CHECK CONSTRAINT [FK_METATABL_REF_222_STUDY]

