ALTER TABLE [dbo].[MAILINGSTEP]  WITH CHECK ADD  CONSTRAINT [FK_MAILINGS_REF_6482_MAILINGM] FOREIGN KEY([METHODOLOGY_ID])
REFERENCES [dbo].[MAILINGMETHODOLOGY] ([METHODOLOGY_ID])


GO
ALTER TABLE [dbo].[MAILINGSTEP] CHECK CONSTRAINT [FK_MAILINGS_REF_6482_MAILINGM]

