ALTER TABLE [dbo].[PCLGENLOG]  WITH CHECK ADD  CONSTRAINT [FK_PCLGENLOG_PCLGENRUN_ID] FOREIGN KEY([PCLGENRUN_ID])
REFERENCES [dbo].[PCLGENRUN] ([PCLGENRUN_ID])


GO
ALTER TABLE [dbo].[PCLGENLOG] CHECK CONSTRAINT [FK_PCLGENLOG_PCLGENRUN_ID]

