ALTER TABLE [dbo].[PCLGENLOG]  WITH CHECK ADD  CONSTRAINT [FK_PCLGENLOG_SURVEY_ID] FOREIGN KEY([SURVEY_ID])
REFERENCES [dbo].[SURVEY_DEF] ([SURVEY_ID])


GO
ALTER TABLE [dbo].[PCLGENLOG] CHECK CONSTRAINT [FK_PCLGENLOG_SURVEY_ID]

