ALTER TABLE [dbo].[PCLOUTPUT]  WITH CHECK ADD  CONSTRAINT [FK_PCLOUTPU_REF_31743_PAPERSIZ] FOREIGN KEY([PAPERSIZE_ID])
REFERENCES [dbo].[PAPERSIZE] ([PAPERSIZE_ID])


GO
ALTER TABLE [dbo].[PCLOUTPUT] CHECK CONSTRAINT [FK_PCLOUTPU_REF_31743_PAPERSIZ]

