ALTER TABLE [dbo].[QUESTIONFORM]  WITH NOCHECK ADD  CONSTRAINT [FK_QUESTION_REF_31730_CUTOFF] FOREIGN KEY([CUTOFF_ID])
REFERENCES [dbo].[CUTOFF] ([CUTOFF_ID])


GO
ALTER TABLE [dbo].[QUESTIONFORM] CHECK CONSTRAINT [FK_QUESTION_REF_31730_CUTOFF]

