ALTER TABLE [dbo].[QUESTIONFORM]  WITH CHECK ADD  CONSTRAINT [FK_QUESTION_REF_25709_SAMPLEPO] FOREIGN KEY([SAMPLEPOP_ID])
REFERENCES [dbo].[SAMPLEPOP] ([SAMPLEPOP_ID])


GO
ALTER TABLE [dbo].[QUESTIONFORM] CHECK CONSTRAINT [FK_QUESTION_REF_25709_SAMPLEPO]

