ALTER TABLE [dbo].[RECURRINGENCOUNTER]  WITH CHECK ADD  CONSTRAINT [FK_RECURRIN_REF_18798_STUDY] FOREIGN KEY([STUDY_ID])
REFERENCES [dbo].[STUDY] ([STUDY_ID])


GO
ALTER TABLE [dbo].[RECURRINGENCOUNTER] CHECK CONSTRAINT [FK_RECURRIN_REF_18798_STUDY]

