ALTER TABLE [dbo].[SAMPLEUNIT]  WITH NOCHECK ADD  CONSTRAINT [FK_SAMPLEUNIT_REF_2092_SAMPLEPL] FOREIGN KEY([SAMPLEPLAN_ID])
REFERENCES [dbo].[SAMPLEPLAN] ([SAMPLEPLAN_ID])


GO
ALTER TABLE [dbo].[SAMPLEUNIT] CHECK CONSTRAINT [FK_SAMPLEUNIT_REF_2092_SAMPLEPL]

