ALTER TABLE [dbo].[SAMPLEPOP]  WITH CHECK ADD  CONSTRAINT [FK_SAMPLEPO_REF_25695_SAMPLESE] FOREIGN KEY([SAMPLESET_ID])
REFERENCES [dbo].[SAMPLESET] ([SAMPLESET_ID])


GO
ALTER TABLE [dbo].[SAMPLEPOP] CHECK CONSTRAINT [FK_SAMPLEPO_REF_25695_SAMPLESE]

