ALTER TABLE [dbo].[STUDY]  WITH CHECK ADD  CONSTRAINT [FK_STUDY_CLIENT] FOREIGN KEY([CLIENT_ID])
REFERENCES [dbo].[CLIENT] ([CLIENT_ID])


GO
ALTER TABLE [dbo].[STUDY] CHECK CONSTRAINT [FK_STUDY_CLIENT]

