ALTER TABLE [dbo].[STUDYCOMPARISON]  WITH CHECK ADD  CONSTRAINT [FK_STUDYCOM_REF_1414_COMPARIS] FOREIGN KEY([COMPARISONTYPE_ID])
REFERENCES [dbo].[COMPARISONTYPE] ([COMPARISONTYPE_ID])


GO
ALTER TABLE [dbo].[STUDYCOMPARISON] CHECK CONSTRAINT [FK_STUDYCOM_REF_1414_COMPARIS]

