ALTER TABLE [dbo].[Period]  WITH CHECK ADD  CONSTRAINT [FK_SURVEY_ID] FOREIGN KEY([Survey_id])
REFERENCES [dbo].[SURVEY_DEF] ([SURVEY_ID])


GO
ALTER TABLE [dbo].[Period] CHECK CONSTRAINT [FK_SURVEY_ID]

