ALTER TABLE [dbo].[STUDY_EMPLOYEE]  WITH NOCHECK ADD  CONSTRAINT [FK_STUDY_EM_REF_913_EMPLOYEE] FOREIGN KEY([EMPLOYEE_ID])
REFERENCES [dbo].[EMPLOYEE] ([EMPLOYEE_ID])


GO
ALTER TABLE [dbo].[STUDY_EMPLOYEE] CHECK CONSTRAINT [FK_STUDY_EM_REF_913_EMPLOYEE]

