ALTER TABLE [dbo].[SAMPLEDATASET]  WITH CHECK ADD  CONSTRAINT [FK_SAMPLEDA_REF_59316_SAMPLESE] FOREIGN KEY([SAMPLESET_ID])
REFERENCES [dbo].[SAMPLESET] ([SAMPLESET_ID])


GO
ALTER TABLE [dbo].[SAMPLEDATASET] CHECK CONSTRAINT [FK_SAMPLEDA_REF_59316_SAMPLESE]

