ALTER TABLE [dbo].[SURVEY_CONTACT]  WITH CHECK ADD  CONSTRAINT [FK_SURVEY_C_REF_1381_CONTACTT] FOREIGN KEY([CONTACTTYPE_ID])
REFERENCES [dbo].[CONTACTTYPE] ([CONTACTTYPE_ID])


GO
ALTER TABLE [dbo].[SURVEY_CONTACT] CHECK CONSTRAINT [FK_SURVEY_C_REF_1381_CONTACTT]

