ALTER TABLE [dbo].[STUDYREPORTTYPE]  WITH CHECK ADD  CONSTRAINT [FK_STUDYREP_REF_1395_STUDY] FOREIGN KEY([STUDY_ID])
REFERENCES [dbo].[STUDY] ([STUDY_ID])


GO
ALTER TABLE [dbo].[STUDYREPORTTYPE] CHECK CONSTRAINT [FK_STUDYREP_REF_1395_STUDY]

