ALTER TABLE [dbo].[SCHEDULEDMAILING]  WITH CHECK ADD  CONSTRAINT [FK_SCHEDULE_REF_27381_MAILINGS] FOREIGN KEY([MAILINGSTEP_ID])
REFERENCES [dbo].[MAILINGSTEP] ([MAILINGSTEP_ID])


GO
ALTER TABLE [dbo].[SCHEDULEDMAILING] CHECK CONSTRAINT [FK_SCHEDULE_REF_27381_MAILINGS]

