ALTER TABLE [dbo].[STUDYREPORTTYPE]  WITH CHECK ADD  CONSTRAINT [FK_STUDYREP_REF_1403_REPORTTY] FOREIGN KEY([REPORTTYPE_ID])
REFERENCES [dbo].[REPORTTYPE] ([REPORTTYPE_ID])


GO
ALTER TABLE [dbo].[STUDYREPORTTYPE] CHECK CONSTRAINT [FK_STUDYREP_REF_1403_REPORTTY]

