ALTER TABLE [dbo].[STUDY_EMPLOYEE]  WITH CHECK ADD  CONSTRAINT [FK_STUDY_EM_REF_917_STUDY] FOREIGN KEY([STUDY_ID])
REFERENCES [dbo].[STUDY] ([STUDY_ID])


GO
ALTER TABLE [dbo].[STUDY_EMPLOYEE] CHECK CONSTRAINT [FK_STUDY_EM_REF_917_STUDY]

