ALTER TABLE [dbo].[SurveyLanguage]  WITH CHECK ADD  CONSTRAINT [FK_SURVEYLA_REF_13206_LANGUAGE] FOREIGN KEY([LangID])
REFERENCES [dbo].[Languages] ([LangID])


GO
ALTER TABLE [dbo].[SurveyLanguage] CHECK CONSTRAINT [FK_SURVEYLA_REF_13206_LANGUAGE]

