ALTER TABLE [dbo].[SAMPLEUNIT]  WITH CHECK ADD  CONSTRAINT [FK_SAMPLEUN_REF_2096_SAMPLEUN] FOREIGN KEY([PARENTSAMPLEUNIT_ID])
REFERENCES [dbo].[SAMPLEUNIT] ([SAMPLEUNIT_ID])


GO
ALTER TABLE [dbo].[SAMPLEUNIT] CHECK CONSTRAINT [FK_SAMPLEUN_REF_2096_SAMPLEUN]

