ALTER TABLE [dbo].[SCHEDULEDMAILING]  WITH CHECK ADD  CONSTRAINT [FK_SCHEDULE_REF_27389_SAMPLEPO] FOREIGN KEY([SAMPLEPOP_ID])
REFERENCES [dbo].[SAMPLEPOP] ([SAMPLEPOP_ID])


GO
ALTER TABLE [dbo].[SCHEDULEDMAILING] CHECK CONSTRAINT [FK_SCHEDULE_REF_27389_SAMPLEPO]

