ALTER TABLE [dbo].[SURVEY_CONTACT]  WITH CHECK ADD  CONSTRAINT [FK_SURVEY_C_REF_1376_CLIENT_C] FOREIGN KEY([CONTACT_ID])
REFERENCES [dbo].[CLIENT_CONTACT] ([CONTACT_ID])


GO
ALTER TABLE [dbo].[SURVEY_CONTACT] CHECK CONSTRAINT [FK_SURVEY_C_REF_1376_CLIENT_C]

