ALTER TABLE [dbo].[STUDYCOMPARISON]  WITH CHECK ADD  CONSTRAINT [FK_STUDYCOM_REF_2941_MSA] FOREIGN KEY([MKTGUIDE_MSA_ID])
REFERENCES [dbo].[MSA] ([MSA_ID])


GO
ALTER TABLE [dbo].[STUDYCOMPARISON] CHECK CONSTRAINT [FK_STUDYCOM_REF_2941_MSA]

