ALTER TABLE [dbo].[SCHEDULEDMAILING]  WITH CHECK ADD  CONSTRAINT [FK_SCHEDULE_REF_28155_OVERRIDE] FOREIGN KEY([OVERRIDEITEM_ID])
REFERENCES [dbo].[OVERRIDEITEM] ([OVERRIDEITEM_ID])


GO
ALTER TABLE [dbo].[SCHEDULEDMAILING] CHECK CONSTRAINT [FK_SCHEDULE_REF_28155_OVERRIDE]

