ALTER TABLE [dbo].[SAMPLEPLAN]  WITH NOCHECK ADD  CONSTRAINT [FK_SAMPLEPL_REF_2083_EMPLOYEE] FOREIGN KEY([EMPLOYEE_ID])
REFERENCES [dbo].[EMPLOYEE] ([EMPLOYEE_ID])


GO
ALTER TABLE [dbo].[SAMPLEPLAN] CHECK CONSTRAINT [FK_SAMPLEPL_REF_2083_EMPLOYEE]

