ALTER TABLE [dbo].[SAMPLEUNIT]  WITH NOCHECK ADD  CONSTRAINT [FK_SampleUnitHierarchy] FOREIGN KEY([REPORTING_HIERARCHY_ID])
REFERENCES [dbo].[REPORTINGHIERARCHY] ([REPORTING_HIERARCHY_ID])


GO
ALTER TABLE [dbo].[SAMPLEUNIT] CHECK CONSTRAINT [FK_SampleUnitHierarchy]

