ALTER TABLE [dbo].[STUDYDELIVERYDATE]  WITH CHECK ADD  CONSTRAINT [FK_STUDYDEL_REF_39410_CLIENT_C] FOREIGN KEY([CONTACT_ID])
REFERENCES [dbo].[CLIENT_CONTACT] ([CONTACT_ID])


GO
ALTER TABLE [dbo].[STUDYDELIVERYDATE] CHECK CONSTRAINT [FK_STUDYDEL_REF_39410_CLIENT_C]

