ALTER TABLE [dbo].[TAGEXCEPTION]  WITH CHECK ADD  CONSTRAINT [FK_TAGEXCEP_REF_53237_TAG] FOREIGN KEY([TAG_ID])
REFERENCES [dbo].[TAG] ([TAG_ID])


GO
ALTER TABLE [dbo].[TAGEXCEPTION] CHECK CONSTRAINT [FK_TAGEXCEP_REF_53237_TAG]

