ALTER TABLE [dbo].[SAMPLESET]  WITH CHECK ADD  CONSTRAINT [FK_TABLE_ID] FOREIGN KEY([intDateRange_Table_id])
REFERENCES [dbo].[METATABLE] ([TABLE_ID])


GO
ALTER TABLE [dbo].[SAMPLESET] CHECK CONSTRAINT [FK_TABLE_ID]

