ALTER TABLE [dbo].[TAGEXCEPTION]  WITH CHECK ADD  CONSTRAINT [FK_TAGEXCEP_REF_53241_METASTRU] FOREIGN KEY([TABLE_ID], [FIELD_ID])
REFERENCES [dbo].[METASTRUCTURE] ([TABLE_ID], [FIELD_ID])


GO
ALTER TABLE [dbo].[TAGEXCEPTION] CHECK CONSTRAINT [FK_TAGEXCEP_REF_53241_METASTRU]

