ALTER TABLE [dbo].[TOCL]  WITH CHECK ADD  CONSTRAINT [FK_TOCL_REF_7002_STUDY] FOREIGN KEY([STUDY_ID])
REFERENCES [dbo].[STUDY] ([STUDY_ID])


GO
ALTER TABLE [dbo].[TOCL] CHECK CONSTRAINT [FK_TOCL_REF_7002_STUDY]

