ALTER TABLE [dbo].[TAGFIELD]  WITH CHECK ADD  CONSTRAINT [FK_TAGFIELD_REF_38365_STUDY] FOREIGN KEY([STUDY_ID])
REFERENCES [dbo].[STUDY] ([STUDY_ID])


GO
ALTER TABLE [dbo].[TAGFIELD] CHECK CONSTRAINT [FK_TAGFIELD_REF_38365_STUDY]

