'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2443
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2443.
'
Namespace dqwsGeoCodeCheck
    
    '<remarks/>
    'CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="BasicHttpBinding_IService", [Namespace]:="urn:MelissaDataGeoCodeService")>  _
    Public Class Service
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "https://geocoder.melissadata.net/v2/SOAP/Service.svc"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:MelissaDataGeoCodeService/IService/doGeoCode", RequestNamespace:="urn:MelissaDataGeoCodeService", ResponseNamespace:="urn:MelissaDataGeoCodeService", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function doGeoCode(ByVal Request As RequestArray) As ResponseArray
            Dim results() As Object = Me.Invoke("doGeoCode", New Object() {Request})
            Return CType(results(0),ResponseArray)
        End Function
        
        '<remarks/>
        Public Function BegindoGeoCode(ByVal Request As RequestArray, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("doGeoCode", New Object() {Request}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EnddoGeoCode(ByVal asyncResult As System.IAsyncResult) As ResponseArray
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ResponseArray)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:mdWebServiceGeoCode")>  _
    Public Class RequestArray
        
        '<remarks/>
        Public TransmissionReference As String
        
        '<remarks/>
        Public CustomerID As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Record")>  _
        Public Record() As RequestArrayRecord
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:mdWebServiceGeoCode")>  _
    Public Class RequestArrayRecord
        
        '<remarks/>
        Public RecordID As String
        
        '<remarks/>
        Public AddressKey As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:mdWebServiceGeoCode")>  _
    Public Class ResponseArrayRecordAddressCensus
        
        '<remarks/>
        Public Block As String
        
        '<remarks/>
        Public Tract As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:mdWebServiceGeoCode")>  _
    Public Class ResponseArrayRecordAddressCBSA
        
        '<remarks/>
        Public Code As String
        
        '<remarks/>
        Public Title As String
        
        '<remarks/>
        Public Level As String
        
        '<remarks/>
        Public CBSADivisionCode As String
        
        '<remarks/>
        Public CBSADivisionTitle As String
        
        '<remarks/>
        Public CBSADivisionLevel As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:mdWebServiceGeoCode")>  _
    Public Class ResponseArrayRecordAddressTimeZone
        
        '<remarks/>
        Public Name As String
        
        '<remarks/>
        Public Code As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:mdWebServiceGeoCode")>  _
    Public Class ResponseArrayRecordAddressPlace
        
        '<remarks/>
        Public Code As String
        
        '<remarks/>
        Public Name As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:mdWebServiceGeoCode")>  _
    Public Class ResponseArrayRecordAddressCounty
        
        '<remarks/>
        Public Name As String
        
        '<remarks/>
        Public Fips As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:mdWebServiceGeoCode")>  _
    Public Class ResponseArrayRecordAddress
        
        '<remarks/>
        Public County As ResponseArrayRecordAddressCounty
        
        '<remarks/>
        Public Latitude As String
        
        '<remarks/>
        Public Longitude As String
        
        '<remarks/>
        Public Place As ResponseArrayRecordAddressPlace
        
        '<remarks/>
        Public TimeZone As ResponseArrayRecordAddressTimeZone
        
        '<remarks/>
        Public CBSA As ResponseArrayRecordAddressCBSA
        
        '<remarks/>
        Public Census As ResponseArrayRecordAddressCensus
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:mdWebServiceGeoCode")>  _
    Public Class ResponseArrayRecord
        
        '<remarks/>
        Public RecordID As String
        
        '<remarks/>
        Public Results As String
        
        '<remarks/>
        Public Address As ResponseArrayRecordAddress
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:mdWebServiceGeoCode")>  _
    Public Class ResponseArray
        
        '<remarks/>
        Public Version As String
        
        '<remarks/>
        Public TransmissionReference As String
        
        '<remarks/>
        Public Results As String
        
        '<remarks/>
        Public TotalRecords As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Record")>  _
        Public Record() As ResponseArrayRecord
    End Class
End Namespace
