CREATE TABLE [dbo].[allunits](
	[CLIENT_ID] [float] NULL,
	[DATEFIELD] [nvarchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AP_ID] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COMPONENTA] [float] NULL,
	[COMPONENTB] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CORR_VAR] [float] NULL,
	[CORRELATIO] [float] NULL,
	[ENDDATE] [float] NULL,
	[PAGE_NUMBE] [float] NULL,
	[STARTDATE] [float] NULL,
	[STRGROUPIN] [nvarchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STRMEASURE] [nvarchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TIME_TYPE] [float] NULL,
	[COLUMN_NBR] [float] NULL,
	[CMPR_NUM] [float] NULL,
	[QUEST_OR_T] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[THEME_ID] [float] NULL,
	[GROUPING_O] [nvarchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MEASURE_OV] [nvarchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SEQ_NUMBER] [float] NULL,
	[STRDATAPOI] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NUMCONTROL] [float] NULL,
	[DTILASTDAT] [float] NULL,
	[PAGE_SECTI] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DTIMEANTIA] [float] NULL,
	[DTIMEANTIB] [float] NULL,
	[NUMCONFIDE] [float] NULL,
	[STACKED_BA] [float] NULL,
	[NUMBREAKOU] [float] NULL,
	[QUEST_RESP] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[QSTNCORE] [float] NULL,
	[SAMPLEPOP_] [float] NULL,
	[SAMPLEUNIT] [float] NULL,
	[SCALEID] [float] NULL,
	[SCALEORDER] [float] NULL,
	[MAX_SCALEO] [float] NULL,
	[VAL] [float] NULL,
	[ITEM] [float] NULL,
	[RESULT_DAT] [float] NULL,
	[SURVEY_ID] [float] NULL,
	[STUDY_ID] [float] NULL,
	[RB_WEIGHT] [float] NULL,
	[THEME] [float] NULL
) ON [PRIMARY]


