CREATE TABLE [dbo].[Billians_NursingHomes](
	[Directory Code] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Name] [nvarchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Former Name] [nvarchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Memo Line] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Street Address] [nvarchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Mail Address] [nvarchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[City] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[State] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Street Zip] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Mail Zip] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[County] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Phone] [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Fax] [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[800 Number] [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Website] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[General Facility Email] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Freestanding/Hospital Based] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[System Type] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Government Owned] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Owned By (non corporate)] [nvarchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Food Services Contract] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Environmental Services Contract] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Non-Reporting] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[New NH] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Date Closed] [nvarchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Non-Count] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Medicare Provider Number1] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Medicare Provider Number2] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Medicare Provider Number3] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Medicare Provider Number4] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Medicare Provider Number5] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Total Beds] [int] NULL,
	[Private Beds] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Medicare Beds] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Medicaid Beds] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Sub-Acute Beds] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Alzheimers Beds] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Assisted Living Care] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Extended Care] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Intermediate Care] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Development Disability Intermediate Care] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Long-Term Care] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Nursing Home Care] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Residential Care] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Personal Care] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Skilled Nursing Care] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Transitional Care] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Latitude] [float] NULL,
	[Longitude] [float] NULL,
	[FIPS County] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MSA] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MSA Description] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_Billians_NursingHomes] PRIMARY KEY CLUSTERED 
(
	[Directory Code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]


