CREATE TABLE [dbo].[BUBBLEPOS](
	[QUESTIONFORM_ID] [int] NOT NULL,
	[SAMPLEUNIT_ID] [int] NOT NULL,
	[INTPAGE_NUM] [int] NOT NULL,
	[QSTNCORE] [int] NOT NULL,
	[INTBEGCOLUMN] [int] NULL,
	[READMETHOD_ID] [int] NULL,
	[INTRESPCOL] [int] NOT NULL
) ON [PRIMARY]


