if object_id('BubbleItemPos','U') is not null
	drop table [dbo].[BUBBLEITEMPOS]
/*
CREATE TABLE [dbo].[BUBBLEITEMPOS](
	[QUESTIONFORM_ID] [int] NOT NULL,
	[INTPAGE_NUM] [int] NOT NULL,
	[QSTNCORE] [int] NOT NULL,
	[SURVEY_ID] [int] NOT NULL,
	[ITEM] [int] NOT NULL,
	[SAMPLEUNIT_ID] [int] NOT NULL,
	[VAL] [int] NULL,
	[X_POS] [int] NOT NULL,
	[Y_POS] [int] NOT NULL,
 CONSTRAINT [PK_BUBBLEITEMPOS] PRIMARY KEY CLUSTERED 
(
	[QUESTIONFORM_ID] ASC,
	[INTPAGE_NUM] ASC,
	[QSTNCORE] ASC,
	[SURVEY_ID] ASC,
	[ITEM] ASC,
	[SAMPLEUNIT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
*/