CREATE TABLE [dbo].[BUSINESSRULE_HISTORY](
	[BUSINESSRULE_ID] [int] NOT NULL,
	[BUSRULE_CD] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[STUDY_ID] [int] NULL,
	[SURVEY_ID] [int] NOT NULL,
	[STRCRITERIASTMT_NM] [char](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[strCriteriaString] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]


