CREATE TABLE [dbo].[BUSINESSRULE](
	[BUSINESSRULE_ID] [int] IDENTITY(1,1) NOT NULL,
	[SURVEY_ID] [int] NOT NULL,
	[STUDY_ID] [int] NULL,
	[CRITERIASTMT_ID] [int] NULL,
	[BUSRULE_CD] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
 CONSTRAINT [PK_BUSINESSRULE] PRIMARY KEY CLUSTERED 
(
	[BUSINESSRULE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]


