CREATE TABLE [dbo].[CANADA_SAMPLEUNITCLASSES_Data](
	[STRCLIENT_NM] [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CLIENT_ID] [int] NOT NULL,
	[STRSTUDY_NM] [char](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[STUDY_ID] [int] NOT NULL,
	[STRSURVEY_NM] [char](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[SURVEY_ID] [int] NOT NULL,
	[Sampleunit_id] [int] NULL,
	[strSampleUnit_nm] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[datLastUpdated] [datetime] NULL,
	[intTier] [int] NULL,
	[intTreeOrder] [int] NULL,
	[SUFacility_id] [int] NULL,
	[strFacility_nm] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Emp(8)] [int] NULL,
	[ER(3)] [int] NULL,
	[ER-Peds(78)] [int] NULL,
	[ER-UrgentCare(70)] [int] NULL,
	[HH(5)] [int] NULL,
	[IP(1)] [int] NULL,
	[IP-Burns(77)] [int] NULL,
	[IP-Cardiology(15)] [int] NULL,
	[IP-Dietary(22)] [int] NULL,
	[IP-GYN(75)] [int] NULL,
	[IP-ICU(21)] [int] NULL,
	[IP-Lab(19)] [int] NULL,
	[IP-Labor/Delivery(13)] [int] NULL,
	[IP-Med(10)] [int] NULL,
	[IP-Neuro(74)] [int] NULL,
	[IP-Oncology(16)] [int] NULL,
	[IP-Orthopedics(18)] [int] NULL,
	[IP-Other(24)] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IP-PainCenter(23)] [int] NULL,
	[IP-Peds(14)] [int] NULL,
	[IP-Psych(76)] [int] NULL,
	[IP-Rad(20)] [int] NULL,
	[IP-RehabTherapy(17)] [int] NULL,
	[IP-Surg(11)] [int] NULL,
	[LongTermCare(79)] [int] NULL,
	[LongTermCare-CCC(80)] [int] NULL,
	[LongTermCare-LTC(81)] [int] NULL,
	[Member(9)] [int] NULL,
	[N/A(0)] [int] NULL,
	[OP(2)] [int] NULL,
	[OP-CardiacRehab(31)] [int] NULL,
	[OP-Cardiology(28)] [int] NULL,
	[OP-CathLab(33)] [int] NULL,
	[OP-Dietary(36)] [int] NULL,
	[OP-Endoscopy(26)] [int] NULL,
	[OP-Lab(34)] [int] NULL,
	[OP-OccuTherapy(69)] [int] NULL,
	[OP-Oncology(29)] [int] NULL,
	[OP-Orthopedics(30)] [int] NULL,
	[OP-Other(39)] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OP-PainCenter(37)] [int] NULL,
	[OP-Peds(27)] [int] NULL,
	[OP-PhysicalTherapy(68)] [int] NULL,
	[OP-PulmonaryRehab(32)] [int] NULL,
	[OP-Rad(35)] [int] NULL,
	[OP-Rehab(40)] [int] NULL,
	[OP-Services(41)] [int] NULL,
	[OP-Surg(25)] [int] NULL,
	[Other(72)] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Other-Other(73)] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Phys(7)] [int] NULL,
	[POV(6)] [int] NULL,
	[POV-Audiology(47)] [int] NULL,
	[POV-Cardiology(43)] [int] NULL,
	[POV-Complementary Medicine(63)] [int] NULL,
	[POV-Dental General(53)] [int] NULL,
	[POV-Diabetes(44)] [int] NULL,
	[POV-ENT(46)] [int] NULL,
	[POV-Family Medicine(54)] [int] NULL,
	[POV-General Pediatrics(56)] [int] NULL,
	[POV-General Surgery(50)] [int] NULL,
	[POV-GYN Womens Health(55)] [int] NULL,
	[POV-Health Education(62)] [int] NULL,
	[POV-Internal Medicine(42)] [int] NULL,
	[POV-Mammography(65)] [int] NULL,
	[POV-Mental Health(57)] [int] NULL,
	[POV-Neurology(45)] [int] NULL,
	[POV-Nutrition(58)] [int] NULL,
	[POV-Oncology(49)] [int] NULL,
	[POV-Ophthalmology(48)] [int] NULL,
	[POV-Optometry(60)] [int] NULL,
	[POV-Orthopedics(52)] [int] NULL,
	[POV-Other(67)] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POV-Physiotherapy(59)] [int] NULL,
	[POV-Social Services(61)] [int] NULL,
	[POV-Traditional Healing(64)] [int] NULL,
	[POV-Ultrasound/Radiology(66)] [int] NULL,
	[POV-UrgentCare(71)] [int] NULL,
	[POV-Urology(51)] [int] NULL
) ON [PRIMARY]


