CREATE TABLE [dbo].[CLIENT](
	[CLIENT_ID] [int] IDENTITY(1,1) NOT NULL,
	[STRCLIENT_NM] [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Active] [bit] NULL CONSTRAINT [DF_CLIENT_Active]  DEFAULT ((1)),
	[ClientGroup_ID] [int] NULL,
 CONSTRAINT [PK_CLIENT] PRIMARY KEY NONCLUSTERED 
(
	[CLIENT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]


