CREATE TABLE [dbo].[CODESTEXT](
	[CodeText_id] [int] IDENTITY(1,1) NOT NULL,
	[Code] [int] NOT NULL,
	[Age] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Sex] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Doctor] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[QPC_Text] [varchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_CODESTEXT] PRIMARY KEY CLUSTERED 
(
	[CodeText_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]


