CREATE TABLE [dbo].[CODETEXTTAG](
	[CODETEXT_ID] [int] NOT NULL,
	[TAG_ID] [int] NOT NULL,
	[INTSTARTPOS] [int] NOT NULL,
	[INTLENGTH] [int] NOT NULL,
 CONSTRAINT [PK_CODETEXTTAG] PRIMARY KEY CLUSTERED 
(
	[CODETEXT_ID] ASC,
	[TAG_ID] ASC,
	[INTSTARTPOS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]


