if object_id('COMMENTLINEPOS','U') is not null
	drop table [dbo].[COMMENTLINEPOS]
/*
CREATE TABLE [dbo].[COMMENTLINEPOS](
	[QUESTIONFORM_ID] [int] NOT NULL,
	[INTPAGE_NUM] [int] NOT NULL,
	[CMNTBOX_ID] [int] NOT NULL,
	[INTLINE_NUM] [int] NOT NULL,
	[SAMPLEUNIT_ID] [int] NOT NULL,
	[X_POS] [int] NOT NULL,
	[Y_POS] [int] NOT NULL,
	[INTWIDTH] [int] NOT NULL,
	[INTHEIGHT] [int] NOT NULL,
 CONSTRAINT [PK_COMMENTLINEPOS] PRIMARY KEY CLUSTERED 
(
	[QUESTIONFORM_ID] ASC,
	[INTPAGE_NUM] ASC,
	[CMNTBOX_ID] ASC,
	[INTLINE_NUM] ASC,
	[SAMPLEUNIT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
*/