CREATE TABLE [dbo].[COMMENTCOPYTYPE](
	[COMMENTCOPYTYPE_CD] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
 CONSTRAINT [PK_COMMENTCOPYTYPE] PRIMARY KEY CLUSTERED 
(
	[COMMENTCOPYTYPE_CD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]


