CREATE TABLE [dbo].[CRITERIAINLIST](
	[CRITERIAINLIST_ID] [int] IDENTITY(1,1) NOT NULL,
	[CRITERIACLAUSE_ID] [int] NULL,
	[STRLISTVALUE] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
 CONSTRAINT [PK_CRITERIAINLIST] PRIMARY KEY CLUSTERED 
(
	[CRITERIAINLIST_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]


