CREATE TABLE [dbo].[CriteriaInList_bkup_INC0028553](
	[CRITERIAINLIST_ID] [int] IDENTITY(1,1) NOT NULL,
	[CRITERIACLAUSE_ID] [int] NULL,
	[STRLISTVALUE] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]


