CREATE TABLE [dbo].[CriteriaStmt_bkup_INC0028553](
	[CRITERIASTMT_ID] [int] IDENTITY(1,1) NOT NULL,
	[STUDY_ID] [int] NULL,
	[STRCRITERIASTMT_NM] [char](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[strCriteriaString] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]


