CREATE TABLE [dbo].[CRITERIASTMT](
	[CRITERIASTMT_ID] [int] IDENTITY(1,1) NOT NULL,
	[STUDY_ID] [int] NULL,
	[STRCRITERIASTMT_NM] [char](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[strCriteriaString] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_CRITERIASTMT] PRIMARY KEY CLUSTERED 
(
	[CRITERIASTMT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]


