CREATE TABLE [dbo].[CRITERIACLAUSE](
	[CRITERIACLAUSE_ID] [int] IDENTITY(1,1) NOT NULL,
	[CRITERIAPHRASE_ID] [int] NOT NULL,
	[CRITERIASTMT_ID] [int] NULL,
	[TABLE_ID] [int] NOT NULL,
	[FIELD_ID] [int] NOT NULL,
	[INTOPERATOR] [int] NULL,
	[STRLOWVALUE] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STRHIGHVALUE] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_CRITERIACLAUSE] PRIMARY KEY CLUSTERED 
(
	[CRITERIACLAUSE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]


