CREATE TABLE [dbo].[CultureToLanguages](
	[CultureLangID] [int] IDENTITY(1,1) NOT NULL,
	[CultureID] [int] NOT NULL,
	[LangID] [int] NOT NULL,
 CONSTRAINT [PK_CultureToLanguages_1] PRIMARY KEY CLUSTERED 
(
	[CultureLangID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


