CREATE TABLE [dbo].[CUTOFF](
	[CUTOFF_ID] [int] IDENTITY(1,1) NOT NULL,
	[SURVEY_ID] [int] NOT NULL,
	[DATCUTOFFDATE] [datetime] NOT NULL,
	[EMPLOYEE_ID] [int] NOT NULL,
	[DatCutoffStart_DT] [datetime] NULL,
	[DatCutoffStop_DT] [datetime] NULL,
	[BitExecutingCutoff] [bit] NOT NULL CONSTRAINT [DF_CUTOFF_BitExecutingCutoff]  DEFAULT (0),
	[ExportCount] [int] NULL,
 CONSTRAINT [PK_CUTOFF] PRIMARY KEY CLUSTERED 
(
	[CUTOFF_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]


