CREATE TABLE [dbo].[DATA_SET](
	[DATASET_ID] [int] IDENTITY(1,1) NOT NULL,
	[STUDY_ID] [int] NULL,
	[DATLOAD_DT] [datetime] NULL,
	[INTGOOD_RECS] [int] NULL,
	[INTBAD_RECS] [int] NULL,
	[INTADDRNOCHG] [int] NULL,
	[INTADDRCLEANED] [int] NULL,
	[INTADDRERROR] [int] NULL,
	[RecordCount] [int] NULL,
	[DATAPPLY_DT] [datetime] NULL,
 CONSTRAINT [PK_DATA_SET] PRIMARY KEY CLUSTERED 
(
	[DATASET_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]


