CREATE TABLE [dbo].[DatabaseBOB](
	[DISPOSTN] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[METHOD] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UNDEL_DT] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SAMPPOP] [float] NULL,
	[SAMPUNIT] [float] NULL,
	[UNIT_NM] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MEDICARE] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HCAHPS] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SAMPSET] [float] NULL,
	[REPORTDT] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SAMPTYPE] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SAMP_DT] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LITHOCD] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DYFRFRST] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DYFRCUR] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RTRN_DT] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COMPLETE] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADDR] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADDR2] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADDRERR] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADDRSTAT] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADMTDATE] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADMTSRC] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AGE] [float] NULL,
	[AGEGROUP] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AREACODE] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CITY] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CPT4] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CPT4_10] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CPT4_2] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CPT4_3] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CPT4_4] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CPT4_5] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CPT4_6] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CPT4_7] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CPT4_8] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CPT4_9] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEL_PT] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DISDATE] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DISDEST] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DISSTAT] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DISUNIT] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DOB] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DRG] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DRID] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DRSPEC] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EMPLOYER] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENC_ID] [float] NULL,
	[ENC_MTCH] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ETHNIC] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FACNUM] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FINCLASS] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FNAME] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GENDER] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HCAHPADM] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HCAHPAGE] [float] NULL,
	[HCAHPSAG] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HCAHPDIS] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HCAHPSER] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HCAHPVIS] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ICD9] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ICD9_10] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ICD9_2] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ICD9_3] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ICD9_4] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ICD9_5] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ICD9_6] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ICD9_7] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ICD9_8] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ICD9_9] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LANGID] [float] NULL,
	[HCLANG] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOS] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LNAME] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MARITAL] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MIDDLE] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MRN] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NAMESTAT] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NEWDATE] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PHONE] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PHONSTAT] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POP_ID] [float] NULL,
	[POP_MTCH] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POSTCODE] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PRIMDX] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PROVINCE] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RACE] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SERDATE] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SERVICE3] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SERVICE1] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SEX] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SP_DAY] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SP_MONTH] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SP_YEAR] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ST] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VISITNUM] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VISTYPE] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZIP4] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZIP5] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]


