CREATE TABLE [dbo].[dbg_temp_restore_vendorphonefile_data](
	[_tbl_nm] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[vendorfile_data_id] [int] NOT NULL,
	[vendorfile_id] [int] NULL,
	[hcahpssamp] [int] NULL,
	[litho] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[survey_id] [int] NULL,
	[sampleset_id] [int] NULL,
	[phone] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[altphone] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[fname] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[lname] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[addr] [varchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[addr2] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[city] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[st] [varchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[zip5] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[phservdate] [datetime] NULL,
	[langid] [int] NULL,
	[telematch] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[phfacname] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[phservind1] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[phservind2] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[phservind3] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[phservind4] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[phservind5] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[phservind6] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[phservind7] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[phservind8] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[phservind9] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[phservind10] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[phservind11] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[phservind12] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]


