CREATE TABLE [dbo].[dc_badAlgorithms](
	[SURVEY_ID] [int] IDENTITY(1,1) NOT NULL,
	[STUDY_ID] [int] NOT NULL,
	[STRSURVEY_NM] [char](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[STRSURVEY_DSC] [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INTRESPONSE_RECALC_PERIOD] [int] NOT NULL,
	[INTRESURVEY_PERIOD] [int] NULL,
	[BITREPEATINGENCOUNTERS_FLG] [bit] NOT NULL,
	[BITPHYSASSIST_NAME_FLG] [bit] NOT NULL,
	[BITMINOR_EXCEPT_FLG] [bit] NOT NULL,
	[BITNEWBORN_FLG] [bit] NOT NULL,
	[DATSURVEY_START_DT] [datetime] NULL,
	[DATSURVEY_END_DT] [datetime] NULL,
	[STRMAILFREQ] [char](9) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[INTSAMPLESINPERIOD] [int] NOT NULL,
	[STRXMITROUTE] [char](16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BITUSECOMMENTS] [bit] NOT NULL,
	[STRCMNTCOPYTYPE] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STRCMNTSORT] [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BITSENDCMNTOUT] [bit] NOT NULL,
	[STRSPECIALINSTRUCTIONS] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STRCMNTMAILFREQ] [char](9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STRCMNTCARRIER] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STROTHERINSTRUCTIONS] [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STRCMNTTYPING_DBVER] [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BITCMNTTYPING_ONDISK] [bit] NOT NULL,
	[STRCMNT_CMNT] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BITVALIDATED_FLG] [bit] NOT NULL,
	[DATVALIDATED] [datetime] NULL,
	[BITFORMGENRELEASE] [bit] NOT NULL,
	[BITLAYOUTVALID] [bit] NOT NULL,
	[BITDYNAMIC] [bit] NOT NULL,
	[STRCUTOFFRESPONSE_CD] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[cutofftable_id] [int] NULL,
	[cutofffield_id] [int] NULL,
	[strHouseholdingType] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[bitDoHousehold] [bit] NOT NULL,
	[vcHouseholding] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[intQuarter] [int] NULL,
	[weighttype] [tinyint] NOT NULL,
	[bitmultreturns] [bit] NULL,
	[Priority_Flg] [tinyint] NULL,
	[bitEnforceSkip] [bit] NULL,
	[strclientfacingName] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SurveyType_id] [int] NULL,
	[MedicareNumber] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AHANumber] [int] NULL,
	[SurveyTypeDef_id] [int] NULL,
	[datHCAHPSReportable] [datetime] NULL,
	[ReSurveyMethod_id] [int] NOT NULL,
	[SamplingAlgorithmID] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]


