CREATE TABLE [dbo].[djk_wo69976](
	[POP_ID] [int] NULL,
	[CLINTYPE] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CLINICAL_NUM] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CLINICAL_NM] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NONCLINICAL_NUM] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NONCLINICAL_NM] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]


