CREATE TABLE [dbo].[DL_BadLithos](
	[BadLitho_ID] [int] IDENTITY(1,1) NOT NULL,
	[DataLoad_ID] [int] NULL,
	[BadstrLithoCode] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DateCreated] [datetime] NULL CONSTRAINT [DF_DL_BadLithos_DateCreated]  DEFAULT (getdate()),
 CONSTRAINT [PK_DL_BadLithos] PRIMARY KEY CLUSTERED 
(
	[BadLitho_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]


