CREATE TABLE [dbo].[DL_Comments](
	[DataLoadCmnt_ID] [int] IDENTITY(1,1) NOT NULL,
	[DL_LithoCode_ID] [int] NOT NULL,
	[DL_Error_ID] [int] NULL,
	[CmntNumber] [int] NULL,
	[cmntText] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[bitSubmitted] [bit] NULL,
 CONSTRAINT [PK_DL_Comments] PRIMARY KEY CLUSTERED 
(
	[DataLoadCmnt_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]


