CREATE TABLE [dbo].[DL_ErrorCodes](
	[DL_Error_ID] [int] IDENTITY(1,1) NOT NULL,
	[ErrorDesc] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DateCreated] [datetime] NULL,
 CONSTRAINT [PK_DL_ErrorCodes] PRIMARY KEY CLUSTERED 
(
	[DL_Error_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


