CREATE TABLE [dbo].[DL_PopMapping](
	[DL_PopMapping_ID] [int] IDENTITY(1,1) NOT NULL,
	[DL_LithoCode_ID] [int] NULL,
	[DL_Error_ID] [int] NULL,
	[QstnCore] [int] NULL,
	[PopMappingText] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_DL_PopMapping] PRIMARY KEY CLUSTERED 
(
	[DL_PopMapping_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]


