CREATE TABLE [dbo].[drm_questionresult_inc0023912](
	[QUESTIONRESULT_ID] [int] IDENTITY(1,1) NOT NULL,
	[QUESTIONFORM_ID] [int] NOT NULL,
	[SAMPLEUNIT_ID] [int] NOT NULL,
	[QSTNCORE] [int] NOT NULL,
	[INTRESPONSEVAL] [int] NOT NULL,
	[QPC_TIMESTAMP] [timestamp] NULL
) ON [PRIMARY]


