CREATE TABLE [dbo].[drm_BUSINESSRULE_INC0028463](
	[BUSINESSRULE_ID] [int] IDENTITY(1,1) NOT NULL,
	[SURVEY_ID] [int] NOT NULL,
	[STUDY_ID] [int] NULL,
	[CRITERIASTMT_ID] [int] NULL,
	[BUSRULE_CD] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]


