CREATE TABLE [dbo].[EMPLOYEE](
	[EMPLOYEE_ID] [int] IDENTITY(1,1) NOT NULL,
	[STREMPLOYEE_FIRST_NM] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[STREMPLOYEE_LAST_NM] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[STREMPLOYEE_TITLE] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STRNTLOGIN_NM] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[strPhoneExt] [char](5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[strEmail] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[FullAccess] [bit] NULL CONSTRAINT [DF__Employee__FullAc__54F67D98]  DEFAULT (0),
	[Dashboard_FullAccess] [bit] NULL CONSTRAINT [DF_EMPLOYEE_Dashboard_FullAccess]  DEFAULT (0),
	[bitActive] [bit] NULL CONSTRAINT [DF_EMPLOYEE_bitActive]  DEFAULT (1),
	[role_id] [int] NULL CONSTRAINT [DF_EMPLOYEE_role_id]  DEFAULT (0),
	[Country_id] [int] NOT NULL CONSTRAINT [DF__Employee__Countr__5BE9C4A3]  DEFAULT (1),
 CONSTRAINT [PK_EMPLOYEE] PRIMARY KEY CLUSTERED 
(
	[EMPLOYEE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]


