CREATE TABLE [dbo].[FormGenErrorType](
	[FGErrorType_id] [int] NOT NULL,
	[FGErrorType_dsc] [varchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
 CONSTRAINT [PK_FORMGENERRORTYPE] PRIMARY KEY NONCLUSTERED 
(
	[FGErrorType_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]


