CREATE TABLE [dbo].[HOUSEHOLDRULE](
	[HOUSEHOLDRULE_ID] [int] IDENTITY(1,1) NOT NULL,
	[TABLE_ID] [int] NULL,
	[FIELD_ID] [int] NULL,
	[SURVEY_ID] [int] NULL,
 CONSTRAINT [PK_HOUSEHOLDRULE] PRIMARY KEY CLUSTERED 
(
	[HOUSEHOLDRULE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]


