CREATE TABLE [dbo].[jf_DODTOCL](
	[recage] [int] NULL,
	[dmissex] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[primpay] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[dx] [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[proccd] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[prn] [varchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[admdate] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[dispdate] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[dissvc] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[dmiscln] [varchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[drg] [varchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[mtf] [varchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[recspon] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[mancare] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[mdc] [varchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[acv] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[deersenr] [varchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[dmisbenf] [varchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[pn1stnm] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[pnlstnm] [varchar](26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[maln1tx] [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[maln2tx] [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[macitynm] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[mastcd] [varchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[maprzip] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[brthdate] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[dropdead] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[nomatch] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[updte] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[dropdead1] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[nomatch1] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[updte1] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[dropdead2] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[nomatch2] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[updte2] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]


