CREATE TABLE [dbo].[jf_dodippc](
	[patage] [int] NULL,
	[dmissex] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[dx] [char](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[proccd] [char](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[hcsrno] [char](22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[admdate] [char](9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[dispdate] [char](9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[dissvc] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[drg] [char](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[catchid] [char](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[mdc] [char](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[enrcode] [char](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[bencat] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[amtbill] [char](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ohipaid] [char](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[thrdprty] [char](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[thrdprty2] [char](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[coinsur] [char](9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[copay] [char](9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[govtpaid] [char](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[pn1stnm] [char](21) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[pnlstnm] [char](27) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[maln1tx] [char](41) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[maln2tx] [char](41) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[macitynm] [char](21) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[mastcd] [char](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[maprzip] [char](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[sponsvc] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[brthdate] [char](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[dropdead] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[nomatch] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[updte] [char](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[dropdead1] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[nomatch1] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[updte1] [char](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[dropdead2] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[nomatch2] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[udte2] [char](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]


