CREATE TABLE [dbo].[MAILINGSUMMARY](
	[SURVEY_ID] [int] NOT NULL,
	[DATMAILED] [datetime] NOT NULL,
	[INTPAGES] [int] NOT NULL,
	[MAILINGSTEP_ID] [int] NOT NULL,
	[SAMPLESET_ID] [int] NOT NULL,
	[MAILCOUNT] [int] NOT NULL,
 CONSTRAINT [PK_MAILINGSUMMARY] PRIMARY KEY CLUSTERED 
(
	[SURVEY_ID] ASC,
	[DATMAILED] ASC,
	[INTPAGES] ASC,
	[MAILINGSTEP_ID] ASC,
	[SAMPLESET_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]


