CREATE TABLE [dbo].[MAILINGSTEP](
	[MAILINGSTEP_ID] [int] IDENTITY(1,1) NOT NULL,
	[METHODOLOGY_ID] [int] NOT NULL,
	[SURVEY_ID] [int] NULL,
	[INTSEQUENCE] [int] NOT NULL,
	[SELCOVER_ID] [int] NULL,
	[BITSURVEYINLINE] [bit] NOT NULL,
	[BITSENDSURVEY] [bit] NOT NULL,
	[INTINTERVALDAYS] [int] NOT NULL,
	[BITTHANKYOUITEM] [bit] NOT NULL,
	[STRMAILINGSTEP_NM] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[BITFIRSTSURVEY] [bit] NOT NULL,
	[OverRide_Langid] [int] NULL,
	[MMMailingStep_id] [int] NULL,
	[MailingStepMethod_id] [int] NULL CONSTRAINT [DF__MAILINGST__Maili__292DD54A]  DEFAULT (0),
	[ExpireInDays] [int] NULL CONSTRAINT [DF__MAILINGST__Expir__2A21F983]  DEFAULT (84),
	[ExpireFromStep] [int] NULL,
	[Quota_ID] [int] NULL,
	[QuotaStopCollectionAt] [int] NULL CONSTRAINT [DF__MAILINGST__Quota__4BB98E26]  DEFAULT (0),
	[DaysInField] [int] NULL CONSTRAINT [DF__MAILINGST__DaysI__4CADB25F]  DEFAULT (0),
	[NumberOfAttempts] [int] NULL CONSTRAINT [DF__MAILINGST__Numbe__4DA1D698]  DEFAULT (0),
	[WeekDay_Day_Call] [bit] NULL CONSTRAINT [DF__MAILINGST__WeekD__4E95FAD1]  DEFAULT (0),
	[WeekDay_Eve_Call] [bit] NULL CONSTRAINT [DF__MAILINGST__WeekD__4F8A1F0A]  DEFAULT (0),
	[Sat_Day_Call] [bit] NULL CONSTRAINT [DF__MAILINGST__Sat_D__507E4343]  DEFAULT (0),
	[Sat_Eve_Call] [bit] NULL CONSTRAINT [DF__MAILINGST__Sat_E__5172677C]  DEFAULT (0),
	[Sun_Day_Call] [bit] NULL CONSTRAINT [DF__MAILINGST__Sun_D__52668BB5]  DEFAULT (0),
	[Sun_Eve_Call] [bit] NULL CONSTRAINT [DF__MAILINGST__Sun_E__535AAFEE]  DEFAULT (0),
	[CallBackOtherLang] [bit] NULL CONSTRAINT [DF__MAILINGST__CallB__544ED427]  DEFAULT (0),
	[CallbackUsingTTY] [bit] NULL CONSTRAINT [DF__MAILINGST__Callb__5542F860]  DEFAULT (0),
	[AcceptPartial] [bit] NULL CONSTRAINT [DF__MAILINGST__Accep__56371C99]  DEFAULT (0),
	[SendEmailBlast] [bit] NULL CONSTRAINT [DF__MAILINGST__SendE__572B40D2]  DEFAULT (0),
	[Vendor_ID] [int] NULL,
 CONSTRAINT [PK_MAILINGSTEP] PRIMARY KEY CLUSTERED 
(
	[MAILINGSTEP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


