CREATE TABLE [dbo].[MAILINGMETHODOLOGY](
	[METHODOLOGY_ID] [int] IDENTITY(1,1) NOT NULL,
	[SURVEY_ID] [int] NULL,
	[BITACTIVEMETHODOLOGY] [bit] NOT NULL,
	[STRMETHODOLOGY_NM] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[DATCREATE_DT] [datetime] NOT NULL,
	[StandardMethodologyID] [int] NOT NULL CONSTRAINT [DF__MAILINGME__Stand__2651689F]  DEFAULT (5),
 CONSTRAINT [PK_MAILINGMETHODOLOGY] PRIMARY KEY CLUSTERED 
(
	[METHODOLOGY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


