CREATE TABLE [dbo].[MB_BilliansTestImport](
	[txtDirectoryCode] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[txtName] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[txtFormerName] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[txtStreetAdd] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[txtMailAdd] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[txtCity] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[txtState] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[txtStreetZip] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[txtMailZip] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[txtCounty] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[txtPhone] [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[txtFax] [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[txt800] [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[txtEMail] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[txtUrl] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[intTotalBeds] [int] NULL,
	[txtMSA] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[txtFIPSState] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[txtFIPSCounty] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[intStaffedBeds] [int] NULL,
	[intAcuteBeds] [int] NULL,
	[intPsyBeds] [int] NULL,
	[intRehabBeds] [int] NULL,
	[intSubAcuteBeds] [int] NULL,
	[intNursingHomeBeds] [int] NULL,
	[intSNFBeds] [int] NULL,
	[intICUBeds] [int] NULL,
	[intCCUBeds] [int] NULL,
	[intNurseryBeds] [int] NULL,
	[intNICUBeds] [int] NULL,
	[intPICUBeds] [int] NULL,
	[intIcuCcuBeds] [int] NULL,
	[intORRooms] [int] NULL,
	[intOutpatientVisits] [int] NULL,
	[intAnnualERVisits] [int] NULL,
	[intAnnualOutpatientERCombined] [int] NULL,
	[intAnnualDischarges] [int] NULL,
	[intAnnualAdmissions] [int] NULL,
	[intDailyCensus] [int] NULL,
	[intBirths] [int] NULL,
	[intSurgeryInpatient] [int] NULL,
	[intSurgeryOutpatient] [int] NULL,
	[intAnnualSurgeryCombined] [int] NULL,
	[intNumberEmployees] [int] NULL,
	[intNumberFTEEmployees] [int] NULL,
	[txtFiscYrEnd] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[blnMedicalSurgical] [bit] NOT NULL,
	[blnAcuteCare] [bit] NOT NULL,
	[blnPsych] [bit] NOT NULL,
	[blnPsychOnly] [bit] NOT NULL,
	[blnSubAbuse] [bit] NOT NULL,
	[blnRehab] [bit] NOT NULL,
	[blnRehabOnly] [bit] NOT NULL,
	[blnCriticalAccess] [bit] NOT NULL,
	[blnSubAcuteCare] [bit] NOT NULL,
	[blnLongTermAcuteCare] [bit] NOT NULL,
	[blnNursingHomeCare] [bit] NOT NULL,
	[blnSNFCare] [bit] NOT NULL,
	[blnChildrensFacility] [bit] NOT NULL,
	[blnAmbulatorySurgery] [bit] NOT NULL,
	[blnOnSite] [bit] NOT NULL,
	[txtSpecialty] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[blnNotForProfit] [bit] NOT NULL,
	[blnForProfit] [bit] NOT NULL,
	[blnProprietary] [bit] NOT NULL,
	[blnOwnChurch] [bit] NOT NULL,
	[blnOwnFederal] [bit] NOT NULL,
	[blnOwnState] [bit] NOT NULL,
	[blnOwnCounty] [bit] NOT NULL,
	[blnOwnCity] [bit] NOT NULL,
	[blnOwnHospitalAuth] [bit] NOT NULL,
	[blnJointCoac] [bit] NOT NULL,
	[blnCommAccredRehabFac] [bit] NOT NULL,
	[dteJCAHOAccred] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[blnAMA] [bit] NOT NULL,
	[blnAMAResidents] [bit] NOT NULL,
	[blnAMAInterns] [bit] NOT NULL,
	[blnAOAInterns] [bit] NOT NULL,
	[blnAOAResidents] [bit] NOT NULL,
	[blnTrainingForAdmin] [bit] NOT NULL,
	[blnTrainingForRadTechs] [bit] NOT NULL,
	[blnTrainingForLabTechs] [bit] NOT NULL,
	[blnTrainingForDietitians] [bit] NOT NULL,
	[blnSchoolForNursing] [bit] NOT NULL,
	[blnRNProgram] [bit] NOT NULL,
	[blnLPNProgram] [bit] NOT NULL,
	[txtManagedBy] [nvarchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[txtLeasedBy] [nvarchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[txtJointVenture] [nvarchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[txtJointVenture2] [nvarchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[txtGroupOwner] [nvarchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[txtGroupAffiliated] [nvarchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[txtGroupAffiliated2] [nvarchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[blnIncludes] [bit] NOT NULL,
	[txtMedicareProviderNumber] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[intDRG1] [int] NULL,
	[intDRG2] [int] NULL,
	[intDRG3] [int] NULL,
	[intDRG4] [int] NULL,
	[intDRG5] [int] NULL,
	[txtTotalSqFt] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[blnPendingConstRenovation] [bit] NOT NULL,
	[memDetailsOfProject] [ntext] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[memDetailsOfProject2] [ntext] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[txtProjectCompleteDate] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[blnNewHospital] [bit] NOT NULL,
	[dteDateClosed] [smalldatetime] NULL,
	[txtDunnsNo] [nvarchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[blnTeachHosp] [bit] NOT NULL,
	[txtEmailConv] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]


