CREATE TABLE [dbo].[mb_sampTrace](
	[RowNumber] [int] IDENTITY(0,1) NOT NULL,
	[EventClass] [int] NULL,
	[ApplicationName] [nvarchar](128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BinaryData] [image] NULL,
	[ClientProcessID] [int] NULL,
	[DatabaseID] [int] NULL,
	[DatabaseName] [nvarchar](128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Duration] [bigint] NULL,
	[EndTime] [datetime] NULL,
	[EventSequence] [bigint] NULL,
	[GroupID] [int] NULL,
	[HostName] [nvarchar](128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsSystem] [int] NULL,
	[LineNumber] [int] NULL,
	[LoginName] [nvarchar](128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LoginSid] [image] NULL,
	[NTDomainName] [nvarchar](128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NTUserName] [nvarchar](128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NestLevel] [int] NULL,
	[ObjectID] [int] NULL,
	[ObjectName] [nvarchar](128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ObjectType] [int] NULL,
	[RequestID] [int] NULL,
	[RowCounts] [bigint] NULL,
	[SPID] [int] NULL,
	[ServerName] [nvarchar](128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SessionLoginName] [nvarchar](128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SourceDatabaseID] [int] NULL,
	[StartTime] [datetime] NULL,
	[TextData] [ntext] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TransactionID] [bigint] NULL,
	[XactSequence] [bigint] NULL,
	[CPU] [int] NULL,
	[IntegerData] [int] NULL,
	[IntegerData2] [int] NULL,
	[Offset] [int] NULL,
	[Reads] [bigint] NULL,
	[Writes] [bigint] NULL,
	[State] [int] NULL,
	[Error] [int] NULL,
	[Severity] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[RowNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]


