CREATE TABLE [dbo].[METALOOKUP](
	[NUMMASTERTABLE_ID] [int] NOT NULL,
	[NUMMASTERFIELD_ID] [int] NOT NULL,
	[NUMLKUPTABLE_ID] [int] NOT NULL,
	[NUMLKUPFIELD_ID] [int] NOT NULL,
	[STRLKUP_TYPE] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_METALOOKUP] PRIMARY KEY CLUSTERED 
(
	[NUMMASTERTABLE_ID] ASC,
	[NUMMASTERFIELD_ID] ASC,
	[NUMLKUPTABLE_ID] ASC,
	[NUMLKUPFIELD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]


