CREATE TABLE [dbo].[METATABLE](
	[TABLE_ID] [int] IDENTITY(1,1) NOT NULL,
	[STRTABLE_NM] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STRTABLE_DSC] [varchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STUDY_ID] [int] NULL,
	[BITUSESADDRESS] [bit] NOT NULL,
 CONSTRAINT [PK_METATABLE] PRIMARY KEY CLUSTERED 
(
	[TABLE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]


