CREATE TABLE [dbo].[METAFIELDGROUPDEF](
	[FIELDGROUP_ID] [int] IDENTITY(1,1) NOT NULL,
	[STRFIELDGROUP_NM] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[strAddrCleanType] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[bitAddrCleanDefault] [bit] NULL DEFAULT (0),
 CONSTRAINT [PK_METAFIELDGROUPDEF] PRIMARY KEY CLUSTERED 
(
	[FIELDGROUP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]


