CREATE TABLE [dbo].[METASTRUCTURE](
	[TABLE_ID] [int] NOT NULL,
	[FIELD_ID] [int] NOT NULL,
	[BITKEYFIELD_FLG] [bit] NOT NULL,
	[BITUSERFIELD_FLG] [bit] NOT NULL,
	[BITMATCHFIELD_FLG] [bit] NOT NULL,
	[BITPOSTEDFIELD_FLG] [bit] NOT NULL,
	[bitPII] [bit] NULL,
	[bitAllowUS] [bit] NULL,
 CONSTRAINT [PK_METASTRUCTURE] PRIMARY KEY CLUSTERED 
(
	[TABLE_ID] ASC,
	[FIELD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]


