CREATE TABLE [dbo].[Norms_UnitsbyService](
	[client_id] [int] NULL,
	[client] [varchar](73) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[study_id] [int] NULL,
	[study] [varchar](43) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[survey_Id] [int] NOT NULL,
	[survey] [varchar](75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[sampleunit_Id] [int] NOT NULL,
	[unit] [varchar](75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ProjectNumber] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AD] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[service_id] [int] NULL,
	[service_name] [varchar](84) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UserSpecifiedService] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PickervsLegacy] [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[AHA_ID] [int] NULL,
	[HospitalName] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[city] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[state] [varchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Country] [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[region] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Admissions] [int] NULL,
	[BedSize] [int] NULL,
	[BedSizeGroups] [varchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TraumaHospital] [bit] NULL,
	[Government] [bit] NULL,
	[ForProfit] [bit] NULL,
	[ReligiousAffiliation] [bit] NULL,
	[Teaching] [bit] NULL,
	[RURAL] [bit] NULL,
	[sampleType] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]


