CREATE TABLE [dbo].[OVERRIDEITEM](
	[OVERRIDEITEM_ID] [int] IDENTITY(1,1) NOT NULL,
	[INTINTERVALDAYS] [int] NULL,
 CONSTRAINT [PK_OVERRIDEITEM] PRIMARY KEY CLUSTERED 
(
	[OVERRIDEITEM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]


