CREATE TABLE [dbo].[PAPERSIZE](
	[PAPERSIZE_ID] [int] IDENTITY(1,1) NOT NULL,
	[PAPERSIZE_NM] [char](7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[STRREGPOINTS] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STRSIZECODE] [char](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STRBARCODEA] [char](48) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STRBARCODEB] [char](48) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STRBARCODEC] [char](48) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STRBARCODED] [char](48) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[strTemplateCode] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_PAPERSIZE] PRIMARY KEY CLUSTERED 
(
	[PAPERSIZE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]


