CREATE TABLE [dbo].[PAPERCONFIG](
	[PAPERCONFIG_ID] [int] IDENTITY(1,1) NOT NULL,
	[STRPAPERCONFIG_NM] [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[INTLETTERHEAD] [int] NULL,
	[INTLETTER] [int] NULL,
	[INTLEGAL] [int] NULL,
	[INTTABLOID] [int] NULL,
	[INTDOUBLELEGAL] [int] NULL,
	[INTPAGES] [int] NULL,
	[INTPOSTCARD] [int] NULL,
 CONSTRAINT [PK_PAPERCONFIG] PRIMARY KEY CLUSTERED 
(
	[PAPERCONFIG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]


