CREATE TABLE [dbo].[PCL_SKIP](
	[SURVEY_ID] [int] NOT NULL,
	[SELQSTNS_ID] [int] NOT NULL,
	[SELSCLS_ID] [int] NOT NULL,
	[SCALEITEM] [int] NOT NULL,
	[NUMSKIP] [int] NULL,
	[NUMSKIPTYPE] [int] NULL
) ON [PRIMARY]


