CREATE TABLE [dbo].[PCLGENLOG](
	[PCLGENLOG_ID] [int] IDENTITY(1,1) NOT NULL,
	[PCLGENRUN_ID] [int] NOT NULL,
	[SURVEY_ID] [int] NULL,
	[SENTMAIL_ID] [int] NULL,
	[LOGENTRY] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATLOGGED] [datetime] NOT NULL,
 CONSTRAINT [PK_PCLGENLOG] PRIMARY KEY CLUSTERED 
(
	[PCLGENLOG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]


