CREATE TABLE [dbo].[PCLOUTPUT2](
	[SENTMAIL_ID] [int] NOT NULL,
	[INTSHEET_NUM] [int] NOT NULL,
	[PAPERSIZE_ID] [int] NULL,
	[INTPA] [int] NULL,
	[INTPB] [int] NULL,
	[INTPC] [int] NULL,
	[INTPD] [int] NULL,
	[PCLSTREAM] [image] NULL,
	[BITCOVER] [bit] NOT NULL,
 CONSTRAINT [PK_PCLOUTPUT2] PRIMARY KEY CLUSTERED 
(
	[SENTMAIL_ID] ASC,
	[INTSHEET_NUM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]


