CREATE TABLE [dbo].[PCLOBJECT](
	[PCLOBJECT_ID] [int] IDENTITY(1,1) NOT NULL,
	[PCLOBJECT_DSC] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PCLSTREAM] [image] NULL,
 CONSTRAINT [PK_PCLOBJECT] PRIMARY KEY CLUSTERED 
(
	[PCLOBJECT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]


