CREATE TABLE [dbo].[PCLReset_log](
	[PCLReset_ID] [int] IDENTITY(1,1) NOT NULL,
	[datCaptured] [datetime] NULL,
	[Comments] [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
PRIMARY KEY CLUSTERED 
(
	[PCLReset_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


