CREATE TABLE [dbo].[providerclinicCRITERIACLAUSE](
	[CRITERIACLAUSE_ID] [int] IDENTITY(1,1) NOT NULL,
	[CRITERIAPHRASE_ID] [int] NOT NULL,
	[CRITERIASTMT_ID] [int] NULL,
	[TABLE_ID] [int] NOT NULL,
	[FIELD_ID] [int] NOT NULL,
	[INTOPERATOR] [int] NULL,
	[STRLOWVALUE] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STRHIGHVALUE] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]


