CREATE TABLE [dbo].[QDEBatchType](
	[BatchType_id] [int] IDENTITY(1,1) NOT NULL,
	[strBatchType_Nm] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
 CONSTRAINT [PK_QDEBatchType] PRIMARY KEY CLUSTERED 
(
	[BatchType_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


