CREATE TABLE [dbo].[QPReportProc](
	[QPReportProc_ID] [int] IDENTITY(1,1) NOT NULL,
	[QPReport_ID] [int] NULL,
	[strReportProc_nm] [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[strDSN_nm] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
PRIMARY KEY CLUSTERED 
(
	[QPReportProc_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]


