CREATE TABLE [dbo].[QPReport](
	[QPReport_ID] [int] IDENTITY(1,1) NOT NULL,
	[strReport_nm] [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[QPReportCategory_id] [int] NULL,
	[UserGroup_id] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[QPReport_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]


