CREATE TABLE [dbo].[QUALPRO_SYSLOGS](
	[QUALPRO_SYSLOG_ID] [int] IDENTITY(1,1) NOT NULL,
	[EMPLOYEE_ID] [int] NOT NULL,
	[DATEVENT_DT] [datetime] NOT NULL,
	[EVENTTYPE_ID] [int] NOT NULL,
	[STRMODULE] [char](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[STUDY_ID] [int] NULL,
	[SURVEY_ID] [int] NULL,
 CONSTRAINT [PK_QUALPRO_SYSLOGS] PRIMARY KEY CLUSTERED 
(
	[QUALPRO_SYSLOG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]


