CREATE TABLE [dbo].[READMETHOD](
	[READMETHOD_ID] [int] NOT NULL,
	[BITMULTIRESP] [bit] NOT NULL,
	[STRREADMETHOD_NM] [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
 CONSTRAINT [PK_READMETHOD] PRIMARY KEY CLUSTERED 
(
	[READMETHOD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]


