CREATE TABLE [dbo].[RECURRINGENCOUNTER](
	[RECURRINGENC_ID] [int] IDENTITY(1,1) NOT NULL,
	[STUDY_ID] [int] NOT NULL,
	[STARTENC_ID] [int] NOT NULL,
	[ENDENC_ID] [int] NULL,
	[POP_ID] [int] NOT NULL,
 CONSTRAINT [PK_RECURRINGENCOUNTER] PRIMARY KEY CLUSTERED 
(
	[RECURRINGENC_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]


