CREATE TABLE [dbo].[REPORTINGHIERARCHY](
	[REPORTING_HIERARCHY_ID] [int] IDENTITY(1,1) NOT NULL,
	[SURVEY_ID] [int] NULL,
	[STUDY_ID] [int] NULL,
	[REPORTING_LEVEL_NM] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PRNT_REPORTING_HIERARCHY_ID] [int] NULL,
	[intTier] [int] NULL,
 CONSTRAINT [PK___1__14] PRIMARY KEY CLUSTERED 
(
	[REPORTING_HIERARCHY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]


