CREATE TABLE [dbo].[REPORTMANAGER_REPORTS](
	[REPORTNAME_ID] [int] NOT NULL,
	[REPORTNAME] [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REPORTPATH] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]


