CREATE TABLE [dbo].[SampleUnitLinkage](
	[SampleUnit_id] [int] NOT NULL,
	[LinkSampleUnit_id] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SampleUnit_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


