CREATE TABLE [dbo].[SAMPLEUNIT_11242009193814000](
	[SAMPLEUNIT_ID] [int] IDENTITY(1,1) NOT NULL,
	[CRITERIASTMT_ID] [int] NULL,
	[SAMPLEPLAN_ID] [int] NOT NULL,
	[PARENTSAMPLEUNIT_ID] [int] NULL,
	[STRSAMPLEUNIT_NM] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INTTARGETRETURN] [int] NULL,
	[INTMINCONFIDENCE] [int] NULL,
	[INTMAXMARGIN] [int] NULL,
	[NUMINITRESPONSERATE] [int] NULL,
	[NUMRESPONSERATE] [int] NULL,
	[REPORTING_HIERARCHY_ID] [int] NULL,
	[SUFacility_id] [int] NULL,
	[SUServices] [varchar](300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[bitsuppress] [bit] NOT NULL,
	[bitHCAHPS] [bit] NULL,
	[bitHHCAHPS] [bit] NULL,
	[Priority] [int] NOT NULL CONSTRAINT [DF__Sample_11242009193814005]  DEFAULT (1),
	[SampleSelectionType_id] [int] NOT NULL CONSTRAINT [DF__Sample_11242009193814004]  DEFAULT (1),
	[DontSampleUnit] [tinyint] NOT NULL CONSTRAINT [DF_SAMPLEU_11242009193814003]  DEFAULT (0),
 CONSTRAINT [PK_SAMPLEU_11242009193814001] PRIMARY KEY CLUSTERED 
(
	[SAMPLEUNIT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]


