CREATE TABLE [dbo].[SAMPLEUNITSECTION](
	[SAMPLEUNITSECTION_ID] [int] IDENTITY(1,1) NOT NULL,
	[SAMPLEUNIT_ID] [int] NULL,
	[SELQSTNSSECTION] [int] NULL,
	[SELQSTNSSURVEY_ID] [int] NULL,
 CONSTRAINT [PK_SAMPLEUNITSECTION] PRIMARY KEY CLUSTERED 
(
	[SAMPLEUNITSECTION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]


