CREATE TABLE [dbo].[SAMPLEUNITTREEINDEX](
	[SAMPLEUNIT_ID] [int] NOT NULL,
	[ANCESTORUNIT_ID] [int] NOT NULL,
 CONSTRAINT [PK_SAMPLEUNITTREEINDEX] PRIMARY KEY CLUSTERED 
(
	[SAMPLEUNIT_ID] ASC,
	[ANCESTORUNIT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]


