CREATE TABLE [dbo].[SAMPLEPLAN](
	[SAMPLEPLAN_ID] [int] IDENTITY(1,1) NOT NULL,
	[ROOTSAMPLEUNIT_ID] [int] NULL,
	[EMPLOYEE_ID] [int] NULL,
	[SURVEY_ID] [int] NULL,
	[DATCREATE_DT] [datetime] NOT NULL,
 CONSTRAINT [PK_SAMPLEPLAN] PRIMARY KEY CLUSTERED 
(
	[SAMPLEPLAN_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]


