CREATE TABLE [dbo].[SAMPLEDATASET](
	[SAMPLESET_ID] [int] NOT NULL,
	[DATASET_ID] [int] NOT NULL,
 CONSTRAINT [PK_SAMPLEDATASET] PRIMARY KEY CLUSTERED 
(
	[SAMPLESET_ID] ASC,
	[DATASET_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]


