CREATE TABLE [dbo].[SAMPLEUNIT](
	[SAMPLEUNIT_ID] [int] IDENTITY(1,1) NOT NULL,
	[CRITERIASTMT_ID] [int] NULL,
	[SAMPLEPLAN_ID] [int] NOT NULL,
	[PARENTSAMPLEUNIT_ID] [int] NULL,
	[STRSAMPLEUNIT_NM] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INTTARGETRETURN] [int] NULL,
	[INTMINCONFIDENCE] [int] NULL,
	[INTMAXMARGIN] [int] NULL,
	[NUMINITRESPONSERATE] [int] NULL,
	[NUMRESPONSERATE] [int] NULL,
	[REPORTING_HIERARCHY_ID] [int] NULL,
	[SUFacility_id] [int] NULL,
	[SUServices] [varchar](300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[bitsuppress] [bit] NOT NULL,
	[bitHCAHPS] [bit] NULL,
	[bitHHCAHPS] [bit] NULL,
	[bitCHART] [bit] NULL,
	[bitMNCM] [bit] NULL,
	[Priority] [int] NOT NULL CONSTRAINT [DF__SAMPLEUNI__Prior__324D2B30]  DEFAULT ((1)),
	[SampleSelectionType_id] [int] NOT NULL CONSTRAINT [DF__SAMPLEUNI__Sampl__33414F69]  DEFAULT ((1)),
	[DontSampleUnit] [tinyint] NOT NULL CONSTRAINT [DF_SAMPLEUNIT_DontSampleUnit]  DEFAULT ((0)),
	[bitACOCAHPS] [bit] NULL DEFAULT ((0)),
 CONSTRAINT [PK_SAMPLEUNIT] PRIMARY KEY CLUSTERED 
(
	[SAMPLEUNIT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


