CREATE TABLE [dbo].[SCANIMPORTERROR](
	[SCANIMPORTERROR_ID] [int] IDENTITY(1,1) NOT NULL,
	[STRLITHOCODE] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[DATERRORDATE] [datetime] NOT NULL,
	[intErrorCode] [int] NULL CONSTRAINT [DF_SCANIMPORTERROR_intErrorCode]  DEFAULT (0),
	[strSTRBatchNumber] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_SCANIMPORTERROR] PRIMARY KEY CLUSTERED 
(
	[SCANIMPORTERROR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]


