CREATE TABLE [dbo].[SELECTEDSAMPLE](
	[SELECTEDSAMPLE_ID] [int] IDENTITY(1,1) NOT NULL,
	[SAMPLESET_ID] [int] NOT NULL,
	[STUDY_ID] [int] NULL,
	[POP_ID] [int] NOT NULL,
	[SAMPLEUNIT_ID] [int] NOT NULL,
	[STRUNITSELECTTYPE] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[intExtracted_flg] [int] NULL,
	[enc_id] [int] NULL,
	[ReportDate] [datetime] NULL,
	[SampleEncounterDate] [datetime] NULL,
 CONSTRAINT [PK_SELECTEDSAMPLE] PRIMARY KEY CLUSTERED 
(
	[SELECTEDSAMPLE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]


