CREATE TABLE [dbo].[SENTMAILING](
	[SENTMAIL_ID] [int] IDENTITY(1,1) NOT NULL,
	[SCHEDULEDMAILING_ID] [int] NULL,
	[DATGENERATED] [datetime] NULL,
	[DATPRINTED] [datetime] NULL,
	[DATMAILED] [datetime] NULL,
	[METHODOLOGY_ID] [int] NULL,
	[PAPERCONFIG_ID] [int] NULL,
	[STRLITHOCODE] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STRPOSTALBUNDLE] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INTPAGES] [int] NULL,
	[DATUNDELIVERABLE] [datetime] NULL,
	[INTRESPONSESHAPE] [int] NULL,
	[STRGROUPDEST] [varchar](9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[datDeleted] [datetime] NULL,
	[datBundled] [datetime] NULL,
	[intReprinted] [int] NULL CONSTRAINT [DF_SENTMAILING_intReprinted]  DEFAULT (0),
	[datReprinted] [datetime] NULL,
	[LangID] [int] NULL,
	[datExpire] [datetime] NULL,
	[Country_id] [int] NOT NULL CONSTRAINT [DF__SENTMAILI__Count__6F563970]  DEFAULT ((1)),
	[bitExported] [bit] NULL CONSTRAINT [DF_SENTMAILING_bitModified]  DEFAULT ((0)),
 CONSTRAINT [PK_SENTMAILING] PRIMARY KEY CLUSTERED 
(
	[SENTMAIL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


