CREATE TABLE [dbo].[skd_tmp_alex_DS202372](
	[enc_id] [int] NOT NULL,
	[NewRecordDate] [datetime] NULL,
	[HServiceType] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HVisitType] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HAdmissionSource] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HDischargeStatus] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HAdmitAge] [int] NULL,
	[HCatAge] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MSDRG] [varchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HServiceDes] [int] NULL,
	[HNQLDesc] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VisitType] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceIndicator] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VisitNum] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AdmitDate] [datetime] NULL,
	[ClinicNum] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DischargeDate] [datetime] NULL,
	[NurseStation] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LengthOfStay] [int] NULL,
	[ICD9] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AdmitSource] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DischargeStatus] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Shift] [varchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AdmitDrID] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AdmitDrSpec] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DrID] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DrSpec] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FinClass] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PlanNumber] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PLANNUM2] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PLANNUM3] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PLANNUM4] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PlanName] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PlanName2] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PlanName3] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOSCheck] [int] NULL,
	[pop_id] [int] NULL,
	[Enc_Mtch] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceArea] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_2] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_3] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_4] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceType] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SpanishDay] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SpanishMonth] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SpanishYear] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SvyType] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FacilityNum] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_5] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FacilityName] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ICU] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DrTitle] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DrLastName] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DrFirstName] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DrNameStat] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DrNPI] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceDate] [datetime] NULL,
	[ServiceInd_6] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]


