CREATE TABLE [dbo].[skd_tmp_avery_DS_202625](
	[DischargeStatus] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AdmitTime] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DischargeTime] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DRG] [varchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NewRecordDate] [datetime] NULL,
	[FacilityNum] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DrID] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AdmitDate] [datetime] NULL,
	[AdmitSource] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DischargeDate] [datetime] NULL,
	[AdmitDrID] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ConsultDrID] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CPT4] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ICD9] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LengthOfStay] [int] NULL,
	[VisitNum] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DrSpec] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DischargeDest] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DischgDrSpec] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DischgDrID] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ICD9_2] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClinicName] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DepartmentNum] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceDate] [datetime] NULL,
	[pop_id] [int] NULL,
	[enc_id] [int] NOT NULL,
	[VisitType] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceIndicator] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClinicNum] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Restriction] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RoomNum] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RoomClass] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BedNum] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_21] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NurseStation] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Enc_Mtch] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HServiceType] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HVisitType] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HAdmissionSource] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HDischargeStatus] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HAdmitAge] [int] NULL,
	[HCatAge] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MSDRG] [varchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AdmitDrSpec] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ConsultDrSpec] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOSCheck] [int] NULL,
	[HServiceDes] [int] NULL,
	[ServiceInd_11] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]


