CREATE TABLE [dbo].[skd_tmp_avery_DS_202623](
	[DischargeStatus] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AdmitTime] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DischargeTime] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DRG] [varchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NewRecordDate] [datetime] NULL,
	[FacilityNum] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DrID] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AdmitDate] [datetime] NULL,
	[AdmitSource] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DischargeDate] [datetime] NULL,
	[CPT4] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DischargeUnit] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ICD9] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VisitNum] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DrSpec] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DischargeDest] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DischgDrID] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CarePath] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DepartmentNum] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceDate] [datetime] NULL,
	[pop_id] [int] NULL,
	[enc_id] [int] NOT NULL,
	[VisitType] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceIndicator] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClinicNum] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Restriction] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AdmitDrFName] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AdmitDrLName] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ConsultDrFName] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ConsultDrLName] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DschgDrFName] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DschgDrLName] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RoomNum] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RoomClass] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BedNum] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_22] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_30] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_31] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AdmitNameStat] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ConsultNameStat] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DschgNameStat] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Shift] [varchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DayIndicator] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Enc_Mtch] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DRID2] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HServiceType] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HVisitType] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HAdmissionSource] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HDischargeStatus] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HAdmitAge] [int] NULL,
	[HCatAge] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MSDRG] [varchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOSCheck] [int] NULL,
	[HServiceDes] [int] NULL,
	[ConsultDrSpec] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AdmitDrSpec] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DischgDrSpec] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_2] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_3] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_4] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_5] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_10] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_6] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_7] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]


