CREATE TABLE [dbo].[skd_tmp_INC0013524_Peconic](
	[DischargeStatus] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DRG] [varchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NewRecordDate] [datetime] NULL,
	[DrID] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AdmitDate] [datetime] NULL,
	[AdmitSource] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DischargeDate] [datetime] NULL,
	[DischargeUnit] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VisitNum] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FacilityName] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[pop_id] [int] NULL,
	[enc_id] [int] NOT NULL,
	[VisitType] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_20] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Enc_Mtch] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HServiceType] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HVisitType] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HAdmissionSource] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HDischargeStatus] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HAdmitAge] [int] NULL,
	[HCatAge] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SpanishDay] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SpanishMonth] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SpanishYear] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceDate] [datetime] NULL,
	[ServiceInd_10] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MSDRG] [varchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HServiceDes] [int] NULL,
	[FinClass] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOSCheck] [int] NULL
) ON [PRIMARY]


