CREATE TABLE [dbo].[skd_tmp_INC0013078_encounterdata](
	[DischargeStatus] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AdmitTime] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DischargeTime] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NewRecordDate] [datetime] NULL,
	[FacilityNum] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DrID] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AdmitDate] [datetime] NULL,
	[AdmitSource] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DischargeUnit] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VisitNum] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[pop_id] [int] NULL,
	[enc_id] [int] NOT NULL,
	[VisitType] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RoomNum] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BedNum] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceType] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Surgeon] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Enc_Mtch] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DRID2] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DRID3] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Serviceind_100] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HServiceType] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HVisitType] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HAdmissionSource] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HDischargeStatus] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HAdmitAge] [int] NULL,
	[HCatAge] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MSDRG] [varchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOSCheck] [int] NULL,
	[AdmitSource2] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HServiceDes] [int] NULL,
	[HNQLDesc] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DischargeDate] [datetime] NULL,
	[SpanishDay] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SpanishMonth] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SpanishYear] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PhServDate] [datetime] NULL,
	[PhServInd1] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AdmitPriority] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Visittype2] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FacilityName] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LengthOfStay] [int] NULL,
	[EDAdmit] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ICD9] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ICD9_2] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ICD9_3] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ICD9_4] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CPT4] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CPT4_2] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CPT4_3] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CPT4_4] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceIndicator] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_2] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_3] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_4] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_5] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Serviceind_101] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Serviceind_102] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Serviceind_103] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Serviceind_104] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_105] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_106] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_107] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_108] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_109] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_110] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_111] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_112] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_113] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_114] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_115] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_116] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_117] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_118] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_119] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_120] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_121] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_122] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_123] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_124] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_125] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_126] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_127] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_128] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_129] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ICD9_5] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CPT4_5] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]


