CREATE TABLE [dbo].[skd_tmp_INC0013299](
	[enc_id] [int] NOT NULL,
	[NewRecordDate] [datetime] NULL,
	[pop_id] [int] NULL,
	[FacilityNum] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DischargeUnit] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VisitNum] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DischargeStatus] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VisitType] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AdmitDate] [datetime] NULL,
	[DischargeDate] [datetime] NULL,
	[LengthOfStay] [int] NULL,
	[AdmitSource] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DrID] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClinicNum] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FinClass] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceIndicator] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceDate] [datetime] NULL,
	[DischargeDest] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HServiceType] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HVisitType] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HAdmissionSource] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HDischargeStatus] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HAdmitAge] [int] NULL,
	[HCatAge] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DRG] [varchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_2] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_3] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MSDRG] [varchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HServiceDes] [int] NULL,
	[LOSCheck] [int] NULL,
	[Enc_Mtch] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]


