CREATE TABLE [dbo].[SkipQstns](
	[Skip_id] [int] NOT NULL,
	[QstnCore] [int] NOT NULL,
 CONSTRAINT [PK_SkipQstns] PRIMARY KEY CLUSTERED 
(
	[Skip_id] ASC,
	[QstnCore] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


