CREATE TABLE [dbo].[SSRS_MS_SamplePlanWorksheetAll_Log](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[DateLogged] [datetime] NULL,
	[Event] [varchar](1500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_SSRS_MS_SamplePlanWorksheetAll_Log] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


