CREATE TABLE [dbo].[STATE](
	[STATE_ID] [int] IDENTITY(1,1) NOT NULL,
	[STATE_CD] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[STATE_NM] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
 CONSTRAINT [PK_STATE] PRIMARY KEY CLUSTERED 
(
	[STATE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]


