CREATE TABLE [dbo].[STUDYDELIVERYDATE](
	[DELIVERYDATE_ID] [int] IDENTITY(1,1) NOT NULL,
	[STUDY_ID] [int] NOT NULL,
	[CONTACT_ID] [int] NULL,
	[DATDELIVERY_DT] [datetime] NOT NULL,
	[STRDELIVERY_DSC] [varchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[DATWORKED] [datetime] NULL,
	[INTHOURSWORKED] [int] NULL,
	[BITBILLABLE] [bit] NOT NULL,
	[BITCLIENTREQUEST] [bit] NOT NULL,
	[BITCORRECTION] [bit] NOT NULL,
 CONSTRAINT [PK_STUDYDELIVERYDATE] PRIMARY KEY CLUSTERED 
(
	[DELIVERYDATE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]


