CREATE TABLE [dbo].[STUDYREPORTTYPE](
	[STUDYREPORTTYPE_ID] [int] IDENTITY(1,1) NOT NULL,
	[REPORTTYPE_ID] [int] NOT NULL,
	[STUDY_ID] [int] NOT NULL,
	[STRREPORTNOTE] [varchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_STUDYREPORTTYPE] PRIMARY KEY CLUSTERED 
(
	[STUDYREPORTTYPE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]


