CREATE TABLE [dbo].[STUDYCOMPARISON](
	[STUDYCOMPARISON_ID] [int] IDENTITY(1,1) NOT NULL,
	[STUDY_ID] [int] NOT NULL,
	[STATE_ID] [int] NULL,
	[COMPARISONTYPE_ID] [int] NOT NULL,
	[MKTGUIDE_MSA_ID] [int] NULL,
	[mktguideplantype_id] [int] NULL,
 CONSTRAINT [PK_STUDYCOMPARISON] PRIMARY KEY CLUSTERED 
(
	[STUDYCOMPARISON_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]


