CREATE TABLE [dbo].[SURVEY_DEF](
	[SURVEY_ID] [int] IDENTITY(1,1) NOT NULL,
	[STUDY_ID] [int] NOT NULL,
	[STRSURVEY_NM] [char](10) NOT NULL,
	[STRSURVEY_DSC] [varchar](40) NULL,
	[INTRESPONSE_RECALC_PERIOD] [int] NOT NULL,
	[INTRESURVEY_PERIOD] [int] NULL,
	[BITREPEATINGENCOUNTERS_FLG] [bit] NOT NULL,
	[BITPHYSASSIST_NAME_FLG] [bit] NOT NULL,
	[BITMINOR_EXCEPT_FLG] [bit] NOT NULL,
	[BITNEWBORN_FLG] [bit] NOT NULL,
	[DATSURVEY_START_DT] [datetime] NULL,
	[DATSURVEY_END_DT] [datetime] NULL,
	[STRMAILFREQ] [char](9) NOT NULL,
	[INTSAMPLESINPERIOD] [int] NOT NULL,
	[STRXMITROUTE] [char](16) NULL,
	[BITUSECOMMENTS] [bit] NOT NULL,
	[STRCMNTCOPYTYPE] [varchar](15) NULL,
	[STRCMNTSORT] [varchar](40) NULL,
	[BITSENDCMNTOUT] [bit] NOT NULL,
	[STRSPECIALINSTRUCTIONS] [text] NULL,
	[STRCMNTMAILFREQ] [char](9) NULL,
	[STRCMNTCARRIER] [varchar](14) NULL,
	[STROTHERINSTRUCTIONS] [varchar](40) NULL,
	[STRCMNTTYPING_DBVER] [varchar](40) NULL,
	[BITCMNTTYPING_ONDISK] [bit] NOT NULL,
	[STRCMNT_CMNT] [varchar](255) NULL,
	[BITVALIDATED_FLG] [bit] NOT NULL,
	[DATVALIDATED] [datetime] NULL,
	[BITFORMGENRELEASE] [bit] NOT NULL,
	[BITLAYOUTVALID] [bit] NOT NULL,
	[BITDYNAMIC] [bit] NOT NULL,
	[STRCUTOFFRESPONSE_CD] [char](1) NULL,
	[cutofftable_id] [int] NULL,
	[cutofffield_id] [int] NULL,
	[strHouseholdingType] [char](1) NOT NULL,
	[bitDoHousehold] [bit] NOT NULL,
	[vcHouseholding] [char](1) NULL,
	[intQuarter] [int] NULL,
	[weighttype] [tinyint] NOT NULL,
	[bitmultreturns] [bit] NULL,
	[Priority_Flg] [tinyint] NULL,
	[bitEnforceSkip] [bit] NULL,
	[strclientfacingName] [varchar](42) NULL,
	[SurveyType_id] [int] NULL,
	[AHANumber] [int] NULL,
	[SurveyTypeDef_id] [int] NULL,
	[ReSurveyMethod_id] [int] NOT NULL,
	[SamplingAlgorithmID] [int] NULL,
	[SampleEncounterField_id] [int] NULL,
	[SampleEncounterTable_id] [int] NULL,
	[Contract] [varchar](9) NULL,
	[bitPhoneTelematch] [bit] NULL,
	[Active] [bit] NULL,
	[PervasiveMapName] [varchar](255) NULL,
	[ContractedLanguages] [varchar](50) NULL,
	[SurveySubType_ID] [int] NULL,
	[QuestionnaireType_ID] [int] NULL,
 CONSTRAINT [PK_SURVEY_DEF] PRIMARY KEY CLUSTERED 
(
	[SURVEY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]



