CREATE TABLE [dbo].[SurveyLanguage](
	[Survey_id] [int] NOT NULL,
	[LangID] [int] NOT NULL,
 CONSTRAINT [PK_SURVEYLANGUAGE] PRIMARY KEY NONCLUSTERED 
(
	[Survey_id] ASC,
	[LangID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]


