CREATE TABLE [dbo].[TABLEDEF](
	[QPC_ID] [int] IDENTITY(1,1) NOT NULL,
	[STRFULL] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FIELDTYPE] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FIELDLEN] [float] NULL,
	[FIELDREQUIRED] [bit] NOT NULL,
	[QUESTION] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCALE] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOGO] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TEXTBOX] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PCL] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COVER] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[QPC_SKIP] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_TABLEDEF] PRIMARY KEY CLUSTERED 
(
	[QPC_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]


