CREATE TABLE [dbo].[TAGEXCEPTION](
	[TAGEXCEPTION_ID] [int] IDENTITY(1,1) NOT NULL,
	[TAG_ID] [int] NULL,
	[TABLE_ID] [int] NULL,
	[FIELD_ID] [int] NULL,
	[STUDY_ID] [int] NULL,
 CONSTRAINT [PK_TAGEXCEPTION] PRIMARY KEY CLUSTERED 
(
	[TAGEXCEPTION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]


