CREATE TABLE [dbo].[TASKS](
	[WO_NUM] [float] NULL,
	[TASK] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TYPE] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REQUEST] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REQDATE] [datetime] NULL,
	[REQTIME] [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OPENBY] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OPENDATE] [datetime] NULL,
	[OPENTIME] [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MODIBY] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MODIDATE] [datetime] NULL,
	[MODITIME] [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CLSDBY] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CLSDDATE] [datetime] NULL,
	[CLSDTIME] [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ELAPSETIME] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ELAPSEMIN] [float] NULL,
	[PRIORITY] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DUEDATE] [datetime] NULL,
	[RESPONS] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ASSNDATE] [datetime] NULL,
	[COMPLETED] [datetime] NULL,
	[HOURS] [float] NULL,
	[RATE] [float] NULL,
	[CHARGE] [float] NULL,
	[WS_NUM] [float] NULL,
	[DEPT_NUM] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEPT] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PHONE] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PHONE_EXT] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOCATION] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DESCRIPT] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WO_TEXT1] [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WO_TEXT2] [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WO_TEXT3] [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WO_TEXT4] [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WO_TEXT5] [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WO_TEXT6] [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WO_DATE1] [datetime] NULL,
	[WO_DATE2] [datetime] NULL,
	[WO_NUM1] [float] NULL,
	[WO_INT1] [float] NULL,
	[NOTE] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FT] [bit] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]


