CREATE TABLE [dbo].[TOCL](
	[TOCL_ID] [int] IDENTITY(1,1) NOT NULL,
	[STUDY_ID] [int] NOT NULL,
	[POP_ID] [int] NOT NULL,
	[DATTOCL_DAT] [datetime] NOT NULL,
 CONSTRAINT [PK_TOCL] PRIMARY KEY CLUSTERED 
(
	[TOCL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]


