CREATE TABLE [dbo].[UNIKEYS](
	[STUDY_ID] [int] NOT NULL,
	[SAMPLESET_ID] [int] NOT NULL,
	[SAMPLEUNIT_ID] [int] NOT NULL,
	[POP_ID] [int] NOT NULL,
	[TABLE_ID] [int] NOT NULL,
	[KEYVALUE] [int] NULL,
 CONSTRAINT [PK_UNIKEYS] PRIMARY KEY CLUSTERED 
(
	[STUDY_ID] ASC,
	[SAMPLESET_ID] ASC,
	[SAMPLEUNIT_ID] ASC,
	[POP_ID] ASC,
	[TABLE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]


