CREATE TABLE [dbo].[UnValidatedSurveys_INC0032729](
	[SCHEDULEDMAILING_ID] [int] NOT NULL,
	[MAILINGSTEP_ID] [int] NULL,
	[SAMPLEPOP_ID] [int] NULL,
	[OVERRIDEITEM_ID] [int] NULL,
	[SENTMAIL_ID] [int] NULL,
	[METHODOLOGY_ID] [int] NULL,
	[DATGENERATE] [datetime] NOT NULL,
	[strsurvey_nm] [char](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]


