CREATE TABLE [dbo].[bd_pepc_citrusvalleyresults](
	[QUESTIONRESULT_ID] [int] NOT NULL,
	[QUESTIONFORM_ID] [int] NOT NULL,
	[SAMPLEUNIT_ID] [int] NOT NULL,
	[QSTNCORE] [int] NOT NULL,
	[INTRESPONSEVAL] [int] NOT NULL,
	[QPC_TIMESTAMP] [timestamp] NULL
) ON [PRIMARY]


