CREATE TABLE [dbo].[s545popload](
	[LName] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FName] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Middle] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Addr] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[City] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ST] [varchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZIP5] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DOB] [datetime] NULL,
	[Sex] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Age] [int] NULL,
	[AddrStat] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AddrErr] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Zip4] [varchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NewRecordDate] [datetime] NULL,
	[LangID] [int] NULL,
	[Del_Pt] [varchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FacilityNum] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SSN] [varchar](9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Suffix] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Title] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DischargeDate] [datetime] NULL,
	[ICD9] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FacilityName] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceDate] [datetime] NULL,
	[pop_id] [int] NOT NULL,
	[Mbrtype] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SvyType] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NameStat] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CPT] [int] NULL,
	[VISN] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VISNname] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EPRPFlag] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GulfWar] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SampWt] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RespWt] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Addr2] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OP_GWFlag] [varchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Country] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Restriction] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceIndicator] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TOCL] [int] NULL,
	[HospitalID] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_9] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_11] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]


