CREATE TABLE [dbo].[s818popload](
	[MRN] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LName] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FName] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Addr] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[City] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ST] [varchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZIP5] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DOB] [datetime] NULL,
	[Sex] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Age] [int] NULL,
	[AddrStat] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AddrErr] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Zip4] [varchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NewRecordDate] [datetime] NULL,
	[LangID] [int] NULL,
	[Del_Pt] [varchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Title] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[pop_id] [int] NOT NULL,
	[NameStat] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Province] [varchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Postal_Code] [varchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Pop_Mtch_Err] [varchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Pop_Mtch] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AddrAlt1] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Del_PtA1] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Zip4Alt1] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Zip5Alt1] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AddrErrA1] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STAlt1] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AddrStatA1] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CityAlt1] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ResProv] [varchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ResLangid] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GuarPhone] [varchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GuarRelation] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FamLangid] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCCGender] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]


