CREATE TABLE [dbo].[stevekennedy](
	[DischargeStatus] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AdmitTime] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DischargeTime] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DRG] [varchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NewRecordDate] [datetime] NULL,
	[DrID] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AdmitDate] [datetime] NULL,
	[AdmitSource] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AdmitDrID] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CPT4] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DischargeUnit] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ICD9] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LengthOfStay] [int] NULL,
	[VisitNum] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DischargeDest] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ICD9_2] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ICD9_3] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClinicName] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CPT4_2] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CPT4_3] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceDate] [datetime] NULL,
	[pop_id] [int] NULL,
	[enc_id] [int] NOT NULL,
	[UtilizationCode] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClinicNum] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_2] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_8] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_9] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_10] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_11] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RoomClass] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BedNum] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CPT4_4] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ICD9_4] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ICD9_5] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VisitType] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DischargeDate] [datetime] NULL,
	[DrSpec] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Enc_Mtch] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Enc_Mtch_Err] [varchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FacilityNum] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FinClass] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceIndicator] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SpanishDay] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SpanishMonth] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SpanishYear] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceInd_33] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HServiceType] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HVisitType] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HAdmissionSource] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HDischargeStatus] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HAdmitAge] [int] NULL,
	[HCatAge] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MSDRG] [varchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOSCheck] [int] NULL,
	[ServiceInd_15] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DRID2] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Visittype2] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AdmitType] [varchar](42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]


