CREATE TABLE [dbo].[SteveSchedMailing](
	[SCHEDULEDMAILING_ID] [int] NOT NULL,
	[MAILINGSTEP_ID] [int] NULL,
	[SAMPLEPOP_ID] [int] NULL,
	[OVERRIDEITEM_ID] [int] NULL,
	[SENTMAIL_ID] [int] NULL,
	[METHODOLOGY_ID] [int] NULL,
	[DATGENERATE] [datetime] NOT NULL
) ON [PRIMARY]


