'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''eToolKit_Preferences class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class eToolKit_Preferences

    '''<summary>
    '''SideNav1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SideNav1 As Global.Nrc.MySolutions.eToolKit_UserControls_SideNav

    '''<summary>
    '''BreadCrumbs1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BreadCrumbs1 As Global.Nrc.MySolutions.UserControls_BreadCrumbs

    '''<summary>
    '''PageLogo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PageLogo1 As Global.Nrc.MySolutions.eToolKit_UserControls_PageLogo

    '''<summary>
    '''rbtCompDatasets control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbtCompDatasets As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''rbtAnalysis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbtAnalysis As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''rblCENot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblCENot As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''SaveButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaveButton As Global.System.Web.UI.WebControls.Button
End Class
