BEGIN TRANSACTION

CREATE TABLE dbo.DATASET_QUEUE
(
    DATASET_QUEUE_ID int NOT NULL IDENTITY (1, 1)
              CONSTRAINT [PK_DATASET_QUEUE] PRIMARY KEY CLUSTERED,
    DATASET_ID int NOT NULL
              CONSTRAINT [FK_DATASET_ID] FOREIGN KEY
              ( DATASET_ID )
              REFERENCES dbo.DATA_SET
              ( DATASET_ID ),
    strSTATE nvarchar(10) NOT NULL,
    datSTART_DT datetime NULL,
    datEND_DT datetime NULL
)
GO

ALTER TABLE dbo.STUDY ADD bitAutosample BIT NOT NULL DEFAULT 0
GO

COMMIT TRANSACTION