CREATE TABLE [dbo].[PU_DefaultMail](
	[Format] [tinyint] NOT NULL,
	[Subject] [varchar](64) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Message] [varchar](7950) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Format] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


