CREATE TABLE [dbo].[PUR_ResultHeadInfo](
	[PUReport_ID] [int] NOT NULL,
	[GenerateDate] [datetime] NOT NULL,
	[Title] [varchar](128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK__PUR_ResultHeadIn__489AC854] PRIMARY KEY CLUSTERED 
(
	[PUReport_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


