CREATE TABLE [dbo].[Team](
	[Team_ID] [int] NOT NULL,
	[TeamName] [varchar](64) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[TeamDescription] [varchar](256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
PRIMARY KEY CLUSTERED 
(
	[Team_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


