CREATE TABLE [dbo].[TeamClient](
	[Team_ID] [int] NOT NULL,
	[Client_ID] [int] NOT NULL,
 CONSTRAINT [PK_TeamClient] PRIMARY KEY CLUSTERED 
(
	[Team_ID] ASC,
	[Client_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


