'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class Upload
    Protected WithEvents Head1 As System.Web.UI.HtmlControls.HtmlHead
    Protected WithEvents form1 As System.Web.UI.HtmlControls.HtmlForm
    Protected WithEvents PageHeader As ucHeader
    Protected WithEvents PageLogo As PageLogo
    Protected WithEvents btnHist As System.Web.UI.WebControls.Button
    Protected WithEvents UploadStatus As System.Web.UI.WebControls.Label
    Protected WithEvents PageFooter1 As ucFooter1
    Protected WithEvents SecurityControl1 As ucSecurity
End Class
