'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class eToolKit_SiteRequirements
    Protected WithEvents SideNav1 As eToolKit_UserControls_SideNav
    Protected WithEvents BreadCrumbs1 As UserControls_BreadCrumbs
    Protected WithEvents PageLogo1 As eToolKit_UserControls_PageLogo
    Protected WithEvents CautionDiv As System.Web.UI.HtmlControls.HtmlGenericControl
    Protected WithEvents JavascriptDiv As System.Web.UI.HtmlControls.HtmlGenericControl
    Protected WithEvents CookiesDiv As System.Web.UI.HtmlControls.HtmlGenericControl
End Class
