ALTER TABLE dbo.TransformMapping ADD CONSTRAINT [PK_TransformMapping] PRIMARY KEY CLUSTERED
(
	TransformMappingId ASC
) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO