ALTER TABLE dbo.ClientTransform ADD CONSTRAINT PK_ClientTransform PRIMARY KEY CLUSTERED
(
		[Client_id] ASC,
		[Study_id] ASC,
		[Survey_id] ASC,
		[TransformId] ASC
) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO